/-
Papers/REC/JBCalculus.lean

**The continuous functional calculus of a JB-algebra** (Hanche-Olsen–Størmer,
*Jordan Operator Algebras*, 3.2.4): for `a` in a JB-algebra `A` (REC 44,
`JBAlgebra`), the closed unital subalgebra `C(a)` generated by `a` is associative
and isometrically, multiplicatively and order-isomorphic to `C(sp a, ℝ)`.
Foundational for REC 136's structure theory and SEA 16's exceptional case.

Plan (2026-09-26; budget ~4 h, ~3,000 lines, compiled increments).
1. Power-associativity (`jbPow_mul_jbPow`): the tree's EJA induction
   (`Theses.B.Eff.eja_pow_aux`) uses only commutativity, bilinearity and the
   linearised Jordan identity (Mathlib's `IsCommJordan` linearisation), so it is
   transplanted verbatim to `JBAlgebra`.  Evaluation `ℝ[X] → A` is multiplicative.
2. Closed subalgebras: a closed subspace `S ∋ 1` with `S * S ⊆ S` is again a
   `JBAlgebra` (`ClosedJBSub`, same order, unit, norm), so the whole JB toolkit
   (`exists_sq_add`, `jb_sq_nonneg`, …) runs *inside* `S`.  `C(a)` := closure of
   the polynomials in `a`; associative by continuity of the product.
3. Gelfand for an *associative* JB-algebra `B`, directly via characters (no
   complexification, no Gelfand–Mazur):
   positive cone closed under products (`(x+ε)(y+ε) = (st)²` from approximate roots);
   states as a compact convex set in the product topology on `B → ℝ`;
   a state attaining `±‖b‖` from Hahn–Banach (`exists_dual_vector` at `‖b‖1 ± b`);
   an extreme point of the face `{φ(b) = ±‖b‖}` (Krein–Milman) is multiplicative
   (`φ(c·)/φ(c)` splits `φ`); so `Γ : B → C(X, ℝ)` on the character space is
   isometric; Stone–Weierstrass + completeness make it onto; order iso via roots.
4. Consequences: `‖b²‖ = ‖b‖²` in every JB-algebra; `sp(a)` (non-invertibility of
   `a - λ` in `C(a)`) = character values; `C(a) ≅ C(sp a, ℝ)` with `a ↦ id`;
   exact positive square roots, unique; `a ≥ 0 ⟺ a = b²`; `f(a)` for continuous `f`.
5. Not attempted: positivity of `U_a` (needs Macdonald / Shirshov–Cohn for two
   generators, a different order of magnitude); only `b ∈ C(a)` (`jQ_nonneg_of_mem_Ca`).

Line budget: 1: 250, 2: 250, 3: 700, 4: 400.  Status: 1–4 done, no sorry, axiom-clean
(`hos324`, `jb_norm_mul_self`, `jbSqrt_unique`, `nonneg_iff_exists_mul_self`).
-/
import Papers.SEA.JBWSEA
import Theses.B.Eff.JordanAlgebras
import Mathlib.Analysis.Convex.KreinMilman
import Mathlib.Topology.ContinuousMap.StoneWeierstrass
import Mathlib.Analysis.Normed.Module.HahnBanach

set_option linter.unusedSectionVars false
set_option warn.classDefReducibility false

namespace Papers.REC.JBCalc

open Theses.B.Eff Papers.REC Filter Topology Polynomial

universe u

noncomputable section

/-! ## 1. Power-associativity -/

section PowerAssoc

variable {A : Type u} [AddCommGroup A] [Module ℝ A] [PartialOrder A] [OrderUnitSpace A] [Mul A]
  [hJ : JBAlgebra A]

include hJ

/-- The commutative non-unital non-associative ring structure of a JB-algebra, used
only to borrow Mathlib's linearisation of the Jordan identity. -/
def jbRing (A : Type u) [AddCommGroup A] [Module ℝ A] [PartialOrder A] [OrderUnitSpace A]
    [Mul A] [JBAlgebra A] : NonUnitalNonAssocCommRing A :=
  { (inferInstance : AddCommGroup A), (inferInstance : Mul A) with
    left_distrib := jb_mul_add
    right_distrib := JBAlgebra.add_mul
    zero_mul := jb_zero_mul
    mul_zero := jb_mul_zero
    mul_comm := JBAlgebra.mul_comm }

omit hJ in
theorem jb_eq_zero_of_nsmul {n : ℕ} (hn : n ≠ 0) {y : A} (h : n • y = 0) : y = 0 := by
  have h2 : ((n : ℕ) : ℝ) • y = 0 := by rwa [Nat.cast_smul_eq_nsmul]
  rcases smul_eq_zero.mp h2 with h3 | h3
  · exact absurd (Nat.cast_eq_zero.mp h3) hn
  · exact h3

/-- **The linearised Jordan identity** (full polarisation of `[L_a, L_{a²}] = 0`), on `w`. -/
theorem jb_lin (a b c w : A) :
    a * (b * c * w) - b * c * (a * w) + (b * (c * a * w) - c * a * (b * w))
      + (c * (a * b * w) - a * b * (c * w)) = 0 := by
  have hcj : ∀ x y : A, x * y * (x * x) = x * (y * (x * x)) := JBAlgebra.jordan
  refine jb_eq_zero_of_nsmul (n := 2) two_ne_zero ?_
  let _inst := jbRing A
  have _inst2 : IsCommJordan A := ⟨hcj⟩
  exact Theses.B.Eff.EuclideanJordanAlgebra.two_nsmul_lin_aux a b c w

/-- The Jordan powers: `a⁰ = 1`, `aⁿ⁺¹ = a * aⁿ`. -/
def jbPow (a : A) : ℕ → A
  | 0 => ouUnit A
  | (n + 1) => a * jbPow a n

omit hJ in
@[simp] theorem jbPow_zero (a : A) : jbPow a 0 = ouUnit A := rfl

omit hJ in
theorem jbPow_succ (a : A) (n : ℕ) : jbPow a (n + 1) = a * jbPow a n := rfl

@[simp] theorem jbPow_one (a : A) : jbPow a 1 = a := by
  rw [jbPow_succ, jbPow_zero, JBAlgebra.mul_one]

/-- The commutator of `L_{a^k}` and `L_{a^{M-k}}` at `w`. -/
def jbCm (a : A) (M k : ℕ) (w : A) : A :=
  jbPow a k * (jbPow a (M - k) * w) - jbPow a (M - k) * (jbPow a k * w)

omit hJ in
theorem jbCm_neg (a : A) {M k : ℕ} (h : k ≤ M) (w : A) :
    jbCm a M (M - k) w = - jbCm a M k w := by
  have e : M - (M - k) = k := by omega
  simp only [jbCm, e]
  abel

theorem jbCm_sum (a : A) {M : ℕ}
    (hA : ∀ i j : ℕ, i + j ≤ M - 1 → jbPow a i * jbPow a j = jbPow a (i + j))
    (w : A) {p q r : ℕ} (hp : 1 ≤ p) (hq : 1 ≤ q) (hr : 1 ≤ r) (hs : p + q + r = M) :
    jbCm a M p w + jbCm a M q w + jbCm a M r w = 0 := by
  have h := jb_lin (jbPow a p) (jbPow a q) (jbPow a r) w
  rw [hA q r (by omega), hA r p (by omega), hA p q (by omega)] at h
  have e1 : q + r = M - p := by omega
  have e2 : r + p = M - q := by omega
  have e3 : p + q = M - r := by omega
  rw [e1, e2, e3] at h
  simp only [jbCm]
  linear_combination (norm := module) h

theorem jbCm_eq_zero (a : A) {M : ℕ} (hM : 3 ≤ M)
    (hA : ∀ i j : ℕ, i + j ≤ M - 1 → jbPow a i * jbPow a j = jbPow a (i + j))
    (w : A) {k : ℕ} (hk1 : 1 ≤ k) (hk2 : k ≤ M - 1) :
    jbCm a M k w = 0 := by
  have hstep : ∀ j : ℕ, 1 ≤ j → j ≤ M - 2 →
      jbCm a M (j + 1) w = jbCm a M 1 w + jbCm a M j w := by
    intro j hj1 hj2
    have hsum := jbCm_sum a hA w (p := 1) (q := j) (r := M - 1 - j)
      le_rfl hj1 (by omega) (by omega)
    have e : M - 1 - j = M - (j + 1) := by omega
    rw [e, jbCm_neg a (k := j + 1) (by omega) w] at hsum
    linear_combination (norm := module) -hsum
  have hmul : ∀ j : ℕ, j ≤ M - 1 → 1 ≤ j → jbCm a M j w = j • jbCm a M 1 w := by
    intro j
    induction j with
    | zero => intro _ h; exact absurd h (by omega)
    | succ n ih =>
      intro hn hn1
      rcases Nat.eq_zero_or_pos n with rfl | hn0
      · simp
      · rw [hstep n hn0 (by omega), ih (by omega) hn0, succ_nsmul]
        abel
  have hM1 : jbCm a M (M - 1) w = - jbCm a M 1 w := by
    have := jbCm_neg a (M := M) (k := 1) (by omega) w
    simpa using this
  have hlast : M • jbCm a M 1 w = 0 := by
    have h1 : jbCm a M (M - 1) w = (M - 1) • jbCm a M 1 w :=
      hmul (M - 1) le_rfl (by omega)
    have e : M - 1 + 1 = M := by omega
    have h3 : (M - 1) • jbCm a M 1 w + jbCm a M 1 w = 0 := by
      rw [← h1, hM1]; abel
    rw [← e, succ_nsmul]
    exact h3
  have hc1 : jbCm a M 1 w = 0 := jb_eq_zero_of_nsmul (by omega) hlast
  rw [hmul k hk2 hk1, hc1, smul_zero]

theorem jb_pow_aux (a : A) : ∀ N : ℕ,
    (∀ i j : ℕ, i + j ≤ N → jbPow a i * jbPow a j = jbPow a (i + j)) ∧
    (∀ i j : ℕ, i + j ≤ N → ∀ w : A,
      jbPow a i * (jbPow a j * w) = jbPow a j * (jbPow a i * w)) := by
  intro N
  induction N with
  | zero =>
    refine ⟨?_, ?_⟩
    · intro i j hij
      have hi : i = 0 := by omega
      have hj : j = 0 := by omega
      subst hi; subst hj
      simp [JBAlgebra.one_mul]
    · intro i j hij w
      have hi : i = 0 := by omega
      have hj : j = 0 := by omega
      subst hi; subst hj
      rfl
  | succ N ih =>
    obtain ⟨hA, hB⟩ := ih
    have hB' : ∀ i j : ℕ, i + j ≤ N + 1 → ∀ w : A,
        jbPow a i * (jbPow a j * w) = jbPow a j * (jbPow a i * w) := by
      intro i j hij w
      rcases Nat.lt_or_ge (i + j) (N + 1) with h | h
      · exact hB i j (by omega) w
      rcases Nat.eq_zero_or_pos i with rfl | hi
      · simp [JBAlgebra.one_mul]
      rcases Nat.eq_zero_or_pos j with rfl | hj
      · simp [JBAlgebra.one_mul]
      rcases Nat.lt_or_ge (N + 1) 3 with h3 | h3
      · have hi1 : i = 1 := by omega
        have hj1 : j = 1 := by omega
        subst hi1; subst hj1
        rfl
      · have hcm : jbCm a (N + 1) i w = 0 := by
          refine jbCm_eq_zero a h3 (fun a' b hab => hA a' b (by omega)) w hi (by omega)
        have e : N + 1 - i = j := by omega
        simp only [jbCm, e] at hcm
        exact sub_eq_zero.mp hcm
    refine ⟨?_, hB'⟩
    intro i j hij
    rcases Nat.lt_or_ge (i + j) (N + 1) with h | h
    · exact hA i j (by omega)
    rcases Nat.eq_zero_or_pos j with rfl | hj
    · simp [JBAlgebra.mul_one]
    rcases Nat.eq_or_lt_of_le hj with h1 | h1
    · have hj1 : j = 1 := h1.symm
      subst hj1
      rw [jbPow_one, JBAlgebra.mul_comm, ← jbPow_succ]
    · have e : j - 1 + 1 = j := by omega
      have h1' : jbPow a i * jbPow a j = jbPow a i * (jbPow a 1 * jbPow a (j - 1)) := by
        rw [jbPow_one, ← jbPow_succ, e]
      have h2 := hB i 1 (by omega) (jbPow a (j - 1))
      have h3 := hA i (j - 1) (by omega)
      rw [h1', h2, h3, jbPow_one, ← jbPow_succ]
      congr 1
      omega

/-- **Power-associativity of a JB-algebra**: `aᵐ * aⁿ = aᵐ⁺ⁿ`. -/
theorem jbPow_mul_jbPow (a : A) (m n : ℕ) : jbPow a m * jbPow a n = jbPow a (m + n) :=
  (jb_pow_aux a (m + n)).1 m n le_rfl

/-! ### Evaluation of real polynomials -/

/-- Evaluation of a real polynomial at `a`, as a plain function. -/
def jbEvF (a : A) (q : ℝ[X]) : A := q.sum fun n c => c • jbPow a n

omit hJ in
theorem jbEvF_monomial (a : A) (n : ℕ) (c : ℝ) :
    jbEvF a (Polynomial.monomial n c) = c • jbPow a n :=
  Polynomial.sum_monomial_index c _ (zero_smul ℝ _)

omit hJ in
theorem jbEvF_add (a : A) (p q : ℝ[X]) : jbEvF a (p + q) = jbEvF a p + jbEvF a q :=
  Polynomial.sum_add_index p q _ (fun _ => zero_smul ℝ _) (fun _ c d => add_smul c d _)

omit hJ in
theorem jbEvF_smul (a : A) (r : ℝ) (q : ℝ[X]) : jbEvF a (r • q) = r • jbEvF a q := by
  induction q using Polynomial.induction_on' with
  | add p q hp hq => rw [smul_add, jbEvF_add, jbEvF_add, hp, hq, smul_add]
  | monomial n c =>
    rw [Polynomial.smul_monomial, jbEvF_monomial, jbEvF_monomial, _root_.smul_smul, smul_eq_mul]

/-- **Evaluation at `a`**, `ℝ[X] →ₗ[ℝ] A`; multiplicative by power-associativity. -/
def jbEv (a : A) : ℝ[X] →ₗ[ℝ] A where
  toFun := jbEvF a
  map_add' := jbEvF_add a
  map_smul' r q := jbEvF_smul a r q

omit hJ in
@[simp] theorem jbEv_monomial (a : A) (n : ℕ) (c : ℝ) :
    jbEv a (Polynomial.monomial n c) = c • jbPow a n := jbEvF_monomial a n c

/-- **Evaluation is multiplicative** (power-associativity). -/
theorem jbEv_mul (a : A) (p q : ℝ[X]) : jbEv a (p * q) = jbEv a p * jbEv a q := by
  induction p using Polynomial.induction_on' with
  | add p₁ p₂ h₁ h₂ => rw [add_mul, map_add, map_add, h₁, h₂, JBAlgebra.add_mul]
  | monomial n c =>
    induction q using Polynomial.induction_on' with
    | add q₁ q₂ h₁ h₂ => rw [mul_add, map_add, map_add, h₁, h₂, jb_mul_add]
    | monomial m d =>
      rw [Polynomial.monomial_mul_monomial, jbEv_monomial, jbEv_monomial,
        jbEv_monomial, JBAlgebra.smul_mul, jb_mul_smul, _root_.smul_smul, jbPow_mul_jbPow]

omit hJ in
theorem jbEv_one (a : A) : jbEv a 1 = ouUnit A := by
  have h : (Polynomial.monomial 0 (1 : ℝ)) = 1 := by
    rw [Polynomial.monomial_zero_left, map_one]
  rw [← h, jbEv_monomial, jbPow_zero, one_smul]

theorem jbEv_X (a : A) : jbEv a Polynomial.X = a := by
  rw [← Polynomial.monomial_one_one_eq_X, jbEv_monomial, jbPow_one, one_smul]

omit hJ in
theorem jbEv_C (a : A) (r : ℝ) : jbEv a (Polynomial.C r) = r • ouUnit A := by
  rw [← Polynomial.monomial_zero_left, jbEv_monomial, jbPow_zero]

/-- The polynomials in `a` form an associative algebra. -/
theorem jbEv_assoc (a : A) (p q r : ℝ[X]) :
    jbEv a p * jbEv a q * jbEv a r = jbEv a p * (jbEv a q * jbEv a r) := by
  rw [← jbEv_mul, ← jbEv_mul, ← jbEv_mul, ← jbEv_mul, mul_assoc]

end PowerAssoc

/-! ## 2. Closed unital subalgebras are JB-algebras; `C(a)` -/

section Sub

variable {A : Type u} [AddCommGroup A] [Module ℝ A] [PartialOrder A] [OrderUnitSpace A] [Mul A]

variable (A) in
/-- A **closed unital subalgebra** of a JB-algebra: a subspace containing `1`, closed
under the Jordan product and closed in the order-unit norm. -/
structure ClosedJBSub where
  carrier : Submodule ℝ A
  one_mem : ouUnit A ∈ carrier
  mul_mem : ∀ {x y : A}, x ∈ carrier → y ∈ carrier → x * y ∈ carrier
  closed : ∀ x : A, (∀ ε : ℝ, 0 < ε → ∃ y ∈ carrier, ousNorm A (x - y) < ε) → x ∈ carrier

namespace ClosedJBSub

variable (T : ClosedJBSub A)

instance : OrderUnitSpace T.carrier where
  add_le_add_left x y h z := by
    show (x : A) + z ≤ y + z
    exact add_le_add h le_rfl
  smul_nonneg hr hx := by
    show (0 : A) ≤ _
    exact ou_smul_nonneg hr hx
  unit := ⟨ouUnit A, T.one_mem⟩
  exists_le_smul_unit x := ou_exists_le_smul_unit (x : A)

instance : Mul T.carrier := ⟨fun x y => ⟨(x : A) * y, T.mul_mem x.2 y.2⟩⟩

@[simp] theorem coe_mul (x y : T.carrier) : ((x * y : T.carrier) : A) = (x : A) * y := rfl

@[simp] theorem coe_unit : ((ouUnit T.carrier : T.carrier) : A) = ouUnit A := rfl

theorem coe_le {x y : T.carrier} : x ≤ y ↔ (x : A) ≤ y := Iff.rfl

/-- The order-unit norm of the subalgebra is that of `A`. -/
theorem ousNorm_coe (x : T.carrier) : ousNorm T.carrier x = ousNorm A x := by
  unfold ousNorm
  congr 1

variable [hJ : JBAlgebra A]

instance isOUS : IsOUS T.carrier where
  norm_eq_zero x h := by
    rw [ousNorm_coe] at h
    exact Subtype.ext (IsOUS.norm_eq_zero _ h)
  cone_closed x h := by
    show (0 : A) ≤ x
    refine IsOUS.cone_closed (x : A) fun ε hε => ?_
    obtain ⟨w, hw, hwx⟩ := h ε hε
    exact ⟨w, hw, by rwa [ousNorm_coe] at hwx⟩

/-- **A closed unital subalgebra of a JB-algebra is a JB-algebra** (same order, unit,
norm and product). -/
instance jb : JBAlgebra T.carrier where
  banach s hs := by
    obtain ⟨v, hv⟩ := hJ.banach (fun n => (s n : A)) fun ε hε => by
      obtain ⟨N, hN⟩ := hs ε hε
      exact ⟨N, fun m hm n hn => by have := hN m hm n hn; rwa [ousNorm_coe] at this⟩
    have hvT : v ∈ T.carrier := T.closed v fun ε hε => by
      obtain ⟨N, hN⟩ := hv ε hε
      exact ⟨s N, (s N).2, by rw [ousNorm_sub_comm]; exact hN N le_rfl⟩
    exact ⟨⟨v, hvT⟩, fun ε hε => by
      obtain ⟨N, hN⟩ := hv ε hε
      exact ⟨N, fun n hn => by rw [ousNorm_coe]; exact hN n hn⟩⟩
  mul_comm x y := Subtype.ext (JBAlgebra.mul_comm (x : A) y)
  mul_one x := Subtype.ext (JBAlgebra.mul_one (x : A))
  one_mul x := Subtype.ext (JBAlgebra.one_mul (x : A))
  jordan x y := Subtype.ext (JBAlgebra.jordan (x : A) y)
  sq_mem x h1 h2 := JBAlgebra.sq_mem (x : A) h1 h2
  add_mul x y z := Subtype.ext (JBAlgebra.add_mul (x : A) y z)
  smul_mul r x y := Subtype.ext (JBAlgebra.smul_mul r (x : A) y)

/-- Powers and polynomials of an element of `T` stay in `T`. -/
theorem jbPow_mem {a : A} (ha : a ∈ T.carrier) (n : ℕ) : jbPow a n ∈ T.carrier := by
  induction n with
  | zero => exact T.one_mem
  | succ n ih => exact T.mul_mem ha ih

theorem jbEv_mem {a : A} (ha : a ∈ T.carrier) (p : ℝ[X]) : jbEv a p ∈ T.carrier := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => rw [map_add]; exact T.carrier.add_mem hp hq
  | monomial n c => rw [jbEv_monomial]; exact T.carrier.smul_mem c (T.jbPow_mem ha n)

end ClosedJBSub

variable [hJ : JBAlgebra A]

include hJ

attribute [local instance] ousNormedAddCommGroup ousNormedSpace

/-- The Jordan product is jointly continuous (`‖ab‖ ≤ ‖a‖‖b‖`). -/
theorem jb_continuous_mul : Continuous fun p : A × A => p.1 * p.2 := by
  let B : A →ₗ[ℝ] A →ₗ[ℝ] A :=
    LinearMap.mk₂ ℝ (· * ·) JBAlgebra.add_mul JBAlgebra.smul_mul jb_mul_add jb_mul_smul
  let C := B.mkContinuous₂ 1 fun x y => by
    rw [one_mul]; exact jb_norm_mul_le x y
  exact C.continuous₂

/-- The norm closure of a unital subspace closed under the product. -/
def closureSub (P : Submodule ℝ A) (h1 : ouUnit A ∈ P)
    (hmul : ∀ {x y : A}, x ∈ P → y ∈ P → x * y ∈ P) : ClosedJBSub A where
  carrier := P.topologicalClosure
  one_mem := P.le_topologicalClosure h1
  mul_mem {x y} hx hy := by
    have := map_mem_closure₂ (f := fun a b : A => a * b) (u := (P : Set A))
      jb_continuous_mul hx hy fun a ha b hb => hmul ha hb
    exact this
  closed x hx := by
    show x ∈ closure (P : Set A)
    rw [← closure_closure]
    refine Metric.mem_closure_iff.2 fun ε hε => ?_
    obtain ⟨y, hy, hxy⟩ := hx ε hε
    exact ⟨y, hy, by rw [dist_eq_norm]; exact hxy⟩

theorem mem_closureSub {P : Submodule ℝ A} {h1 : ouUnit A ∈ P}
    {hmul : ∀ {x y : A}, x ∈ P → y ∈ P → x * y ∈ P} {x : A} :
    x ∈ (closureSub P h1 hmul).carrier ↔ x ∈ closure (P : Set A) := Iff.rfl

/-- Associativity passes to the closure. -/
theorem closureSub_assoc (P : Submodule ℝ A) (h1 : ouUnit A ∈ P)
    (hmul : ∀ {x y : A}, x ∈ P → y ∈ P → x * y ∈ P)
    (hass : ∀ x ∈ P, ∀ y ∈ P, ∀ z ∈ P, x * y * z = x * (y * z)) :
    ∀ x ∈ (closureSub P h1 hmul).carrier, ∀ y ∈ (closureSub P h1 hmul).carrier,
      ∀ z ∈ (closureSub P h1 hmul).carrier, x * y * z = x * (y * z) := by
  intro x hx y hy z hz
  have hc : Continuous fun p : A × A × A => p.1 * p.2.1 * p.2.2 - p.1 * (p.2.1 * p.2.2) := by
    have m := jb_continuous_mul (A := A)
    refine Continuous.sub ?_ ?_
    · exact m.comp ((m.comp (continuous_fst.prodMk (continuous_fst.comp continuous_snd))).prodMk
        (continuous_snd.comp continuous_snd))
    · exact m.comp (continuous_fst.prodMk (m.comp continuous_snd))
  have hsub : (P : Set A) ×ˢ ((P : Set A) ×ˢ (P : Set A)) ⊆
      {p : A × A × A | p.1 * p.2.1 * p.2.2 - p.1 * (p.2.1 * p.2.2) = 0} := by
    rintro ⟨a, b, c⟩ ⟨ha, hb, hc⟩
    show _ = _
    rw [sub_eq_zero]
    exact hass a ha b hb c hc
  have hcl := (isClosed_eq hc continuous_const).closure_subset_iff.2 hsub
  rw [closure_prod_eq, closure_prod_eq] at hcl
  have := hcl (Set.mk_mem_prod (mem_closureSub.1 hx)
    (Set.mk_mem_prod (mem_closureSub.1 hy) (mem_closureSub.1 hz)))
  exact sub_eq_zero.1 this

theorem jbEv_range_mul (a : A) {x y : A} (hx : x ∈ LinearMap.range (jbEv a))
    (hy : y ∈ LinearMap.range (jbEv a)) : x * y ∈ LinearMap.range (jbEv a) := by
  obtain ⟨p, rfl⟩ := hx; obtain ⟨q, rfl⟩ := hy; exact ⟨p * q, jbEv_mul a p q⟩

/-- **`C(a)`**: the closed unital subalgebra generated by `a`, the norm closure of the
polynomials in `a`. -/
def Ca (a : A) : ClosedJBSub A :=
  closureSub (LinearMap.range (jbEv a)) ⟨1, jbEv_one a⟩ (jbEv_range_mul a)

theorem mem_Ca {a x : A} : x ∈ (Ca a).carrier ↔ x ∈ closure (Set.range (jbEv a)) := Iff.rfl

theorem jbEv_mem_Ca (a : A) (p : ℝ[X]) : jbEv a p ∈ (Ca a).carrier :=
  subset_closure ⟨p, rfl⟩

theorem self_mem_Ca (a : A) : a ∈ (Ca a).carrier := by
  have := jbEv_mem_Ca a X; rwa [jbEv_X] at this

/-- **H-O–S 3.2.4, associativity**: `C(a)` is associative. -/
theorem Ca_assoc (a : A) : ∀ x ∈ (Ca a).carrier, ∀ y ∈ (Ca a).carrier,
    ∀ z ∈ (Ca a).carrier, x * y * z = x * (y * z) :=
  closureSub_assoc (LinearMap.range (jbEv a)) ⟨1, jbEv_one a⟩ (jbEv_range_mul a) (by
    rintro _ ⟨p, rfl⟩ _ ⟨q, rfl⟩ _ ⟨r, rfl⟩; exact jbEv_assoc a p q r)

/-- `C(a)` is the *smallest* closed unital subalgebra containing `a`. -/
theorem Ca_le {a : A} (T : ClosedJBSub A) (ha : a ∈ T.carrier) :
    (Ca a).carrier ≤ T.carrier := by
  intro x hx
  refine T.closed x fun ε hε => ?_
  obtain ⟨y, ⟨p, rfl⟩, hy⟩ := Metric.mem_closure_iff.1 (mem_Ca.1 hx) ε hε
  exact ⟨jbEv a p, T.jbEv_mem ha p, by rw [dist_eq_norm] at hy; exact hy⟩

end Sub

/-! ## 3. Gelfand theory for associative JB-algebras -/

section States

variable (B : Type u) [AddCommGroup B] [Module ℝ B] [PartialOrder B] [OrderUnitSpace B] [Mul B]

/-- The **states** of `B` (positive unital linear functionals), as a subset of `B → ℝ`
with the product (weak*) topology. -/
def stateSet : Set (B → ℝ) :=
  {f | (∀ x y, f (x + y) = f x + f y) ∧ (∀ (r : ℝ) x, f (r • x) = r * f x) ∧
    (∀ x, 0 ≤ x → 0 ≤ f x) ∧ f (ouUnit B) = 1}

/-- The **characters** of `B`: multiplicative states. -/
def charSet : Set (B → ℝ) := {f | f ∈ stateSet B ∧ ∀ x y, f (x * y) = f x * f y}

variable {B}

/-- A state as a linear functional. -/
def stL {f : B → ℝ} (hf : f ∈ stateSet B) : B →ₗ[ℝ] ℝ where
  toFun := f
  map_add' := hf.1
  map_smul' := hf.2.1

@[simp] theorem stL_apply {f : B → ℝ} (hf : f ∈ stateSet B) (x : B) : stL hf x = f x := rfl

theorem state_abs_le {f : B → ℝ} (hf : f ∈ stateSet B) (x : B) : |f x| ≤ ousNorm B x :=
  abs_state_le (stL hf) hf.2.2.1 hf.2.2.2 x

theorem convex_stateSet : Convex ℝ (stateSet B) := by
  intro f hf g hg a b ha hb hab
  refine ⟨fun x y => ?_, fun r x => ?_, fun x hx => ?_, ?_⟩ <;>
    simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]
  · rw [hf.1, hg.1]; ring
  · rw [hf.2.1, hg.2.1]; ring
  · exact add_nonneg (mul_nonneg ha (hf.2.2.1 x hx)) (mul_nonneg hb (hg.2.2.1 x hx))
  · rw [hf.2.2.2, hg.2.2.2]; linarith

theorem isClosed_stateSet : IsClosed (stateSet B) := by
  have e : stateSet B = (⋂ x, ⋂ y, {f : B → ℝ | f (x + y) = f x + f y}) ∩
      ((⋂ (r : ℝ), ⋂ x, {f : B → ℝ | f (r • x) = r * f x}) ∩
      ((⋂ x, ⋂ (_ : 0 ≤ x), {f : B → ℝ | 0 ≤ f x}) ∩ {f | f (ouUnit B) = 1})) := by
    ext f; simp only [stateSet, Set.mem_inter_iff, Set.mem_iInter, Set.mem_ofPred_eq]
  rw [e]
  refine IsClosed.inter (isClosed_iInter fun x => isClosed_iInter fun y =>
    isClosed_eq (continuous_apply _) (by fun_prop))
    (IsClosed.inter (isClosed_iInter fun r => isClosed_iInter fun x =>
      isClosed_eq (continuous_apply _) (continuous_const.mul (continuous_apply _)))
    (IsClosed.inter (isClosed_iInter fun x => isClosed_iInter fun _ =>
      isClosed_le continuous_const (continuous_apply _))
      (isClosed_eq (continuous_apply _) continuous_const)))

theorem isClosed_charSet : IsClosed (charSet B) := by
  have e : charSet B = stateSet B ∩ ⋂ x, ⋂ y, {f : B → ℝ | f (x * y) = f x * f y} := by
    ext f; simp only [charSet, Set.mem_inter_iff, Set.mem_iInter, Set.mem_ofPred_eq]
  rw [e]
  exact isClosed_stateSet.inter (isClosed_iInter fun x => isClosed_iInter fun y =>
    isClosed_eq (continuous_apply _) (by fun_prop))

variable [IsOUS B]

/-- **Banach–Alaoglu** for the state space, via Tychonoff. -/
theorem isCompact_stateSet : IsCompact (stateSet B) := by
  have hK : IsCompact (Set.pi Set.univ fun x : B => Set.Icc (-ousNorm B x) (ousNorm B x)) :=
    isCompact_univ_pi fun _ => isCompact_Icc
  refine hK.of_isClosed_subset isClosed_stateSet ?_
  intro f hf x _
  exact abs_le.1 (state_abs_le hf x)

theorem isCompact_charSet : IsCompact (charSet B) :=
  isCompact_stateSet.of_isClosed_subset isClosed_charSet fun _ hf => hf.1

instance : CompactSpace (charSet B) := isCompact_iff_compactSpace.1 isCompact_charSet

/-- A positive functional vanishing at `1` vanishes. -/
theorem linfun_eq_zero (g : B →ₗ[ℝ] ℝ) (hpos : ∀ y, 0 ≤ y → 0 ≤ g y)
    (h1 : g (ouUnit B) = 0) (x : B) : g x = 0 := by
  obtain ⟨b1, b2⟩ := ousNorm_bounds_le x
  have p1 := hpos _ (sub_nonneg.2 b1)
  have p2 := hpos _ (sub_nonneg.2 b2)
  rw [map_sub, map_neg, map_smul, h1, smul_zero] at p1
  rw [map_sub, map_smul, h1, smul_zero] at p2
  linarith

/-- A positive functional with `g 1 = t > 0`, rescaled, is a state. -/
theorem state_of_pos (g : B →ₗ[ℝ] ℝ) (hpos : ∀ y, 0 ≤ y → 0 ≤ g y) {t : ℝ}
    (h1 : g (ouUnit B) = t) (ht : 0 < t) : (fun y => t⁻¹ * g y) ∈ stateSet B := by
  refine ⟨fun x y => ?_, fun r x => ?_, fun x hx => ?_, ?_⟩
  · simp only [map_add]; ring
  · simp only [map_smul, smul_eq_mul]; ring
  · exact mul_nonneg (inv_nonneg.2 ht.le) (hpos x hx)
  · simp only [h1]; exact inv_mul_cancel₀ ht.ne'

theorem ousNorm_unit_le_one : ousNorm B (ouUnit B) ≤ 1 :=
  ousNorm_le_rc zero_le_one (by rw [one_smul]; exact neg_le_self ou_unit_nonneg)
    (by rw [one_smul])

attribute [local instance] ousNormedAddCommGroup ousNormedSpace

/-- A state attaining `‖b‖` at `b`, from a norming functional of `‖b‖1 + b`. -/
theorem exists_state_eq_aux {b : B} {m : ℝ} (hm : ousNorm B b = m) (hm0 : 0 < m)
    (h2 : ousNorm B (m • ouUnit B + b) = 2 * m) : ∃ f ∈ stateSet B, f b = m := by
  obtain ⟨g, hg1, hgx⟩ := exists_dual_vector ℝ (m • ouUnit B + b)
    (by rw [norm_eq_ousNorm, h2]; positivity)
  have hle : ∀ y, g y ≤ ousNorm B y := fun y => by
    have := g.le_opNorm y
    rw [hg1, one_mul, Real.norm_eq_abs] at this
    exact (le_abs_self _).trans this
  have hge : ∀ y, -ousNorm B y ≤ g y := fun y => by
    have := hle (-y); rw [map_neg, ousNorm_neg] at this; linarith
  rw [norm_eq_ousNorm, h2, map_add, map_smul, smul_eq_mul, RCLike.ofReal_real_eq_id, id] at hgx
  have hu := (hle (ouUnit B)).trans ousNorm_unit_le_one
  have hb := hle b
  rw [hm] at hb
  have hg1' : g (ouUnit B) = 1 := by
    have : m * 1 ≤ m * g (ouUnit B) := by linarith
    have := le_of_mul_le_mul_left this hm0
    linarith
  have hgb : g b = m := by rw [hg1'] at hgx; linarith
  refine ⟨g, ⟨fun x y => map_add g x y, fun r x => by rw [map_smul, smul_eq_mul],
    fun y hy => ?_, hg1'⟩, hgb⟩
  set n := ousNorm B y
  have hn : 0 ≤ n := ousNorm_nonneg_rc y
  have hz : ousNorm B (y - (n / 2) • ouUnit B) ≤ n / 2 := by
    refine ousNorm_le_rc (by positivity) ?_ ?_
    · rw [neg_le_sub_iff_le_add]; exact le_add_of_nonneg_left hy
    · rw [sub_le_iff_le_add, ← add_smul, add_halves]; exact (ousNorm_bounds_le y).2
  have := hge (y - (n / 2) • ouUnit B)
  rw [map_sub, map_smul, hg1', smul_eq_mul] at this
  show 0 ≤ g y
  linarith

/-- **A state attains the norm**: for `b ≠ 0` some state has `|f b| = ‖b‖`. -/
theorem exists_state_abs_eq_norm {b : B} (hb : b ≠ 0) :
    ∃ f ∈ stateSet B, |f b| = ousNorm B b := by
  set m := ousNorm B b with hmdef
  have hm0 : 0 < m :=
    lt_of_le_of_ne (ousNorm_nonneg_rc b) fun h => hb (IsOUS.norm_eq_zero b h.symm)
  have hle : ∀ c : B, ousNorm B c = m → ousNorm B (m • ouUnit B + c) ≤ 2 * m := by
    intro c hc
    refine (ousNorm_add_le _ _).trans ?_
    have := ousNorm_smul_le m (ouUnit B)
    rw [abs_of_pos hm0] at this
    have := ousNorm_unit_le_one (B := B)
    nlinarith
  by_cases hp : ousNorm B (m • ouUnit B + b) = 2 * m
  · obtain ⟨f, hf, hfb⟩ := exists_state_eq_aux rfl hm0 hp
    exact ⟨f, hf, by rw [hfb, abs_of_pos hm0]⟩
  by_cases hn : ousNorm B (m • ouUnit B + -b) = 2 * m
  · obtain ⟨f, hf, hfb⟩ := exists_state_eq_aux (b := -b) (by rw [ousNorm_neg]) hm0 hn
    refine ⟨f, hf, ?_⟩
    have e : f (-b) = -f b := by
      have := hf.2.1 (-1) b; rwa [neg_one_smul, neg_one_mul] at this
    rw [e] at hfb
    rw [show f b = -m by linarith, abs_neg, abs_of_pos hm0]
  exfalso
  have lp : ousNorm B (m • ouUnit B + b) < 2 * m := lt_of_le_of_ne (hle b rfl) hp
  have ln : ousNorm B (m • ouUnit B + -b) < 2 * m :=
    lt_of_le_of_ne (hle (-b) (by rw [ousNorm_neg])) hn
  set k := max (ousNorm B (m • ouUnit B + b)) (ousNorm B (m • ouUnit B + -b)) - m
  have hk : k < m := by
    have := max_lt lp ln
    simp only [k]; linarith
  have b1 : b ≤ max k 0 • ouUnit B := by
    have h := (ousNorm_bounds_le (m • ouUnit B + b)).2
    have h' : ousNorm B (m • ouUnit B + b) • ouUnit B ≤ (max k 0 + m) • ouUnit B :=
      ou_smul_unit_mono (by simp only [k]; have := le_max_left k 0
                            have := le_max_left (ousNorm B (m • ouUnit B + b))
                              (ousNorm B (m • ouUnit B + -b))
                            linarith)
    have := h.trans h'
    rw [add_smul, add_comm (max k 0 • ouUnit B)] at this
    exact le_of_add_le_add_left this
  have b2 : -b ≤ max k 0 • ouUnit B := by
    have h := (ousNorm_bounds_le (m • ouUnit B + -b)).2
    have h' : ousNorm B (m • ouUnit B + -b) • ouUnit B ≤ (max k 0 + m) • ouUnit B :=
      ou_smul_unit_mono (by simp only [k]; have := le_max_left k 0
                            have := le_max_right (ousNorm B (m • ouUnit B + b))
                              (ousNorm B (m • ouUnit B + -b))
                            linarith)
    have := h.trans h'
    rw [add_smul, add_comm (max k 0 • ouUnit B)] at this
    exact le_of_add_le_add_left this
  have := ousNorm_le_rc (le_max_right k 0) (neg_le.1 b2) b1
  rw [← hmdef] at this
  have : max k 0 < m := max_lt hk hm0
  linarith

end States

section Gelfand

variable {B : Type u} [AddCommGroup B] [Module ℝ B] [PartialOrder B] [OrderUnitSpace B] [Mul B]
  [hJ : JBAlgebra B]

include hJ

/-- In an associative JB-algebra **the positive cone is closed under products**:
`(x + ε)(y + ε) = s² t² = (st)²` with approximate square roots `s, t`. -/
theorem assoc_mul_nonneg (hB : ∀ x y z : B, x * y * z = x * (y * z)) {x y : B}
    (hx : 0 ≤ x) (hy : 0 ≤ y) : 0 ≤ x * y := by
  refine Papers.SEA.JBW.nonneg_of_forall_add fun δ hδ => ?_
  have hnx := ousNorm_nonneg_rc x
  have hny := ousNorm_nonneg_rc y
  set M := ousNorm B x + ousNorm B y + 1 with hM
  have hM0 : 0 < M := by linarith
  set ε := min 1 (δ / M) with hε
  have hε0 : 0 < ε := lt_min one_pos (div_pos hδ hM0)
  have hε1 : ε ≤ 1 := min_le_left _ _
  have hεM : ε * M ≤ δ := by
    calc ε * M ≤ δ / M * M := mul_le_mul_of_nonneg_right (min_le_right _ _) hM0.le
      _ = δ := div_mul_cancel₀ δ hM0.ne'
  obtain ⟨s, -, hs⟩ := Papers.SEA.JBW.exists_sq_add hx hε0
  obtain ⟨t, -, ht⟩ := Papers.SEA.JBW.exists_sq_add hy hε0
  have hsq : (x + ε • ouUnit B) * (y + ε • ouUnit B) = (s * t) * (s * t) := by
    rw [← hs, ← ht, hB s t (s * t), ← hB t s t, JBAlgebra.mul_comm t s, hB s t t,
      ← hB s s (t * t)]
  have h0 : 0 ≤ (x + ε • ouUnit B) * (y + ε • ouUnit B) := hsq ▸ jb_sq_nonneg _
  have hexp : (x + ε • ouUnit B) * (y + ε • ouUnit B)
      = x * y + ε • x + ε • y + (ε * ε) • ouUnit B := by
    simp only [JBAlgebra.add_mul, jb_mul_add, JBAlgebra.smul_mul, jb_mul_smul,
      JBAlgebra.mul_one, JBAlgebra.one_mul]
    module
  have hx' : ε • x ≤ (ε * ousNorm B x) • ouUnit B := by
    rw [← _root_.smul_smul]; exact ou_smul_le_smul hε0.le (ousNorm_bounds_le x).2
  have hy' : ε • y ≤ (ε * ousNorm B y) • ouUnit B := by
    rw [← _root_.smul_smul]; exact ou_smul_le_smul hε0.le (ousNorm_bounds_le y).2
  have hc : ε * ε + ε * ousNorm B x + ε * ousNorm B y ≤ δ := by nlinarith
  calc (0 : B) ≤ (x + ε • ouUnit B) * (y + ε • ouUnit B) +
        ((δ - (ε * ε + ε * ousNorm B x + ε * ousNorm B y)) • ouUnit B +
          ((ε * ousNorm B x) • ouUnit B - ε • x) + ((ε * ousNorm B y) • ouUnit B - ε • y)) :=
        add_nonneg h0 (add_nonneg (add_nonneg (ou_smul_unit_nonneg (by linarith))
          (sub_nonneg.2 hx')) (sub_nonneg.2 hy'))
    _ = x * y + δ • ouUnit B := by rw [hexp]; module

/-- **Characters attain the norm** (Krein–Milman): if a state takes the value `s` at
`b`, with `|s| = ‖b‖`, then an extreme point `φ` of the face `{f ; f b = s}` of the
state space is a character.  For `0 ≤ c ≤ 1` the positive functionals `φ(c ·)` and
`φ((1-c) ·)` split `φ`, so extremality forces `φ(c x) = φ(c) φ(x)`. -/
theorem exists_char_eq (hB : ∀ x y z : B, x * y * z = x * (y * z)) {b : B} {s : ℝ}
    (hs : |s| = ousNorm B b) (hex : ∃ f ∈ stateSet B, f b = s) :
    ∃ φ ∈ charSet B, φ b = s := by
  set F := stateSet B ∩ {f | f b = s}
  have hFc : IsCompact F :=
    isCompact_stateSet.inter_right (isClosed_eq (continuous_apply b) continuous_const)
  obtain ⟨f0, hf0, hf0b⟩ := hex
  obtain ⟨φ, hφ⟩ := hFc.extremePoints_nonempty ⟨f0, hf0, hf0b⟩
  have hφF : φ ∈ F := hφ.1
  have hφS : φ ∈ stateSet B := hφF.1
  set ℓ := stL hφS
  have key : ∀ c : B, 0 ≤ c → c ≤ ouUnit B → ∀ x, φ (c * x) = φ c * φ x := by
    intro c hc0 hc1 x
    let g₁ : B →ₗ[ℝ] ℝ := ℓ.comp (jbT c)
    let g₂ : B →ₗ[ℝ] ℝ := ℓ.comp (jbT (ouUnit B - c))
    have hg₁ : ∀ y, g₁ y = φ (c * y) := fun y => rfl
    have hg₂ : ∀ y, g₂ y = φ ((ouUnit B - c) * y) := fun y => rfl
    have hsum : ∀ y, φ (c * y) + φ ((ouUnit B - c) * y) = φ y := by
      intro y; rw [← hφS.1, ← JBAlgebra.add_mul, add_sub_cancel, JBAlgebra.one_mul]
    have hpos₁ : ∀ y, 0 ≤ y → 0 ≤ g₁ y := fun y hy =>
      hφS.2.2.1 _ (assoc_mul_nonneg hB hc0 hy)
    have hpos₂ : ∀ y, 0 ≤ y → 0 ≤ g₂ y := fun y hy =>
      hφS.2.2.1 _ (assoc_mul_nonneg hB (sub_nonneg.2 hc1) hy)
    set t := φ c with htdef
    have ht1 : g₁ (ouUnit B) = t := by rw [hg₁, JBAlgebra.mul_one]
    have ht2 : g₂ (ouUnit B) = 1 - t := by
      have := hsum (ouUnit B)
      rw [JBAlgebra.mul_one, JBAlgebra.mul_one, hφS.2.2.2] at this
      rw [hg₂, JBAlgebra.mul_one]; linarith
    have ht0 : 0 ≤ t := ht1 ▸ hpos₁ _ ou_unit_nonneg
    have ht1' : t ≤ 1 := by have := hpos₂ _ ou_unit_nonneg; rw [ht2] at this; linarith
    rcases ht0.eq_or_lt with h0 | h0
    · have := linfun_eq_zero g₁ hpos₁ (by rw [ht1, ← h0]) x
      rw [hg₁] at this; rw [this, ← h0, zero_mul]
    rcases ht1'.eq_or_lt with h1 | h1
    · have := linfun_eq_zero g₂ hpos₂ (by rw [ht2, h1, sub_self]) x
      rw [hg₂] at this; have := hsum x; rw [h1, one_mul]; linarith
    have h1t : 0 < 1 - t := by linarith
    have hf₁ := state_of_pos g₁ hpos₁ ht1 h0
    have hf₂ := state_of_pos g₂ hpos₂ ht2 h1t
    set f₁ : B → ℝ := fun y => t⁻¹ * g₁ y
    set f₂ : B → ℝ := fun y => (1 - t)⁻¹ * g₂ y
    have hcomb : ∀ y, t * f₁ y + (1 - t) * f₂ y = φ y := by
      intro y
      simp only [f₁, f₂]
      rw [← mul_assoc, ← mul_assoc, mul_inv_cancel₀ h0.ne', mul_inv_cancel₀ h1t.ne', one_mul,
        one_mul, hg₁, hg₂, hsum]
    have hb₁ := state_abs_le hf₁ b
    have hb₂ := state_abs_le hf₂ b
    rw [← hs] at hb₁ hb₂
    have hcb := hcomb b
    rw [hφF.2] at hcb
    have hfb : f₁ b = s ∧ f₂ b = s := by
      rcases le_total 0 s with hs0 | hs0
      · rw [abs_of_nonneg hs0] at hb₁ hb₂
        have a1 := (abs_le.1 hb₁).2
        have a2 := (abs_le.1 hb₂).2
        constructor <;> nlinarith
      · rw [abs_of_nonpos hs0] at hb₁ hb₂
        have a1 := (abs_le.1 hb₁).1
        have a2 := (abs_le.1 hb₂).1
        constructor <;> nlinarith
    have hseg : φ ∈ openSegment ℝ f₁ f₂ :=
      ⟨t, 1 - t, h0, h1t, by ring, funext fun y => by
        simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]; exact hcomb y⟩
    have hext := (mem_extremePoints.1 hφ).2 f₁ ⟨hf₁, hfb.1⟩ f₂ ⟨hf₂, hfb.2⟩ hseg
    have e := congrFun hext.1 x
    simp only [f₁, hg₁] at e
    rw [inv_mul_eq_iff_eq_mul₀ h0.ne'] at e
    exact e
  refine ⟨φ, ⟨hφS, fun c x => ?_⟩, hφF.2⟩
  have hℓ : ∀ y, ℓ y = φ y := fun y => rfl
  rcases (ousNorm_nonneg_rc c).eq_or_lt with hm | hm
  · have hc : c = 0 := IsOUS.norm_eq_zero c hm.symm
    subst hc
    rw [jb_zero_mul, ← hℓ, ← hℓ, map_zero, zero_mul]
  obtain ⟨m, hmdef⟩ : ∃ m, m = ousNorm B c := ⟨_, rfl⟩
  rw [← hmdef] at hm
  obtain ⟨c', hc'⟩ : ∃ c', c' = (2 * m)⁻¹ • (c + m • ouUnit B) := ⟨_, rfl⟩
  have hcm0 : 0 ≤ c + m • ouUnit B := by
    rw [← sub_neg_eq_add, hmdef]; exact sub_nonneg.2 (ousNorm_bounds_le c).1
  have hc0 : 0 ≤ c' := hc' ▸ ou_smul_nonneg (by positivity) hcm0
  have hc1 : c' ≤ ouUnit B := by
    have h : c + m • ouUnit B ≤ (2 * m) • ouUnit B := by
      rw [two_mul, add_smul, hmdef]; exact add_le_add (ousNorm_bounds_le c).2 le_rfl
    have := ou_smul_le_smul (inv_nonneg.2 (by positivity : (0 : ℝ) ≤ 2 * m)) h
    rwa [_root_.smul_smul, inv_mul_cancel₀ (by positivity), one_smul, ← hc'] at this
  have hcc : c = (2 * m) • c' - m • ouUnit B := by
    rw [hc', _root_.smul_smul, mul_inv_cancel₀ (by positivity), one_smul, add_sub_cancel_right]
  have k := key c' hc0 hc1 x
  have hu : ℓ (ouUnit B) = 1 := hφS.2.2.2
  rw [hcc, jb_sub_mul, JBAlgebra.smul_mul, JBAlgebra.smul_mul, JBAlgebra.one_mul]
  have e1 : φ ((2 * m) • (c' * x) - m • x) = (2 * m) * φ (c' * x) - m * φ x := by
    rw [← hℓ, map_sub, map_smul, map_smul, hℓ, hℓ, smul_eq_mul, smul_eq_mul]
  have e2 : φ ((2 * m) • c' - m • ouUnit B) = (2 * m) * φ c' - m := by
    rw [← hℓ, map_sub, map_smul, map_smul, hℓ, hu, smul_eq_mul, smul_eq_mul, mul_one]
  rw [e1, e2, k]; ring

/-- The **Gelfand transform** `x ↦ (φ ↦ φ x)` on the character space. -/
def gelfand (x : B) : C(charSet B, ℝ) :=
  ⟨fun φ => φ.1 x, (continuous_apply x).comp continuous_subtype_val⟩

@[simp] theorem gelfand_apply (x : B) (φ : charSet B) : gelfand x φ = φ.1 x := rfl

/-- The Gelfand transform is linear. -/
def gelfandL : B →ₗ[ℝ] C(charSet B, ℝ) where
  toFun := gelfand
  map_add' x y := ContinuousMap.ext fun φ => φ.2.1.1 x y
  map_smul' r x := ContinuousMap.ext fun φ => φ.2.1.2.1 r x

@[simp] theorem gelfandL_apply (x : B) : gelfandL x = gelfand x := rfl

theorem gelfand_mul (x y : B) : gelfand (x * y) = gelfand x * gelfand y :=
  ContinuousMap.ext fun φ => φ.2.2 x y

theorem gelfand_one : gelfand (ouUnit B) = 1 :=
  ContinuousMap.ext fun φ => φ.2.1.2.2.2

attribute [local instance] ousNormedAddCommGroup ousNormedSpace

/-- **The Gelfand transform is isometric**: `‖Γ x‖_∞ = ‖x‖`. -/
theorem norm_gelfand (hB : ∀ x y z : B, x * y * z = x * (y * z)) (x : B) :
    ‖gelfand x‖ = ousNorm B x := by
  apply le_antisymm
  · exact (ContinuousMap.norm_le _ (ousNorm_nonneg_rc x)).2 fun φ => by
      rw [Real.norm_eq_abs]; exact state_abs_le φ.2.1 x
  · by_cases hx : x = 0
    · rw [hx, ousNorm_zero']; exact norm_nonneg _
    obtain ⟨f, hf, hfx⟩ := exists_state_abs_eq_norm hx
    obtain ⟨φ, hφ, hφx⟩ := exists_char_eq hB hfx ⟨f, hf, rfl⟩
    have := ContinuousMap.norm_coe_le_norm (gelfand x) ⟨φ, hφ⟩
    rw [gelfand_apply, Real.norm_eq_abs] at this
    change |φ x| ≤ _ at this
    rwa [hφx, hfx] at this

theorem isometry_gelfand (hB : ∀ x y z : B, x * y * z = x * (y * z)) :
    Isometry (gelfand (B := B)) :=
  Isometry.of_dist_eq fun x y => by
    rw [dist_eq_norm, dist_eq_norm, ← gelfandL_apply, ← gelfandL_apply, ← map_sub,
      gelfandL_apply, norm_gelfand hB, norm_eq_ousNorm]

/-- The range of the Gelfand transform, a subalgebra of `C(X, ℝ)`. -/
def gelfandSubalg : Subalgebra ℝ C(charSet B, ℝ) where
  carrier := Set.range gelfand
  mul_mem' := by rintro _ _ ⟨x, rfl⟩ ⟨y, rfl⟩; exact ⟨x * y, gelfand_mul x y⟩
  add_mem' := by rintro _ _ ⟨x, rfl⟩ ⟨y, rfl⟩; exact ⟨x + y, gelfandL.map_add x y⟩
  one_mem' := ⟨ouUnit B, gelfand_one⟩
  zero_mem' := ⟨0, gelfandL.map_zero⟩
  algebraMap_mem' r := ⟨r • ouUnit B, ContinuousMap.ext fun φ => by
    rw [gelfand_apply, φ.2.1.2.1, φ.2.1.2.2.2]; simp⟩

/-- **The Gelfand transform is onto** (Stone–Weierstrass; the range is closed since the
transform is isometric and `B` complete). -/
theorem gelfand_surjective (hB : ∀ x y z : B, x * y * z = x * (y * z)) :
    Function.Surjective (gelfand (B := B)) := by
  have hsep : (gelfandSubalg (B := B)).SeparatesPoints := by
    intro φ ψ hne
    have : φ.1 ≠ ψ.1 := fun h => hne (Subtype.ext h)
    obtain ⟨x, hx⟩ := Function.ne_iff.1 this
    exact ⟨_, ⟨gelfand x, ⟨x, rfl⟩, rfl⟩, hx⟩
  have hdense := ContinuousMap.subalgebra_topologicalClosure_eq_top_of_separatesPoints _ hsep
  have hclosed : IsClosed (Set.range (gelfand (B := B))) := by
    have := completeSpace_of_banach (W := B) hJ.banach
    exact (isometry_gelfand hB).isClosedEmbedding.isClosed_range
  intro g
  have hg : g ∈ (gelfandSubalg (B := B)).topologicalClosure := by
    rw [hdense]; exact Algebra.mem_top
  have : g ∈ closure (Set.range (gelfand (B := B))) := hg
  rwa [hclosed.closure_eq] at this

theorem gelfand_injective (hB : ∀ x y z : B, x * y * z = x * (y * z)) :
    Function.Injective (gelfand (B := B)) :=
  (isometry_gelfand hB).injective

/-- **Order**: `x ≥ 0` iff every character is `≥ 0` at `x`. -/
theorem nonneg_iff_gelfand (hB : ∀ x y z : B, x * y * z = x * (y * z)) (x : B) :
    0 ≤ x ↔ ∀ φ : charSet B, 0 ≤ φ.1 x := by
  refine ⟨fun h φ => φ.2.1.2.2.1 x h, fun h => ?_⟩
  obtain ⟨c, hc⟩ := gelfand_surjective hB
    ⟨fun φ => Real.sqrt (φ.1 x), Real.continuous_sqrt.comp (gelfand x).continuous⟩
  have : gelfand (c * c) = gelfand x := by
    rw [gelfand_mul, hc]; ext φ
    simp only [ContinuousMap.mul_apply, ContinuousMap.coe_mk, gelfand_apply]
    exact Real.mul_self_sqrt (h φ)
  rw [← gelfand_injective hB this]
  exact jb_sq_nonneg c

/-- **Positive square roots are unique** in an associative JB-algebra. -/
theorem assoc_sqrt_unique (hB : ∀ x y z : B, x * y * z = x * (y * z)) {u v : B}
    (hu : 0 ≤ u) (hv : 0 ≤ v) (h : u * u = v * v) : u = v := by
  apply gelfand_injective hB
  ext φ
  have h1 := (nonneg_iff_gelfand hB u).1 hu φ
  have h2 := (nonneg_iff_gelfand hB v).1 hv φ
  have e := congrArg (fun y => φ.1 y) h
  simp only [φ.2.2] at e
  exact (mul_self_inj h1 h2).1 e

/-- **Gelfand representation of an associative JB-algebra**: `Γ : B ≃ₗ C(X, ℝ)`,
`X` the (compact Hausdorff) character space; `Γ` is isometric, multiplicative, unital
and an order isomorphism. -/
def gelfandEquiv (hB : ∀ x y z : B, x * y * z = x * (y * z)) : B ≃ₗ[ℝ] C(charSet B, ℝ) :=
  LinearEquiv.ofBijective gelfandL ⟨gelfand_injective hB, gelfand_surjective hB⟩

theorem gelfandEquiv_apply (hB : ∀ x y z : B, x * y * z = x * (y * z)) (x : B) :
    gelfandEquiv hB x = gelfand x := rfl

end Gelfand

/-! ## 4. The functional calculus of a single element (H-O–S 3.2.4) -/

section Calculus

variable {A : Type u} [AddCommGroup A] [Module ℝ A] [PartialOrder A] [OrderUnitSpace A] [Mul A]
  [hJ : JBAlgebra A]

include hJ

attribute [local instance] ousNormedAddCommGroup ousNormedSpace

/-- `C(a)`, as a JB-algebra in its own right, is associative. -/
theorem CA_assoc (a : A) : ∀ x y z : (Ca a).carrier, x * y * z = x * (y * z) :=
  fun x y z => Subtype.ext (Ca_assoc a x x.2 y y.2 z z.2)

/-- `a` as an element of `C(a)`. -/
def aC (a : A) : (Ca a).carrier := ⟨a, self_mem_Ca a⟩

/-- **`‖b²‖ = ‖b‖²` in every JB-algebra** (H-O–S 3.1.4's C*-type identity, here a
theorem of the order-unit axioms of REC 44): a character of `C(b)` norming `b`. -/
theorem jb_norm_mul_self (b : A) : ousNorm A (b * b) = ousNorm A b ^ 2 := by
  apply le_antisymm
  · rw [sq]; exact jb_norm_mul_le b b
  · by_cases hb : b = 0
    · subst hb; rw [jb_zero_mul, ousNorm_zero']; simp
    have hb' : aC b ≠ 0 := fun h => hb (congrArg Subtype.val h)
    obtain ⟨f, hf, hfb⟩ := exists_state_abs_eq_norm hb'
    obtain ⟨φ, hφ, hφb⟩ := exists_char_eq (CA_assoc b) hfb ⟨f, hf, rfl⟩
    have h1 := state_abs_le hφ.1 (aC b * aC b)
    rw [hφ.2, hφb, abs_mul, hfb, ClosedJBSub.ousNorm_coe, ClosedJBSub.ousNorm_coe] at h1
    rw [sq]; exact h1

/-- A character is `φ(x - t1) = φ x - t`. -/
theorem char_sub_smul_one {T : ClosedJBSub A} {φ : T.carrier → ℝ} (hφ : φ ∈ charSet T.carrier)
    (x : T.carrier) (t : ℝ) : φ (x - t • ouUnit T.carrier) = φ x - t := by
  have := (stL hφ.1).map_sub x (t • ouUnit T.carrier)
  rw [(stL hφ.1).map_smul, stL_apply, stL_apply, stL_apply, hφ.1.2.2.2, smul_eq_mul,
    mul_one] at this
  exact this

/-- **The spectrum** of `a` (H-O–S 3.2.3): the `t ∈ ℝ` with `a - t1` not invertible
in `C(a)`. -/
def jbSpec (a : A) : Set ℝ :=
  {t | ¬ ∃ y ∈ (Ca a).carrier, (a - t • ouUnit A) * y = ouUnit A}

/-- **The spectrum is the set of character values** `φ(a)`, `φ` a character of `C(a)`. -/
theorem jbSpec_eq (a : A) :
    jbSpec a = (fun φ => φ (aC a)) '' charSet (Ca a).carrier := by
  ext t
  constructor
  · intro ht
    by_contra hne
    have hne' : ∀ φ : charSet (Ca a).carrier, φ.1 (aC a) - t ≠ 0 := fun φ h =>
      hne ⟨φ.1, φ.2, by linarith [sub_eq_zero.1 h]⟩
    let g : C(charSet (Ca a).carrier, ℝ) :=
      ⟨fun φ => (φ.1 (aC a) - t)⁻¹,
        ((gelfand (aC a)).continuous.sub continuous_const).inv₀ hne'⟩
    obtain ⟨y, hy⟩ := gelfand_surjective (CA_assoc a) g
    apply ht
    refine ⟨y, y.2, ?_⟩
    have e : gelfand ((aC a - t • ouUnit (Ca a).carrier) * y) =
        gelfand (ouUnit (Ca a).carrier) := by
      rw [gelfand_mul, hy, gelfand_one]
      ext φ
      simp only [ContinuousMap.mul_apply, gelfand_apply, ContinuousMap.one_apply, g]
      rw [char_sub_smul_one φ.2]
      exact mul_inv_cancel₀ (hne' φ)
    have := congrArg Subtype.val (gelfand_injective (CA_assoc a) e)
    exact this
  · rintro ⟨φ, hφ, rfl⟩ ⟨y, hy, hinv⟩
    have e : (aC a - φ (aC a) • ouUnit (Ca a).carrier) * ⟨y, hy⟩ = ouUnit (Ca a).carrier :=
      Subtype.ext hinv
    have h := congrArg φ e
    rw [hφ.2, char_sub_smul_one hφ, sub_self, zero_mul, hφ.1.2.2.2] at h
    exact zero_ne_one h

/-- The spectrum is compact. -/
theorem isCompact_jbSpec (a : A) : IsCompact (jbSpec a) := by
  rw [jbSpec_eq]
  exact isCompact_charSet.image (continuous_apply _)

instance (a : A) : CompactSpace (jbSpec a) := isCompact_iff_compactSpace.1 (isCompact_jbSpec a)

/-- The spectrum lies in `[-‖a‖, ‖a‖]`. -/
theorem jbSpec_subset (a : A) : jbSpec a ⊆ Set.Icc (-ousNorm A a) (ousNorm A a) := by
  rw [jbSpec_eq]
  rintro _ ⟨φ, hφ, rfl⟩
  have := state_abs_le hφ.1 (aC a)
  rw [ClosedJBSub.ousNorm_coe] at this
  exact abs_le.1 this

/-- The spectrum of a positive element is positive. -/
theorem jbSpec_nonneg {a : A} (ha : 0 ≤ a) {t : ℝ} (ht : t ∈ jbSpec a) : 0 ≤ t := by
  rw [jbSpec_eq] at ht
  obtain ⟨φ, hφ, rfl⟩ := ht
  exact hφ.1.2.2.1 _ ha

/-- A character of `C(a)` is determined by its value at `a`. -/
theorem char_ext {a : A} {φ ψ : (Ca a).carrier → ℝ} (hφ : φ ∈ charSet (Ca a).carrier)
    (hψ : ψ ∈ charSet (Ca a).carrier) (h : φ (aC a) = ψ (aC a)) : φ = ψ := by
  have hpow : ∀ n : ℕ, φ ⟨jbPow a n, (Ca a).jbPow_mem (self_mem_Ca a) n⟩ =
      ψ ⟨jbPow a n, (Ca a).jbPow_mem (self_mem_Ca a) n⟩ := by
    intro n
    induction n with
    | zero =>
      have e : (⟨jbPow a 0, (Ca a).jbPow_mem (self_mem_Ca a) 0⟩ : (Ca a).carrier) =
          ouUnit (Ca a).carrier := rfl
      rw [e, hφ.1.2.2.2, hψ.1.2.2.2]
    | succ n ih =>
      have e : (⟨jbPow a (n + 1), (Ca a).jbPow_mem (self_mem_Ca a) (n + 1)⟩ : (Ca a).carrier) =
          aC a * ⟨jbPow a n, (Ca a).jbPow_mem (self_mem_Ca a) n⟩ := rfl
      rw [e, hφ.2, hψ.2, h, ih]
  have hpoly : ∀ p : ℝ[X], φ ⟨jbEv a p, jbEv_mem_Ca a p⟩ = ψ ⟨jbEv a p, jbEv_mem_Ca a p⟩ := by
    intro p
    induction p using Polynomial.induction_on' with
    | add p q hp hq =>
      have e : (⟨jbEv a (p + q), jbEv_mem_Ca a (p + q)⟩ : (Ca a).carrier) =
          ⟨jbEv a p, jbEv_mem_Ca a p⟩ + ⟨jbEv a q, jbEv_mem_Ca a q⟩ :=
        Subtype.ext (map_add _ p q)
      rw [e, hφ.1.1, hψ.1.1, hp, hq]
    | monomial n c =>
      have e : (⟨jbEv a (Polynomial.monomial n c), jbEv_mem_Ca a _⟩ : (Ca a).carrier) =
          c • ⟨jbPow a n, (Ca a).jbPow_mem (self_mem_Ca a) n⟩ :=
        Subtype.ext (jbEv_monomial a n c)
      rw [e, hφ.1.2.1, hψ.1.2.1, hpow]
  funext x
  refine eq_of_forall_dist_le fun ε hε => ?_
  obtain ⟨_, ⟨p, rfl⟩, hp⟩ := Metric.mem_closure_iff.1 (mem_Ca.1 x.2) (ε / 2) (by positivity)
  rw [dist_eq_norm, norm_eq_ousNorm] at hp
  set y : (Ca a).carrier := ⟨jbEv a p, jbEv_mem_Ca a p⟩
  have hxy : ousNorm (Ca a).carrier (x - y) < ε / 2 := by
    rw [ClosedJBSub.ousNorm_coe]; exact hp
  have e1 := state_abs_le hφ.1 (x - y)
  have e2 := state_abs_le hψ.1 (x - y)
  have m1 := (stL hφ.1).map_sub x y
  have m2 := (stL hψ.1).map_sub x y
  simp only [stL_apply] at m1 m2
  rw [m1] at e1
  rw [m2] at e2
  rw [Real.dist_eq, show φ x - ψ x = (φ x - φ y) - (ψ x - ψ y) by rw [hpoly p]; ring]
  refine (abs_sub _ _).trans ?_
  linarith

/-- The map `φ ↦ φ(a)` from the character space of `C(a)` onto `sp(a)`. -/
def specMap (a : A) : charSet (Ca a).carrier → jbSpec a := fun φ =>
  ⟨φ.1 (aC a), by rw [jbSpec_eq]; exact ⟨φ.1, φ.2, rfl⟩⟩

theorem specMap_bijective (a : A) : Function.Bijective (specMap a) := by
  refine ⟨fun φ ψ h => Subtype.ext (char_ext φ.2 ψ.2 (congrArg Subtype.val h)), ?_⟩
  rintro ⟨t, ht⟩
  rw [jbSpec_eq] at ht
  obtain ⟨φ, hφ, rfl⟩ := ht
  exact ⟨⟨φ, hφ⟩, rfl⟩

/-- **The character space of `C(a)` is homeomorphic to `sp(a)`** (compact to Hausdorff). -/
def specHomeo (a : A) : charSet (Ca a).carrier ≃ₜ jbSpec a :=
  Continuous.homeoOfEquivCompactToT2 (f := Equiv.ofBijective _ (specMap_bijective a))
    (((continuous_apply _).comp continuous_subtype_val).subtype_mk _)

@[simp] theorem specHomeo_apply (a : A) (φ : charSet (Ca a).carrier) :
    (specHomeo a φ : ℝ) = φ.1 (aC a) := rfl

/-- Precomposition with a homeomorphism, as a linear equivalence. -/
def compHomeo {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y] (h : X ≃ₜ Y) :
    C(Y, ℝ) ≃ₗ[ℝ] C(X, ℝ) where
  toFun f := f.comp h
  invFun g := g.comp h.symm
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  left_inv _ := by ext y; simp
  right_inv _ := by ext x; simp

/-- **H-O–S 3.2.4**: the functional calculus `C(sp a, ℝ) ≃ C(a)`. -/
def jbCfcEquiv (a : A) : C(jbSpec a, ℝ) ≃ₗ[ℝ] (Ca a).carrier :=
  (compHomeo (specHomeo a)).trans (gelfandEquiv (CA_assoc a)).symm

theorem gelfand_jbCfcEquiv (a : A) (f : C(jbSpec a, ℝ)) :
    gelfand (jbCfcEquiv a f) = f.comp (specHomeo a) := by
  have := (gelfandEquiv (CA_assoc a)).apply_symm_apply (f.comp (specHomeo a))
  exact this

theorem jbCfcEquiv_eq_iff (a : A) (f : C(jbSpec a, ℝ)) (x : (Ca a).carrier) :
    jbCfcEquiv a f = x ↔ gelfand x = f.comp (specHomeo a) := by
  constructor
  · rintro rfl; exact gelfand_jbCfcEquiv a f
  · intro h; exact gelfand_injective (CA_assoc a) (by rw [gelfand_jbCfcEquiv, h])

/-- **The continuous functional calculus** `f ↦ f(a)`. -/
def jbCfc (a : A) (f : C(jbSpec a, ℝ)) : A := jbCfcEquiv a f

theorem jbCfc_mem (a : A) (f : C(jbSpec a, ℝ)) : jbCfc a f ∈ (Ca a).carrier :=
  (jbCfcEquiv a f).2

theorem jbCfc_add (a : A) (f g : C(jbSpec a, ℝ)) : jbCfc a (f + g) = jbCfc a f + jbCfc a g := by
  simp [jbCfc, map_add]

theorem jbCfc_smul (a : A) (r : ℝ) (f : C(jbSpec a, ℝ)) : jbCfc a (r • f) = r • jbCfc a f := by
  simp [jbCfc, map_smul]

/-- The calculus is multiplicative (for the Jordan product). -/
theorem jbCfc_mul (a : A) (f g : C(jbSpec a, ℝ)) : jbCfc a (f * g) = jbCfc a f * jbCfc a g := by
  have : jbCfcEquiv a (f * g) = jbCfcEquiv a f * jbCfcEquiv a g := by
    rw [jbCfcEquiv_eq_iff, gelfand_mul, gelfand_jbCfcEquiv, gelfand_jbCfcEquiv]; rfl
  exact congrArg Subtype.val this

theorem jbCfc_one (a : A) : jbCfc a 1 = ouUnit A := by
  have : jbCfcEquiv a 1 = ouUnit (Ca a).carrier := by
    rw [jbCfcEquiv_eq_iff, gelfand_one]; rfl
  exact congrArg Subtype.val this

/-- The identity function `sp(a) → ℝ`. -/
def specId (a : A) : C(jbSpec a, ℝ) := ⟨Subtype.val, continuous_subtype_val⟩

/-- `id(a) = a`. -/
theorem jbCfc_id (a : A) : jbCfc a (specId a) = a := by
  have : jbCfcEquiv a (specId a) = aC a := by
    rw [jbCfcEquiv_eq_iff]; rfl
  exact congrArg Subtype.val this

/-- **The calculus is isometric**: `‖f(a)‖ = ‖f‖_∞`. -/
theorem ousNorm_jbCfc (a : A) (f : C(jbSpec a, ℝ)) : ousNorm A (jbCfc a f) = ‖f‖ := by
  rw [jbCfc, ← ClosedJBSub.ousNorm_coe, ← norm_gelfand (CA_assoc a), gelfand_jbCfcEquiv]
  apply le_antisymm
  · exact (ContinuousMap.norm_le _ (norm_nonneg f)).2 fun φ => f.norm_coe_le_norm _
  · refine (ContinuousMap.norm_le _ (norm_nonneg _)).2 fun t => ?_
    obtain ⟨φ, rfl⟩ := (specHomeo a).surjective t
    exact ContinuousMap.norm_coe_le_norm (f.comp (specHomeo a : C(charSet (Ca a).carrier, jbSpec a))) φ

/-- **The calculus is an order isomorphism**: `f(a) ≥ 0` iff `f ≥ 0` on `sp(a)`. -/
theorem jbCfc_nonneg_iff (a : A) (f : C(jbSpec a, ℝ)) : 0 ≤ jbCfc a f ↔ ∀ t, 0 ≤ f t := by
  have h := nonneg_iff_gelfand (CA_assoc a) (jbCfcEquiv a f)
  rw [ClosedJBSub.coe_le] at h
  change 0 ≤ jbCfc a f ↔ _ at h
  rw [h]
  constructor
  · intro H t
    obtain ⟨φ, rfl⟩ := (specHomeo a).surjective t
    have := H φ
    rwa [← gelfand_apply, gelfand_jbCfcEquiv] at this
  · intro H φ
    rw [← gelfand_apply, gelfand_jbCfcEquiv]
    exact H _

/-- **Every element of `C(a)` is `f(a)`** for a unique continuous `f` on `sp(a)`. -/
theorem jbCfc_surjective (a : A) {x : A} (hx : x ∈ (Ca a).carrier) :
    ∃ f : C(jbSpec a, ℝ), jbCfc a f = x :=
  ⟨(jbCfcEquiv a).symm ⟨x, hx⟩, by simp [jbCfc]⟩

theorem jbCfc_injective (a : A) : Function.Injective (jbCfc a) := fun _ _ h =>
  (jbCfcEquiv a).injective (Subtype.ext h)

/-- **H-O–S 3.2.4** (for a JB-algebra in REC 44's sense): `C(a)` is associative, `sp(a)`
is compact, and `f ↦ f(a)` is a linear isomorphism `C(sp a, ℝ) ≅ C(a)` that is
isometric, multiplicative, unital, order-preserving and -reflecting, with `id ↦ a`. -/
theorem hos324 (a : A) :
    (∀ x ∈ (Ca a).carrier, ∀ y ∈ (Ca a).carrier, ∀ z ∈ (Ca a).carrier,
      x * y * z = x * (y * z)) ∧ IsCompact (jbSpec a) ∧
    ∃ Φ : C(jbSpec a, ℝ) ≃ₗ[ℝ] (Ca a).carrier,
      (∀ f, ousNorm A (Φ f) = ‖f‖) ∧ (∀ f g, (Φ (f * g) : A) = Φ f * Φ g) ∧
      (Φ 1 : A) = ouUnit A ∧ (Φ (specId a) : A) = a ∧ (∀ f, 0 ≤ (Φ f : A) ↔ ∀ t, 0 ≤ f t) :=
  ⟨Ca_assoc a, isCompact_jbSpec a, jbCfcEquiv a, ousNorm_jbCfc a, jbCfc_mul a, jbCfc_one a,
    jbCfc_id a, jbCfc_nonneg_iff a⟩

/-- A real polynomial as a continuous function on `sp(a)`. -/
def specPoly (a : A) (p : ℝ[X]) : C(jbSpec a, ℝ) :=
  ⟨fun t => p.eval t.1, p.continuous.comp continuous_subtype_val⟩

/-- **The calculus extends polynomial evaluation**: `p(a)` computed by the calculus is
`Σ cₙ aⁿ` computed with Jordan powers. -/
theorem jbCfc_specPoly (a : A) (p : ℝ[X]) : jbCfc a (specPoly a p) = jbEv a p := by
  have hpow : ∀ n : ℕ, jbCfc a (specId a ^ n) = jbPow a n := by
    intro n
    induction n with
    | zero => rw [pow_zero, jbCfc_one]; rfl
    | succ n ih => rw [pow_succ', jbCfc_mul, jbCfc_id, ih]; rfl
  induction p using Polynomial.induction_on' with
  | add p q hp hq =>
    have e : specPoly a (p + q) = specPoly a p + specPoly a q := by
      ext t; simp [specPoly]
    rw [e, jbCfc_add, hp, hq, map_add]
  | monomial n c =>
    have e : specPoly a (Polynomial.monomial n c) = c • specId a ^ n := by
      ext t; simp [specPoly, specId]
    rw [e, jbCfc_smul, hpow, jbEv_monomial]

/-! ### Square roots -/

/-- `√` on `sp(a)`. -/
def specSqrt (a : A) : C(jbSpec a, ℝ) :=
  ⟨fun t => Real.sqrt t.1, Real.continuous_sqrt.comp continuous_subtype_val⟩

/-- **The square root** `√a := (t ↦ √t)(a)` (meaningful for `a ≥ 0`). -/
def jbSqrt (a : A) : A := jbCfc a (specSqrt a)

theorem jbSqrt_mem (a : A) : jbSqrt a ∈ (Ca a).carrier := jbCfc_mem a _

theorem jbSqrt_nonneg (a : A) : 0 ≤ jbSqrt a :=
  (jbCfc_nonneg_iff a _).2 fun _ => Real.sqrt_nonneg _

/-- **Exact square roots**: `√a · √a = a` for `a ≥ 0`. -/
theorem jbSqrt_mul_self {a : A} (ha : 0 ≤ a) : jbSqrt a * jbSqrt a = a := by
  rw [jbSqrt, ← jbCfc_mul]
  conv_rhs => rw [← jbCfc_id a]
  congr 1
  ext t
  exact Real.mul_self_sqrt (jbSpec_nonneg ha t.2)

/-- **Uniqueness of positive square roots**: if `s ≥ 0` and `s² = a` then `s = √a`
(both lie in the associative `C(s)`, where roots of positive elements are unique). -/
theorem jbSqrt_unique {a s : A} (ha : 0 ≤ a) (hs : 0 ≤ s) (hss : s * s = a) : s = jbSqrt a := by
  have haT : a ∈ (Ca s).carrier := hss ▸ (Ca s).mul_mem (self_mem_Ca s) (self_mem_Ca s)
  have hrT : jbSqrt a ∈ (Ca s).carrier := Ca_le (Ca s) haT (jbSqrt_mem a)
  have := assoc_sqrt_unique (CA_assoc s) (u := aC s) (v := ⟨jbSqrt a, hrT⟩) hs
    (jbSqrt_nonneg a) (Subtype.ext (hss.trans (jbSqrt_mul_self ha).symm))
  exact congrArg Subtype.val this

/-- **The positive elements are exactly the squares**. -/
theorem nonneg_iff_exists_mul_self (a : A) : 0 ≤ a ↔ ∃ b : A, a = b * b :=
  ⟨fun h => ⟨jbSqrt a, (jbSqrt_mul_self h).symm⟩, fun ⟨b, hb⟩ => hb ▸ jb_sq_nonneg b⟩

/-- Positive elements of `C(a)` have positive products (the cone of `C(a)` is closed
under the Jordan product). -/
theorem Ca_mul_nonneg {a x y : A} (hx : x ∈ (Ca a).carrier) (hy : y ∈ (Ca a).carrier)
    (hx0 : 0 ≤ x) (hy0 : 0 ≤ y) : 0 ≤ x * y :=
  assoc_mul_nonneg (CA_assoc a) (x := ⟨x, hx⟩) (y := ⟨y, hy⟩) hx0 hy0

/-- The only case of **positivity of `U_a`** reachable here: `U_a b = 2a(ab) - a²b ≥ 0`
when `b ≥ 0` lies in `C(a)` (there `U_a b = a² b`).  The general case (H-O–S 3.3.6)
needs Macdonald's / Shirshov–Cohn's theorem for two generators. -/
theorem jQ_nonneg_of_mem_Ca {a b : A} (hb : b ∈ (Ca a).carrier) (hb0 : 0 ≤ b) : 0 ≤ jQ a b := by
  have ha := self_mem_Ca a
  have e : jQ a b = (a * a) * b := by
    rw [jQ, ← Ca_assoc a a ha a ha b hb, two_smul]; abel
  rw [e]
  exact Ca_mul_nonneg ((Ca a).mul_mem ha ha) hb (jb_sq_nonneg a) hb0

end Calculus

end

end Papers.REC.JBCalc

