/-
Papers/SIG/KochenSpecker.lean

The Kochen–Specker theorem, discharging the named hypothesis `KochenSpecker H`
of SIG 46 (main.tex:1257–1277): for a complex Hilbert space `H` with
`dim H > 2` (any dimension, finite or not) there is no unital σ-additive map
`P(H) → {0,1}`; so SIG 46's Kochen–Specker clause holds outright
(`sig46_unconditional`).

Plan.
1. Combinatorics (`ks_noColouring`): the Conway–Kochen set of 31 integer
   rays in `ℝ³` (coordinates in `{0,±1,±2}`; found by computer search as a
   minimal uncolourable subset of all such rays) admits no `{0,1}`-colouring
   with no two orthogonal rays coloured `1` and some ray of each of its 17
   orthogonal triples coloured `1`.  Proof: a DPLL tree with 6 leaves (split
   on rays 0, 3, 2/14), each closed by an explicit unit-propagation chain
   (generated by computer search, checked by Lean).
2. Frames.  For an orthonormal family `f : J × Fin 3 → H` (a "copy" of
   `ℂ³ ⊗ ℓ²(J)` inside `H`) and an integer ray `r`, put
   `g_r(j) = Σ_k r_k f(j,k)`, `K_r = (span g_r)ᗮᗮ` (closed), `P_r` its
   projection, and `R` the projection onto `W = (span f)ᗮ`.  Orthogonal rays
   give orthogonal `K_r` (so `P_r + P_s ≤ 1`); an orthogonal triple `a,b,c`
   gives `P_a + P_b + P_c + R = 1`: the defect `y` is orthogonal to every
   `g_a(j), g_b(j), g_c(j)`, hence (the triple spans `ℚ³`: an explicit
   integer identity, checked by `decide`) to every `f(j,k)`, so `y ∈ W ∩ Wᗮ`.
3. Valuations.  For a σ-additive `ω : P(H) → {0,1}` with `ω 1 = 1`:
   orthogonal projections are never both `1`, and of four projections summing
   to `1` one is `1`.  So if `ω R = 0` the colouring `i ↦ ω(P_{ray i})`
   contradicts step 1: every frame has `ω R = 1` (`frame_complement_true`).
4. Two frames with orthogonal complements `R₁ ⊥ R₂` then contradict step 3.
   Take a Hilbert basis `(b_i)_{i∈ι}`.  If `ι` is infinite, `ι ≃ ι × Fin 3`
   and one frame is the whole basis (`R = 0`).  If `ι` is finite,
   `|ι| = n = 3m + k ≥ 3` (`n = dim H`), and the frames are the first `3m`
   and the last `3m` basis vectors; their complements are spanned by the
   last `k` and the first `k` basis vectors, orthogonal as `k ≤ 3m`
   (Parseval).
Only finite additivity of `ω` is used.
-/
import Papers.SIG.Examples

open CategoryTheory Theses.B.Eff
open scoped InnerProductSpace

namespace Papers.SIG.KS

/-! ## 1. The Conway–Kochen rays -/

/-- The 31 rays (primitive integer vectors) of the Kochen–Specker set. -/
def ksRay : Fin 31 → Fin 3 → ℤ :=
  ![![0, 0, 1],
    ![0, 1, -2],
    ![0, 1, -1],
    ![0, 1, 0],
    ![0, 1, 1],
    ![0, 1, 2],
    ![0, 2, -1],
    ![0, 2, 1],
    ![1, -1, -2],
    ![1, -1, -1],
    ![1, -1, 0],
    ![1, -1, 1],
    ![1, -1, 2],
    ![1, 0, -2],
    ![1, 0, -1],
    ![1, 0, 0],
    ![1, 0, 1],
    ![1, 0, 2],
    ![1, 1, -2],
    ![1, 1, -1],
    ![1, 1, 0],
    ![1, 1, 1],
    ![1, 1, 2],
    ![1, 2, -1],
    ![1, 2, 0],
    ![1, 2, 1],
    ![2, -1, -1],
    ![2, -1, 0],
    ![2, -1, 1],
    ![2, 0, -1],
    ![2, 0, 1]]

def ksTriples : List (Fin 31 × Fin 31 × Fin 31) :=
  [(0, 3, 15), (0, 10, 20), (0, 24, 27), (1, 7, 15), (2, 4, 15), (2, 21, 26), (3, 13, 30), (3, 14, 16), (3, 17, 29), (4, 19, 28), (5, 6, 15), (8, 11, 20), (9, 12, 20), (9, 16, 23), (10, 18, 21), (10, 19, 22), (11, 14, 25)]

/-- The integer dot product on `ℤ³`. -/
def dotZ (r s : Fin 3 → ℤ) : ℤ := r 0 * s 0 + r 1 * s 1 + r 2 * s 2

theorem nb {x y : Bool} (h : x = true → y = true → False) (hx : x = true) : y = false := by
  cases y
  · rfl
  · exact (h hx rfl).elim

theorem nb' {x y : Bool} (h : x = true → y = true → False) (hy : y = true) : x = false := by
  cases x
  · rfl
  · exact (h rfl hy).elim

theorem tr1 {x y z : Bool} (h : x = true ∨ y = true ∨ z = true) (hy : y = false) (hz : z = false) :
    x = true := by
  subst hy hz; simpa using h

theorem tr2 {x y z : Bool} (h : x = true ∨ y = true ∨ z = true) (hx : x = false) (hz : z = false) :
    y = true := by
  subst hx hz; simpa using h

theorem tr3 {x y z : Bool} (h : x = true ∨ y = true ∨ z = true) (hx : x = false) (hy : y = false) :
    z = true := by
  subst hx hy; simpa using h

theorem tr0 {x y z : Bool} (h : x = true ∨ y = true ∨ z = true) (hx : x = false) (hy : y = false)
    (hz : z = false) : False := by
  subst hx hy hz; simp at h

/-- **Kochen–Specker, combinatorial core**: no colouring of the 31 rays has
no two orthogonal rays coloured `true` and a `true` ray in each triple of
`ksTriples`. -/
theorem ks_noColouring (c : Fin 31 → Bool)
    (hp : ∀ i j, dotZ (ksRay i) (ksRay j) = 0 → c i = true → c j = true → False)
    (ht : ∀ a b d, (a, b, d) ∈ ksTriples → c a = true ∨ c b = true ∨ c d = true) : False := by
  have p0_3 := hp 0 3 (by decide)
  have p0_10 := hp 0 10 (by decide)
  have p0_15 := hp 0 15 (by decide)
  have p0_20 := hp 0 20 (by decide)
  have p0_24 := hp 0 24 (by decide)
  have p0_27 := hp 0 27 (by decide)
  have p1_7 := hp 1 7 (by decide)
  have p1_15 := hp 1 15 (by decide)
  have p1_25 := hp 1 25 (by decide)
  have p2_4 := hp 2 4 (by decide)
  have p2_9 := hp 2 9 (by decide)
  have p2_15 := hp 2 15 (by decide)
  have p2_21 := hp 2 21 (by decide)
  have p2_26 := hp 2 26 (by decide)
  have p3_13 := hp 3 13 (by decide)
  have p3_14 := hp 3 14 (by decide)
  have p3_15 := hp 3 15 (by decide)
  have p3_16 := hp 3 16 (by decide)
  have p3_17 := hp 3 17 (by decide)
  have p3_29 := hp 3 29 (by decide)
  have p3_30 := hp 3 30 (by decide)
  have p4_11 := hp 4 11 (by decide)
  have p4_15 := hp 4 15 (by decide)
  have p4_19 := hp 4 19 (by decide)
  have p4_28 := hp 4 28 (by decide)
  have p5_6 := hp 5 6 (by decide)
  have p5_15 := hp 5 15 (by decide)
  have p5_23 := hp 5 23 (by decide)
  have p6_8 := hp 6 8 (by decide)
  have p6_15 := hp 6 15 (by decide)
  have p6_22 := hp 6 22 (by decide)
  have p7_12 := hp 7 12 (by decide)
  have p7_15 := hp 7 15 (by decide)
  have p7_18 := hp 7 18 (by decide)
  have p8_11 := hp 8 11 (by decide)
  have p8_20 := hp 8 20 (by decide)
  have p8_30 := hp 8 30 (by decide)
  have p9_12 := hp 9 12 (by decide)
  have p9_16 := hp 9 16 (by decide)
  have p9_20 := hp 9 20 (by decide)
  have p9_23 := hp 9 23 (by decide)
  have p10_18 := hp 10 18 (by decide)
  have p10_19 := hp 10 19 (by decide)
  have p10_20 := hp 10 20 (by decide)
  have p10_21 := hp 10 21 (by decide)
  have p10_22 := hp 10 22 (by decide)
  have p11_14 := hp 11 14 (by decide)
  have p11_20 := hp 11 20 (by decide)
  have p11_25 := hp 11 25 (by decide)
  have p12_20 := hp 12 20 (by decide)
  have p12_29 := hp 12 29 (by decide)
  have p13_28 := hp 13 28 (by decide)
  have p13_30 := hp 13 30 (by decide)
  have p14_16 := hp 14 16 (by decide)
  have p14_21 := hp 14 21 (by decide)
  have p14_25 := hp 14 25 (by decide)
  have p16_19 := hp 16 19 (by decide)
  have p16_23 := hp 16 23 (by decide)
  have p17_26 := hp 17 26 (by decide)
  have p17_29 := hp 17 29 (by decide)
  have p18_21 := hp 18 21 (by decide)
  have p18_30 := hp 18 30 (by decide)
  have p19_22 := hp 19 22 (by decide)
  have p19_28 := hp 19 28 (by decide)
  have p21_26 := hp 21 26 (by decide)
  have p22_29 := hp 22 29 (by decide)
  have p23_27 := hp 23 27 (by decide)
  have p24_26 := hp 24 26 (by decide)
  have p24_27 := hp 24 27 (by decide)
  have p24_28 := hp 24 28 (by decide)
  have p25_27 := hp 25 27 (by decide)
  have t0_3_15 := ht 0 3 15 (by decide)
  have t0_10_20 := ht 0 10 20 (by decide)
  have t0_24_27 := ht 0 24 27 (by decide)
  have t1_7_15 := ht 1 7 15 (by decide)
  have t2_4_15 := ht 2 4 15 (by decide)
  have t2_21_26 := ht 2 21 26 (by decide)
  have t3_13_30 := ht 3 13 30 (by decide)
  have t3_14_16 := ht 3 14 16 (by decide)
  have t3_17_29 := ht 3 17 29 (by decide)
  have t4_19_28 := ht 4 19 28 (by decide)
  have t5_6_15 := ht 5 6 15 (by decide)
  have t8_11_20 := ht 8 11 20 (by decide)
  have t9_12_20 := ht 9 12 20 (by decide)
  have t9_16_23 := ht 9 16 23 (by decide)
  have t10_18_21 := ht 10 18 21 (by decide)
  have t10_19_22 := ht 10 19 22 (by decide)
  have t11_14_25 := ht 11 14 25 (by decide)
  cases v0 : c 0
  · cases v3 : c 3
    · cases v14 : c 14
      · have v15 := tr3 t0_3_15 v0 v3
        have v1 := nb' p1_15 v15
        have v2 := nb' p2_15 v15
        have v4 := nb' p4_15 v15
        have v5 := nb' p5_15 v15
        have v6 := nb' p6_15 v15
        have v7 := nb' p7_15 v15
        have v16 := tr3 t3_14_16 v3 v14
        have v9 := nb' p9_16 v16
        have v19 := nb p16_19 v16
        have v23 := nb p16_23 v16
        have v28 := tr3 t4_19_28 v4 v19
        have v13 := nb' p13_28 v28
        have v24 := nb' p24_28 v28
        have v27 := tr3 t0_24_27 v0 v24
        have v25 := nb' p25_27 v27
        have v30 := tr3 t3_13_30 v3 v13
        have v8 := nb' p8_30 v30
        have v18 := nb' p18_30 v30
        have v11 := tr1 t11_14_25 v14 v25
        have v20 := nb p11_20 v11
        have v10 := tr2 t0_10_20 v0 v20
        have v21 := nb p10_21 v10
        have v22 := nb p10_22 v10
        have v26 := tr3 t2_21_26 v2 v21
        have v17 := nb' p17_26 v26
        have v29 := tr3 t3_17_29 v3 v17
        have v12 := nb' p12_29 v29
        exact tr0 t9_12_20 v9 v12 v20
      · have v11 := nb' p11_14 v14
        have v16 := nb p14_16 v14
        have v21 := nb p14_21 v14
        have v25 := nb p14_25 v14
        have v15 := tr3 t0_3_15 v0 v3
        have v1 := nb' p1_15 v15
        have v2 := nb' p2_15 v15
        have v4 := nb' p4_15 v15
        have v5 := nb' p5_15 v15
        have v6 := nb' p6_15 v15
        have v7 := nb' p7_15 v15
        have v26 := tr3 t2_21_26 v2 v21
        have v17 := nb' p17_26 v26
        have v24 := nb' p24_26 v26
        have v27 := tr3 t0_24_27 v0 v24
        have v23 := nb' p23_27 v27
        have v29 := tr3 t3_17_29 v3 v17
        have v12 := nb' p12_29 v29
        have v22 := nb' p22_29 v29
        have v9 := tr1 t9_16_23 v16 v23
        have v20 := nb p9_20 v9
        have v10 := tr2 t0_10_20 v0 v20
        have v18 := nb p10_18 v10
        have v19 := nb p10_19 v10
        have v28 := tr3 t4_19_28 v4 v19
        have v13 := nb' p13_28 v28
        have v30 := tr3 t3_13_30 v3 v13
        have v8 := nb' p8_30 v30
        exact tr0 t8_11_20 v8 v11 v20
    · cases v2 : c 2
      · have v13 := nb p3_13 v3
        have v14 := nb p3_14 v3
        have v15 := nb p3_15 v3
        have v16 := nb p3_16 v3
        have v17 := nb p3_17 v3
        have v29 := nb p3_29 v3
        have v30 := nb p3_30 v3
        have v4 := tr2 t2_4_15 v2 v15
        have v11 := nb p4_11 v4
        have v19 := nb p4_19 v4
        have v28 := nb p4_28 v4
        have v25 := tr3 t11_14_25 v11 v14
        have v1 := nb' p1_25 v25
        have v27 := nb p25_27 v25
        have v24 := tr2 t0_24_27 v0 v27
        have v26 := nb p24_26 v24
        have v7 := tr2 t1_7_15 v1 v15
        have v12 := nb p7_12 v7
        have v18 := nb p7_18 v7
        have v21 := tr2 t2_21_26 v2 v26
        have v10 := nb' p10_21 v21
        have v20 := tr3 t0_10_20 v0 v10
        have v8 := nb' p8_20 v20
        have v9 := nb' p9_20 v20
        have v23 := tr3 t9_16_23 v9 v16
        have v5 := nb' p5_23 v23
        have v6 := tr2 t5_6_15 v5 v15
        have v22 := nb p6_22 v6
        exact tr0 t10_19_22 v10 v19 v22
      · have v4 := nb p2_4 v2
        have v9 := nb p2_9 v2
        have v15 := nb p2_15 v2
        have v21 := nb p2_21 v2
        have v26 := nb p2_26 v2
        have v13 := nb p3_13 v3
        have v14 := nb p3_14 v3
        have v16 := nb p3_16 v3
        have v17 := nb p3_17 v3
        have v29 := nb p3_29 v3
        have v30 := nb p3_30 v3
        have v23 := tr3 t9_16_23 v9 v16
        have v5 := nb' p5_23 v23
        have v27 := nb p23_27 v23
        have v24 := tr2 t0_24_27 v0 v27
        have v28 := nb p24_28 v24
        have v19 := tr2 t4_19_28 v4 v28
        have v10 := nb' p10_19 v19
        have v22 := nb p19_22 v19
        have v20 := tr3 t0_10_20 v0 v10
        have v8 := nb' p8_20 v20
        have v11 := nb' p11_20 v20
        have v12 := nb' p12_20 v20
        have v6 := tr2 t5_6_15 v5 v15
        have v18 := tr2 t10_18_21 v10 v21
        have v7 := nb' p7_18 v18
        have v1 := tr1 t1_7_15 v7 v15
        have v25 := nb p1_25 v1
        exact tr0 t11_14_25 v11 v14 v25
  · cases v2 : c 2
    · have v3 := nb p0_3 v0
      have v10 := nb p0_10 v0
      have v15 := nb p0_15 v0
      have v20 := nb p0_20 v0
      have v24 := nb p0_24 v0
      have v27 := nb p0_27 v0
      have v4 := tr2 t2_4_15 v2 v15
      have v11 := nb p4_11 v4
      have v19 := nb p4_19 v4
      have v28 := nb p4_28 v4
      have v8 := tr1 t8_11_20 v11 v20
      have v6 := nb' p6_8 v8
      have v30 := nb p8_30 v8
      have v13 := tr2 t3_13_30 v3 v30
      have v5 := tr1 t5_6_15 v6 v15
      have v23 := nb p5_23 v5
      have v22 := tr3 t10_19_22 v10 v19
      have v29 := nb p22_29 v22
      have v17 := tr2 t3_17_29 v3 v29
      have v26 := nb p17_26 v17
      have v21 := tr2 t2_21_26 v2 v26
      have v14 := nb' p14_21 v21
      have v18 := nb' p18_21 v21
      have v16 := tr3 t3_14_16 v3 v14
      have v9 := nb' p9_16 v16
      have v12 := tr2 t9_12_20 v9 v20
      have v7 := nb' p7_12 v12
      have v1 := tr1 t1_7_15 v7 v15
      have v25 := nb p1_25 v1
      exact tr0 t11_14_25 v11 v14 v25
    · have v3 := nb p0_3 v0
      have v10 := nb p0_10 v0
      have v15 := nb p0_15 v0
      have v20 := nb p0_20 v0
      have v24 := nb p0_24 v0
      have v27 := nb p0_27 v0
      have v4 := nb p2_4 v2
      have v9 := nb p2_9 v2
      have v21 := nb p2_21 v2
      have v26 := nb p2_26 v2
      have v12 := tr2 t9_12_20 v9 v20
      have v7 := nb' p7_12 v12
      have v29 := nb p12_29 v12
      have v1 := tr1 t1_7_15 v7 v15
      have v25 := nb p1_25 v1
      have v17 := tr2 t3_17_29 v3 v29
      have v18 := tr2 t10_18_21 v10 v21
      have v30 := nb p18_30 v18
      have v13 := tr2 t3_13_30 v3 v30
      have v28 := nb p13_28 v13
      have v19 := tr2 t4_19_28 v4 v28
      have v16 := nb' p16_19 v19
      have v22 := nb p19_22 v19
      have v14 := tr2 t3_14_16 v3 v16
      have v11 := nb' p11_14 v14
      have v8 := tr1 t8_11_20 v11 v20
      have v6 := nb' p6_8 v8
      have v5 := tr1 t5_6_15 v6 v15
      have v23 := nb p5_23 v5
      exact tr0 t9_16_23 v9 v16 v23

/-! ## 2. Orthogonal triples span -/

/-- The squared norm `|r|²` of an integer vector. -/
def nsq (r : Fin 3 → ℤ) : ℤ := dotZ r r

/-- An orthogonal triple of nonzero integer vectors, with the integer form of
`Σ_v v vᵀ / |v|² = 1` (so the triple spans). -/
def TripleOK (r s t : Fin 3 → ℤ) : Prop :=
  dotZ r s = 0 ∧ dotZ r t = 0 ∧ dotZ s t = 0 ∧ nsq r * nsq s * nsq t ≠ 0 ∧
    ∀ j k : Fin 3, r j * r k * (nsq s * nsq t) + s j * s k * (nsq r * nsq t) +
      t j * t k * (nsq r * nsq s) = if j = k then nsq r * nsq s * nsq t else 0

instance (r s t : Fin 3 → ℤ) : Decidable (TripleOK r s t) := by
  unfold TripleOK; infer_instance

/-- A Boolean checker for `TripleOK`. -/
def tripleOKb (r s t : Fin 3 → ℤ) : Bool :=
  dotZ r s == 0 && dotZ r t == 0 && dotZ s t == 0 && nsq r * nsq s * nsq t != 0 &&
    (List.finRange 3).all fun j => (List.finRange 3).all fun k =>
      r j * r k * (nsq s * nsq t) + s j * s k * (nsq r * nsq t) + t j * t k * (nsq r * nsq s) ==
        if j = k then nsq r * nsq s * nsq t else 0

theorem tripleOK_of_b {r s t : Fin 3 → ℤ} (h : tripleOKb r s t = true) : TripleOK r s t := by
  simp only [tripleOKb, Bool.and_eq_true, beq_iff_eq, bne_iff_ne, ne_eq, List.all_eq_true,
    List.mem_finRange, forall_const] at h
  exact ⟨h.1.1.1.1, h.1.1.1.2, h.1.1.2, h.1.2, h.2⟩

theorem ksTriples_okb : (ksTriples.all fun t => tripleOKb (ksRay t.1) (ksRay t.2.1) (ksRay t.2.2)) = true := by
  decide +kernel

theorem ksTriples_ok : ∀ t ∈ ksTriples, TripleOK (ksRay t.1) (ksRay t.2.1) (ksRay t.2.2) := by
  intro t ht
  exact tripleOK_of_b (List.all_eq_true.1 ksTriples_okb t ht)

/-- A vector `w ∈ ℂ³` orthogonal (bilinearly) to an orthogonal spanning
triple is zero. -/
theorem triple_span {r s t : Fin 3 → ℤ} (h : TripleOK r s t) (w : Fin 3 → ℂ)
    (hr : ∑ k, (r k : ℂ) * w k = 0) (hs : ∑ k, (s k : ℂ) * w k = 0)
    (ht : ∑ k, (t k : ℂ) * w k = 0) (j : Fin 3) : w j = 0 := by
  obtain ⟨-, -, -, hN, hid⟩ := h
  have e : ∀ k, ((r j * r k * (nsq s * nsq t) + s j * s k * (nsq r * nsq t) +
      t j * t k * (nsq r * nsq s) : ℤ) : ℂ) = ((if j = k then nsq r * nsq s * nsq t else 0 : ℤ) : ℂ) :=
    fun k => congrArg _ (hid j k)
  have key : ((nsq r * nsq s * nsq t : ℤ) : ℂ) * w j =
      ((r j : ℂ) * nsq s * nsq t) * ∑ k, (r k : ℂ) * w k +
        ((s j : ℂ) * nsq r * nsq t) * ∑ k, (s k : ℂ) * w k +
        ((t j : ℂ) * nsq r * nsq s) * ∑ k, (t k : ℂ) * w k := by
    have h1 : ((nsq r * nsq s * nsq t : ℤ) : ℂ) * w j =
        ∑ k, w k * ((if j = k then nsq r * nsq s * nsq t else 0 : ℤ) : ℂ) := by
      simp [Int.cast_ite, mul_ite, Finset.sum_ite_eq, mul_comm]
    rw [h1]
    simp_rw [← e]
    push_cast
    simp only [Fin.sum_univ_three]
    ring
  rw [hr, hs, ht] at key
  simp only [mul_zero, add_zero] at key
  rcases mul_eq_zero.1 key with h0 | h0
  · exact absurd (by exact_mod_cast h0) hN
  · exact h0

/-! ## 3. Frames: copies of `ℂ³ ⊗ ℓ²(J)` inside `H` -/

section Frames

set_option linter.unusedSectionVars false

open Submodule

variable {H : Type} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable {J : Type} (f : J × Fin 3 → H)

/-- `g_r(j) = Σ_k r_k f(j,k)`. -/
noncomputable def gvec (r : Fin 3 → ℤ) (j : J) : H := ∑ k, (r k : ℂ) • f (j, k)

/-- `K_r = (span g_r)ᗮᗮ`, the closed span of the `g_r(j)`. -/
noncomputable abbrev Ksub (r : Fin 3 → ℤ) : Submodule ℂ H := (span ℂ (Set.range (gvec f r)))ᗮᗮ

/-- `W = (span f)ᗮ`, the complement of the frame. -/
noncomputable abbrev Wsub : Submodule ℂ H := (span ℂ (Set.range f))ᗮ

theorem inner_gvec (hf : Orthonormal ℂ f) {r s : Fin 3 → ℤ} (h : dotZ r s = 0) (j j' : J) :
    ⟪gvec f r j, gvec f s j'⟫_ℂ = 0 := by
  classical
  have ho := orthonormal_iff_ite.1 hf
  simp only [gvec, sum_inner, inner_sum, inner_smul_left, inner_smul_right, ho, Prod.mk.injEq,
    map_intCast]
  by_cases hj : j = j'
  · subst hj
    have h' : ((dotZ r s : ℤ) : ℂ) = 0 := by rw [h]; simp
    simp only [dotZ] at h'
    push_cast at h'
    simp [Fin.sum_univ_three]
    linear_combination h'
  · simp [hj]

theorem gvec_mem_span (r : Fin 3 → ℤ) (j : J) : gvec f r j ∈ span ℂ (Set.range f) :=
  sum_mem fun k _ => smul_mem _ _ (subset_span ⟨(j, k), rfl⟩)

theorem gvec_mem_K (r : Fin 3 → ℤ) (j : J) : gvec f r j ∈ Ksub f r :=
  le_orthogonal_orthogonal _ (subset_span ⟨j, rfl⟩)

theorem isOrtho_oo {U V : Submodule ℂ H} (h : U ⟂ V) : Uᗮᗮ ⟂ Vᗮᗮ := by
  have h1 : Uᗮᗮ ⟂ V := isOrtho_iff_le.2
    ((orthogonal_le (orthogonal_le (isOrtho_iff_le.1 h))).trans_eq triorthogonal_eq_orthogonal)
  have h2 : Vᗮᗮ ⟂ Uᗮᗮ := isOrtho_iff_le.2
    ((orthogonal_le (orthogonal_le (isOrtho_iff_le.1 (isOrtho_comm.1 h1)))).trans_eq
      triorthogonal_eq_orthogonal)
  exact isOrtho_comm.1 h2

theorem K_ortho (hf : Orthonormal ℂ f) {r s : Fin 3 → ℤ} (h : dotZ r s = 0) :
    Ksub f r ⟂ Ksub f s := by
  refine isOrtho_oo (isOrtho_span.2 ?_)
  rintro _ ⟨j, rfl⟩ _ ⟨j', rfl⟩
  exact inner_gvec f hf h j j'

theorem K_le_W_orth (r : Fin 3 → ℤ) : Ksub f r ≤ (Wsub f)ᗮ :=
  orthogonal_le (orthogonal_le (span_le.2 (by rintro _ ⟨j, rfl⟩; exact gvec_mem_span f r j)))

theorem mem_orth_span {s : Set H} {y : H} (h : ∀ u ∈ s, ⟪u, y⟫_ℂ = 0) : y ∈ (span ℂ s)ᗮ := by
  have : span ℂ {y} ⟂ span ℂ s := isOrtho_comm.1 (isOrtho_span.2 fun u hu v hv => by
    rw [Set.mem_singleton_iff.1 hv]; exact h u hu)
  exact isOrtho_iff_le.1 this (subset_span rfl)

/-- The projection `P_r` onto `K_r`. -/
noncomputable abbrev PK (r : Fin 3 → ℤ) : H →L[ℂ] H := (Ksub f r).starProjection

/-- The projection `R` onto the complement `W` of the frame. -/
noncomputable abbrev PW : H →L[ℂ] H := (Wsub f).starProjection

theorem PK_mul (hf : Orthonormal ℂ f) {r s : Fin 3 → ℤ} (h : dotZ r s = 0) :
    PK f r * PK f s = 0 :=
  (K_ortho f hf h).starProjection_comp_starProjection

/-- The defect of a triple lies in `K_aᗮ`. -/
theorem defect_mem (hf : Orthonormal ℂ f) {a b c : Fin 3 → ℤ} (hab : dotZ a b = 0)
    (hac : dotZ a c = 0) (x : H) :
    x - (PK f a x + PK f b x + PK f c x + PW f x) ∈ (Ksub f a)ᗮ := by
  have e : x - (PK f a x + PK f b x + PK f c x + PW f x) =
      (x - PK f a x) - PK f b x - PK f c x - PW f x := by abel
  rw [e]
  refine sub_mem (sub_mem (sub_mem (sub_starProjection_mem_orthogonal x) ?_) ?_) ?_
  · exact isOrtho_iff_le.1 (isOrtho_comm.1 (K_ortho f hf hab)) (starProjection_apply_mem _ x)
  · exact isOrtho_iff_le.1 (isOrtho_comm.1 (K_ortho f hf hac)) (starProjection_apply_mem _ x)
  · exact isOrtho_iff_le.1 (isOrtho_comm.1 (isOrtho_iff_le.2 (K_le_W_orth f a)))
      (starProjection_apply_mem _ x)

theorem inner_gvec_left (r : Fin 3 → ℤ) (j : J) (y : H) :
    ⟪gvec f r j, y⟫_ℂ = ∑ k, (r k : ℂ) * ⟪f (j, k), y⟫_ℂ := by
  simp only [gvec, sum_inner, inner_smul_left, map_intCast]

/-- An orthogonal triple of rays decomposes the identity together with `R`. -/
theorem triple_sum (hf : Orthonormal ℂ f) {a b c : Fin 3 → ℤ} (h : TripleOK a b c) :
    PK f a + PK f b + PK f c + PW f = 1 := by
  obtain ⟨hab, hac, hbc, -, -⟩ := id h
  have hba : dotZ b a = 0 := by rw [← hab]; simp only [dotZ]; ring
  have hca : dotZ c a = 0 := by rw [← hac]; simp only [dotZ]; ring
  have hcb : dotZ c b = 0 := by rw [← hbc]; simp only [dotZ]; ring
  ext x
  show PK f a x + PK f b x + PK f c x + PW f x = x
  set y := x - (PK f a x + PK f b x + PK f c x + PW f x) with hy
  have ya := defect_mem f hf hab hac x
  have yb : y ∈ (Ksub f b)ᗮ := by
    have := defect_mem f hf hba hbc x
    convert this using 2; abel
  have yc : y ∈ (Ksub f c)ᗮ := by
    have := defect_mem f hf hca hcb x
    convert this using 2; abel
  have hz : ∀ (r : Fin 3 → ℤ), y ∈ (Ksub f r)ᗮ → ∀ j, ∑ k, (r k : ℂ) * ⟪f (j, k), y⟫_ℂ = 0 :=
    fun r hr j => by rw [← inner_gvec_left]; exact inner_right_of_mem_orthogonal (gvec_mem_K f r j) hr
  have yW : y ∈ Wsub f := by
    refine mem_orth_span ?_
    rintro _ ⟨⟨j, k⟩, rfl⟩
    exact triple_span h (fun k => ⟪f (j, k), y⟫_ℂ) (hz a ya j) (hz b yb j) (hz c yc j) k
  have yW' : y ∈ (Wsub f)ᗮ := by
    have e : y = (x - PW f x) - PK f a x - PK f b x - PK f c x := by rw [hy]; abel
    rw [e]
    refine sub_mem (sub_mem (sub_mem (sub_starProjection_mem_orthogonal x) ?_) ?_) ?_ <;>
      exact K_le_W_orth f _ (starProjection_apply_mem _ x)
  have : y = 0 := by
    have := (Wsub f).inf_orthogonal_eq_bot
    have hmem : y ∈ Wsub f ⊓ (Wsub f)ᗮ := ⟨yW, yW'⟩
    rw [this] at hmem
    exact hmem
  rw [hy, sub_eq_zero] at this
  exact this.symm

end Frames

/-! ## 4. Valuations `P(H) → {0,1}` -/

section Valuations

set_option linter.unusedSectionVars false

open Submodule

variable {H : Type} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

theorem bool_ovee (a b : Bool) (h : Perp a b) : ovee a b h = (a || b) := by
  cases a <;> cases b <;> rfl

theorem bool_perp (a b : Bool) (h : Perp a b) : ¬(a = true ∧ b = true) := by
  rintro ⟨rfl, rfl⟩
  cases h

/-- A star projection of `B(H)` as an element of `P(H)`. -/
noncomputable def mkProj (p : H →L[ℂ] H) (hp : IsStarProjection p) : Proj (H →L[ℂ] H) :=
  ⟨⟨p, hp.nonneg, hp.le_one⟩, hp⟩

variable (ω : seaProj (H →L[ℂ] H) ⟶ seaBool)

theorem val_ovee {x y : Proj (H →L[ℂ] H)} (h : Perp x y) :
    ω.toFun (ovee x y h : Proj (H →L[ℂ] H)) = (ω.toFun x || ω.toFun y) := by
  obtain ⟨h', e⟩ := ω.additive.2 h
  exact e.symm.trans (bool_ovee _ _ h')

theorem val_pair {x y : Proj (H →L[ℂ] H)} (h : ((x.1 : H →L[ℂ] H) + y.1) ≤ 1) :
    ¬(ω.toFun x = true ∧ ω.toFun y = true) := by
  obtain ⟨h', -⟩ := ω.additive.2 (x := x) (y := y) h
  exact bool_perp _ _ h'

theorem val_four {p q r s : Proj (H →L[ℂ] H)}
    (hsum : ((p.1 : H →L[ℂ] H) + q.1 + r.1 + s.1) = 1) (h1 : ω.toFun 1 = true)
    (hs : ω.toFun s = false) : ω.toFun p = true ∨ ω.toFun q = true ∨ ω.toFun r = true := by
  have hpq : Perp p q := show ((p.1 : H →L[ℂ] H) + q.1) ≤ 1 from
    calc ((p.1 : H →L[ℂ] H) + q.1) ≤ p.1 + q.1 + r.1 := le_add_of_nonneg_right r.1.2.1
      _ ≤ p.1 + q.1 + r.1 + s.1 := le_add_of_nonneg_right s.1.2.1
      _ = 1 := hsum
  have hpqr : Perp (ovee p q hpq) r := show ((p.1 : H →L[ℂ] H) + q.1 + r.1) ≤ 1 from
    calc ((p.1 : H →L[ℂ] H) + q.1 + r.1) ≤ p.1 + q.1 + r.1 + s.1 := le_add_of_nonneg_right s.1.2.1
      _ = 1 := hsum
  have hpqrs : Perp (ovee (ovee p q hpq) r hpqr) s :=
    show ((p.1 : H →L[ℂ] H) + q.1 + r.1 + s.1) ≤ 1 from hsum.le
  have htot : ovee (ovee (ovee p q hpq) r hpqr) s hpqrs = 1 := Subtype.ext (Subtype.ext hsum)
  have e := val_ovee ω hpqrs
  rw [val_ovee ω hpqr, val_ovee ω hpq, hs] at e
  have e' : ω.toFun (ovee (ovee (ovee p q hpq) r hpqr) s hpqrs : Proj (H →L[ℂ] H)) = true :=
    (congrArg ω.toFun htot).trans h1
  rw [e] at e'
  revert e'
  cases ω.toFun p <;> cases ω.toFun q <;> cases ω.toFun r <;> simp

theorem add_le_one_of_mul {p q : H →L[ℂ] H} (hp : IsStarProjection p) (hq : IsStarProjection q)
    (h : p * q = 0) : p + q ≤ 1 :=
  ((Theses.A.VN.orthogonal_tuple_of_projections_1 p q hp hq).out 0 3).1 h

/-- **Every frame's complement has value `1`**: otherwise the colouring
`i ↦ ω(P_{ray i})` would contradict `ks_noColouring`. -/
theorem frame_complement_true (h1 : ω.toFun 1 = true) {J : Type} (f : J × Fin 3 → H)
    (hf : Orthonormal ℂ f) : ω.toFun (mkProj (PW f) isStarProjection_starProjection) = true := by
  by_contra hR'
  have hR := Bool.eq_false_iff.2 hR'
  refine ks_noColouring (fun i => ω.toFun (mkProj (PK f (ksRay i)) isStarProjection_starProjection))
    ?_ ?_
  · intro i j hij hi hj
    exact val_pair ω (add_le_one_of_mul isStarProjection_starProjection
      isStarProjection_starProjection (PK_mul f hf hij)) ⟨hi, hj⟩
  · intro a b d hmem
    exact val_four ω (s := mkProj (PW f) isStarProjection_starProjection)
      (triple_sum f hf (ksTriples_ok _ hmem)) h1 hR

end Valuations

/-! ## 5. The Kochen–Specker theorem -/

section Main

open Submodule

/-- Frames whose complements are spanned by complementary parts of a Hilbert
basis have orthogonal complements (Parseval). -/
theorem W_ortho_of_cover {H : Type} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] {ι : Type} (b : HilbertBasis ι ℂ H) {J1 J2 : Type}
    (f1 : J1 × Fin 3 → H) (f2 : J2 × Fin 3 → H)
    (hc : ∀ i, b i ∈ Set.range f1 ∨ b i ∈ Set.range f2) : Wsub f1 ⟂ Wsub f2 := by
  rw [isOrtho_iff_le]
  intro x hx
  rw [mem_orthogonal]
  intro y hy
  rw [← b.tsum_inner_mul_inner y x]
  have hz : ∀ i, ⟪y, b i⟫_ℂ * ⟪b i, x⟫_ℂ = 0 := by
    intro i
    rcases hc i with ⟨p, hp⟩ | ⟨p, hp⟩
    · have : b i ∈ span ℂ (Set.range f1) := hp ▸ subset_span ⟨p, rfl⟩
      rw [inner_right_of_mem_orthogonal this hx, mul_zero]
    · have : b i ∈ span ℂ (Set.range f2) := hp ▸ subset_span ⟨p, rfl⟩
      rw [inner_left_of_mem_orthogonal this hy, zero_mul]
  simp only [hz, tsum_zero]

/-- **SIG 46** (main.tex:1257–1277, Example), the cited Kochen–Specker
theorem [KS67], proved (via the Conway–Kochen 31 rays): for a complex Hilbert space `H` with `dim H > 2`
there is no unital (σ-)additive map `P(H) → {0,1}`.  This discharges the
named hypothesis `KochenSpecker H` of SIG 46, in every dimension (finite or
infinite, separable or not). -/
theorem kochenSpecker_holds (H : Type) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] : KochenSpecker H := by
  intro hdim ω h1
  have key : ∀ {J1 J2 : Type} (f1 : J1 × Fin 3 → H) (f2 : J2 × Fin 3 → H),
      Orthonormal ℂ f1 → Orthonormal ℂ f2 → Wsub f1 ⟂ Wsub f2 → False := by
    intro J1 J2 f1 f2 hf1 hf2 hW
    exact val_pair ω (x := mkProj (PW f1) isStarProjection_starProjection)
      (y := mkProj (PW f2) isStarProjection_starProjection)
      (add_le_one_of_mul isStarProjection_starProjection isStarProjection_starProjection
        hW.starProjection_comp_starProjection)
      ⟨frame_complement_true ω h1 f1 hf1, frame_complement_true ω h1 f2 hf2⟩
  obtain ⟨w, b, -⟩ := exists_hilbertBasis ℂ H
  rcases finite_or_infinite w with hfin | hinf
  · -- finite dimension `n = 3m + k ≥ 3`: the first and the last `3m` basis vectors
    let _ := Fintype.ofFinite w
    have hrank : Module.rank ℂ H = Fintype.card w := rank_eq_card_basis b.toOrthonormalBasis.toBasis
    have hn : 2 < Fintype.card w := by
      rw [hrank] at hdim; exact_mod_cast hdim
    set n := Fintype.card w with hn_def
    let σ : Fin n ≃ w := (Fintype.equivFin w).symm
    let e1 : Fin (n / 3) × Fin 3 → w := fun p => σ ⟨3 * p.1 + p.2, by omega⟩
    let e2 : Fin (n / 3) × Fin 3 → w := fun p => σ ⟨n % 3 + 3 * p.1 + p.2, by omega⟩
    have he1 : Function.Injective e1 := by
      rintro ⟨j, a⟩ ⟨j', a'⟩ h
      have := Fin.mk.inj_iff.1 (σ.injective h)
      simp only [Prod.mk.injEq, Fin.ext_iff] at this ⊢; omega
    have he2 : Function.Injective e2 := by
      rintro ⟨j, a⟩ ⟨j', a'⟩ h
      have := Fin.mk.inj_iff.1 (σ.injective h)
      simp only [Prod.mk.injEq, Fin.ext_iff] at this ⊢; omega
    refine key (fun p => b (e1 p)) (fun p => b (e2 p)) (b.orthonormal.comp _ he1)
      (b.orthonormal.comp _ he2) (W_ortho_of_cover b _ _ fun i => ?_)
    have hi : σ (σ.symm i) = i := σ.apply_symm_apply i
    set t := σ.symm i
    by_cases ht : t.1 < 3 * (n / 3)
    · refine Or.inl ⟨(⟨t.1 / 3, by omega⟩, ⟨t.1 % 3, by omega⟩), ?_⟩
      exact congrArg b ((congrArg σ (Fin.ext (by simp only; omega))).trans hi)
    · refine Or.inr ⟨(⟨(t.1 - n % 3) / 3, by omega⟩, ⟨(t.1 - n % 3) % 3, by omega⟩), ?_⟩
      exact congrArg b ((congrArg σ (Fin.ext (by simp only; omega))).trans hi)
  · -- infinite dimension: `w ≃ w × Fin 3`, one frame covering the whole basis
    have hc : Cardinal.mk (w × Fin 3) = Cardinal.mk w := by
      rw [Cardinal.mk_prod, Cardinal.lift_id, Cardinal.lift_id, Cardinal.mk_fin]
      exact Cardinal.mul_eq_left (Cardinal.infinite_iff.1 hinf)
        ((Cardinal.natCast_lt_aleph0 (n := 3)).le.trans (Cardinal.infinite_iff.1 hinf)) (by simp)
    obtain ⟨e⟩ := Cardinal.eq.1 hc
    have hf : Orthonormal ℂ (fun p => b (e p)) := b.orthonormal.comp _ e.injective
    exact key _ _ hf hf (W_ortho_of_cover b _ _ fun i => Or.inl ⟨e.symm i, by simp⟩)

/-- **SIG 46** (main.tex:1257–1277, Example), unconditionally: for a Hilbert
space `H` with `dim H > 2`, neither `P(H)` nor `E = [0,1]_{B(H)}` has a state
in `sEAᵒᵖ`, and every substate of `E` is zero — `sig46_kochenSpecker` with its
named hypothesis discharged by `kochenSpecker_holds`. -/
theorem sig46_unconditional (H : Type) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] (hdim : 2 < Module.rank ℂ H) :
    (∀ ω : Opposite.op seaBool ⟶ Opposite.op (seaProj (H →L[ℂ] H)), ¬ IsTotal ω) ∧
      (∀ ω : Opposite.op seaBool ⟶ Opposite.op (seaEffects (H →L[ℂ] H)), ¬ IsTotal ω) ∧
      ∀ (ω : Opposite.op seaBool ⟶ Opposite.op (seaEffects (H →L[ℂ] H)))
        (a : Theses.effects (H →L[ℂ] H)), ω.unop.toFun a = false :=
  sig46_kochenSpecker H (kochenSpecker_holds H) hdim

end Main

end Papers.SIG.KS

