/-
# The commutation theorem, unconditionally — Takesaki I, Theorem IV.5.9

`(𝒜 ⊗̄ ℬ)□ = 𝒜□ ⊗̄ ℬ□` for **arbitrary** von Neumann subalgebras `𝒜 ⊆ B(ℋ)`,
`ℬ ⊆ B(𝒦)`, and its corollary **121II** (`intersection_tensor`,
`proc.tex:4450`, Takesaki I, Cor. IV.5.10),

  `(𝒜₁ ⊗̄ ℬ₁) ∩ (𝒜₂ ⊗̄ ℬ₂) = (𝒜₁ ∩ 𝒜₂) ⊗̄ (ℬ₁ ∩ ℬ₂)`.

This file is one page of glue on top of two finished developments:

* `A/VN/CommutationTomita.lean`'s `CT_of_cyclicSeparating` — the theorem for a
  pair of algebras each carrying a **cyclic and separating** vector, via
  Rieffel–van Daele's bounded-operator proof of Tomita's theorem `J M J = M□`
  and the factorisation `J_{ω⊗ω'} = J_ω ⊗ J_{ω'}`;
* `A/Proc/CommutationCyclic.lean`'s `CT_of_CT_cyclicSeparating` — the
  amplify-and-cut reduction of the general case to that one.

The two were built to meet, and §1 below is the meeting: the only work is
that the two files phrase "cyclic and separating" differently
(`HasCyclicSeparating`, a `Dense`-span statement about a *set* of operators,
versus `IsCyclicVector`/`IsSeparatingVector` about a `StarSubalgebra`), and
for a ∗-subalgebra the orbit `X ξ` is already a linear subspace, so the two
phrasings coincide.

§2 derives 121II.  `(𝒜₁⊗̄ℬ₁) ∩ (𝒜₂⊗̄ℬ₂) = ((𝒜₁'⊗̄ℬ₁') ∪ (𝒜₂'⊗̄ℬ₂'))□`, and the
von Neumann algebra generated by that union contains every `𝒜ᵢ'⊗1` and every
`1⊗ℬⱼ'`, hence *is* `W*(𝒜₁'∪𝒜₂') ⊗̄ W*(ℬ₁'∪ℬ₂')` — that is
`commutant_inf_eq_vnComm_concreteTensor_wstar`, which needs no commutation
theorem at all, only `concreteTensor_wstar_le` (the normality of `a ↦ a ⊗ 1`).
`vnComm_wstar_union` identifies `W*(𝒜₁'∪𝒜₂')□` as `𝒜₁ ∩ 𝒜₂` from the double
commutant theorem (88VI), and one application of IV.5.9 to the pair
`(W*(𝒜₁'∪𝒜₂'), W*(ℬ₁'∪ℬ₂'))` finishes.

**`Theses.A.Proc.intersection_tensor` (`QuantumLambda.lean:314`) cannot be
proved in place**: `A/Proc/Commutation.lean` imports `QuantumLambda.lean`, so
nothing on the commutation-theorem side can be imported back into it.  What
this file provides instead is `intersection_tensor'`, *literally* the same
statement, and — since a proof of 121II is a proof of
`IntersectionTensorStatement` — the abstract form
`tensorSub_inf` that 125IV consumes.
-/
import Theses.A.Proc.CommutationCyclic
import Theses.A.VN.CommutationTomita

open scoped ComplexOrder ComplexInnerProductSpace CStarAlgebra
open Theses Theses.A.VN Theses.RvD

noncomputable section

namespace Theses.A.Proc

universe u

/-! ## §1. The commutation theorem

`CT_of_cyclicSeparating` discharges `CyclicSeparatingCTStatement`, and
`CT_of_CT_cyclicSeparating` turns that into the general theorem. -/

section Statement

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

variable (X : StarSubalgebra ℂ (H →L[ℂ] H)) (ξ : H) in
/-- The orbit `X ξ = {x ξ : x ∈ X}` of a ∗-subalgebra, which is already a
linear subspace — so the `Dense`-*span* phrasing of cyclicity used by
`HasCyclicSeparating` and the `Dense`-*orbit* phrasing used by
`A/VN/Tomita.lean`'s `IsCyclicVector` agree. -/
def orbitSubmodule : Submodule ℂ H where
  carrier := {y : H | ∃ x ∈ (X : Set (H →L[ℂ] H)), y = x ξ}
  add_mem' := by
    rintro _ _ ⟨a, ha, rfl⟩ ⟨b, hb, rfl⟩
    exact ⟨a + b, add_mem ha hb, by simp⟩
  zero_mem' := ⟨0, zero_mem X, by simp⟩
  smul_mem' := by
    rintro c _ ⟨a, ha, rfl⟩
    exact ⟨c • a, X.smul_mem ha c, by simp⟩

theorem span_orbit (X : StarSubalgebra ℂ (H →L[ℂ] H)) (ξ : H) :
    Submodule.span ℂ {y : H | ∃ x ∈ (X : Set (H →L[ℂ] H)), y = x ξ}
      = orbitSubmodule X ξ :=
  Submodule.span_eq (orbitSubmodule X ξ)

/-- `HasCyclicSeparating` for a ∗-subalgebra is `IsCyclicVector` together with
`IsSeparatingVector`, the shapes `A/VN/Tomita.lean` and hence
`A/VN/CommutationTomita.lean` consume. -/
theorem exists_cyclic_separating_vector {X : StarSubalgebra ℂ (H →L[ℂ] H)}
    (h : HasCyclicSeparating (X : Set (H →L[ℂ] H))) :
    ∃ ξ : H, IsCyclicVector X ξ ∧ IsSeparatingVector X ξ := by
  obtain ⟨ξ, hc, hs⟩ := h
  refine ⟨ξ, ?_, hs⟩
  rw [span_orbit X ξ] at hc
  exact hc

end Statement

/-- **The cyclic-and-separating hypothesis of the reduction is a theorem**:
`A/VN/CommutationTomita.lean`'s `CT_of_cyclicSeparating` proves exactly
`CyclicSeparatingCTStatement`. -/
theorem cyclicSeparatingCTStatement : CyclicSeparatingCTStatement.{u} := by
  intro E F _ _ _ _ _ _ X Y hX hY hXcs hYcs
  obtain ⟨ξ, hcX, hsX⟩ := exists_cyclic_separating_vector hXcs
  obtain ⟨η, hcY, hsY⟩ := exists_cyclic_separating_vector hYcs
  exact CT_of_cyclicSeparating X Y ξ η hX hY hcX hsX hcY hsY

section Main

variable {H K : Type u}
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]

/-- **THE COMMUTATION THEOREM.  Takesaki I, Theorem IV.5.9, unconditional.**

For *arbitrary* von Neumann subalgebras `𝒜 ⊆ B(ℋ)` and `ℬ ⊆ B(𝒦)`,

  `(𝒜 ⊗̄ ℬ)□ = 𝒜□ ⊗̄ ℬ□`

for the concrete tensor product `⊗̄ = concreteTensor` of `QuantumLambda.lean`
and the bundled commutant `□ = vnComm` of `A/Proc/Commutation.lean`.  No
cyclic vector, no separating vector, no σ-finiteness, no type restriction.

This is the theorem `proc.tex:4473` cites to Takesaki — *"Proof. See Corollary
IV.5.10 of [Takesaki1]"* — and hence the single result behind `a.tex:274`'s
"I tailored a thorough treatise of everything that's needed, **including
proofs (except `intersection-tensor-proof`)**": the one point in the whole of
thesis A whose proof is not given.  It is now given, in Lean, from Rieffel–van
Daele's bounded-operator proof of Tomita's theorem
(`A/VN/TomitaAnalytic.lean`) together with the amplify-and-cut reduction
(`A/Proc/CommutationReduction.lean` → `CommutationAmplify.lean` →
`Compression.lean` → `CommutationCyclic.lean`).

`commutation_theorem` below is the same statement with `CT` unfolded. -/
theorem CT_of_isVNSubalgebra {SA : StarSubalgebra ℂ (H →L[ℂ] H)}
    {SB : StarSubalgebra ℂ (K →L[ℂ] K)}
    (hA : IsVNSubalgebra (H →L[ℂ] H) SA) (hB : IsVNSubalgebra (K →L[ℂ] K) SB) :
    CT SA SB :=
  CT_of_CT_cyclicSeparating cyclicSeparatingCTStatement hA hB

/-- **The commutation theorem** (Takesaki I, Thm IV.5.9), with `CT` unfolded:
`(𝒜 ⊗̄ ℬ)□ = 𝒜□ ⊗̄ ℬ□`. -/
theorem commutation_theorem (SA : StarSubalgebra ℂ (H →L[ℂ] H))
    (SB : StarSubalgebra ℂ (K →L[ℂ] K))
    (hA : IsVNSubalgebra (H →L[ℂ] H) SA) (hB : IsVNSubalgebra (K →L[ℂ] K) SB) :
    vnComm (concreteTensor H K SA SB)
      = concreteTensor H K (vnComm SA) (vnComm SB) :=
  CT_of_isVNSubalgebra hA hB

end Main

/-! ## §2. 121II — Takesaki I, Corollary IV.5.10

`(𝒜₁ ⊗̄ ℬ₁) ∩ (𝒜₂ ⊗̄ ℬ₂) = (𝒜₁ ∩ 𝒜₂) ⊗̄ (ℬ₁ ∩ ℬ₂)`. -/

section Intersection

variable {H K : Type u}
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [NormedAddCommGroup K] [InnerProductSpace ℂ K] [CompleteSpace K]

/-- **`W*(𝒜₁□ ∪ 𝒜₂□)□ = 𝒜₁ ∩ 𝒜₂`** for von Neumann subalgebras `𝒜₁, 𝒜₂`:
the double commutant theorem (88VI), in the form
`(𝒜₁ ∩ 𝒜₂)□ = W*(𝒜₁□ ∪ 𝒜₂□)`.  No tensor products are involved. -/
theorem vnComm_wstar_union (S₁ S₂ : StarSubalgebra ℂ (H →L[ℂ] H))
    (h₁ : IsVNSubalgebra (H →L[ℂ] H) S₁) (h₂ : IsVNSubalgebra (H →L[ℂ] H) S₂) :
    vnComm (wstar (H →L[ℂ] H)
        ((vnComm S₁ : Set (H →L[ℂ] H)) ∪ (vnComm S₂ : Set (H →L[ℂ] H))))
      = S₁ ⊓ S₂ := by
  have hsub₁ : vnComm S₁ ≤ wstar (H →L[ℂ] H)
      ((vnComm S₁ : Set (H →L[ℂ] H)) ∪ (vnComm S₂ : Set (H →L[ℂ] H))) :=
    fun _ hx => (isVNSubalgebra_wstar _).2 (Set.mem_union_left _ hx)
  have hsub₂ : vnComm S₂ ≤ wstar (H →L[ℂ] H)
      ((vnComm S₁ : Set (H →L[ℂ] H)) ∪ (vnComm S₂ : Set (H →L[ℂ] H))) :=
    fun _ hx => (isVNSubalgebra_wstar _).2 (Set.mem_union_right _ hx)
  refine le_antisymm (le_inf ?_ ?_) ?_
  · exact (vnComm_antitone hsub₁).trans_eq (vnComm_vnComm S₁ h₁)
  · exact (vnComm_antitone hsub₂).trans_eq (vnComm_vnComm S₂ h₂)
  · refine le_vnComm_comm.mpr (sInf_le ⟨isVNSubalgebra_vnComm _, ?_⟩)
    rintro x (hx | hx)
    · exact vnComm_antitone (inf_le_left : S₁ ⊓ S₂ ≤ S₁) hx
    · exact vnComm_antitone (inf_le_right : S₁ ⊓ S₂ ≤ S₂) hx

/-- **The generated algebra of the union of two concrete tensor products is a
concrete tensor product**, in commutant form:

  `(𝒜₁ ⊗̄ ℬ₁)□ ∩ (𝒜₂ ⊗̄ ℬ₂)□ = (W*(𝒜₁ ∪ 𝒜₂) ⊗̄ W*(ℬ₁ ∪ ℬ₂))□`.

`≥` is monotonicity of `⊗̄`.  For `≤`, the algebra `V` on the left commutes
with every `𝒜ᵢ ⊗ 1` and every `1 ⊗ ℬⱼ` — each of which lies in one of the two
tensor products — so `concreteTensor_wstar_le` (i.e. the normality of
`a ↦ a ⊗ 1`, `CommutationAmplify.lean`) puts the whole of
`W*(𝒜₁ ∪ 𝒜₂) ⊗̄ W*(ℬ₁ ∪ ℬ₂)` inside `V□`.

**No commutation theorem is used here.** -/
theorem vnComm_concreteTensor_inf_vnComm_concreteTensor
    (A₁ A₂ : StarSubalgebra ℂ (H →L[ℂ] H)) (B₁ B₂ : StarSubalgebra ℂ (K →L[ℂ] K)) :
    vnComm (concreteTensor H K A₁ B₁) ⊓ vnComm (concreteTensor H K A₂ B₂)
      = vnComm (concreteTensor H K
          (wstar (H →L[ℂ] H) ((A₁ : Set (H →L[ℂ] H)) ∪ (A₂ : Set (H →L[ℂ] H))))
          (wstar (K →L[ℂ] K) ((B₁ : Set (K →L[ℂ] K)) ∪ (B₂ : Set (K →L[ℂ] K))))) := by
  have hA₁ : A₁ ≤ wstar (H →L[ℂ] H)
      ((A₁ : Set (H →L[ℂ] H)) ∪ (A₂ : Set (H →L[ℂ] H))) :=
    fun _ hx => (isVNSubalgebra_wstar _).2 (Set.mem_union_left _ hx)
  have hA₂ : A₂ ≤ wstar (H →L[ℂ] H)
      ((A₁ : Set (H →L[ℂ] H)) ∪ (A₂ : Set (H →L[ℂ] H))) :=
    fun _ hx => (isVNSubalgebra_wstar _).2 (Set.mem_union_right _ hx)
  have hB₁ : B₁ ≤ wstar (K →L[ℂ] K)
      ((B₁ : Set (K →L[ℂ] K)) ∪ (B₂ : Set (K →L[ℂ] K))) :=
    fun _ hx => (isVNSubalgebra_wstar _).2 (Set.mem_union_left _ hx)
  have hB₂ : B₂ ≤ wstar (K →L[ℂ] K)
      ((B₁ : Set (K →L[ℂ] K)) ∪ (B₂ : Set (K →L[ℂ] K))) :=
    fun _ hx => (isVNSubalgebra_wstar _).2 (Set.mem_union_right _ hx)
  refine le_antisymm ?_ (le_inf (vnComm_antitone (concreteTensor_mono hA₁ hB₁))
    (vnComm_antitone (concreteTensor_mono hA₂ hB₂)))
  set V := vnComm (concreteTensor H K A₁ B₁) ⊓ vnComm (concreteTensor H K A₂ B₂) with hV
  have hle₁ : concreteTensor H K A₁ B₁ ≤ vnComm V :=
    le_vnComm_comm.mp (inf_le_left : V ≤ vnComm (concreteTensor H K A₁ B₁))
  have hle₂ : concreteTensor H K A₂ B₂ ≤ vnComm V :=
    le_vnComm_comm.mp (inf_le_right : V ≤ vnComm (concreteTensor H K A₂ B₂))
  refine le_vnComm_comm.mp (concreteTensor_wstar_le (isVNSubalgebra_vnComm V) ?_ ?_)
  · rintro a (ha | ha)
    · exact hle₁ (opTensor_mem_concreteTensor ha (one_mem B₁))
    · exact hle₂ (opTensor_mem_concreteTensor ha (one_mem B₂))
  · rintro b (hb | hb)
    · exact hle₁ (opTensor_mem_concreteTensor (one_mem A₁) hb)
    · exact hle₂ (opTensor_mem_concreteTensor (one_mem A₂) hb)

/-- **121II** (`intersection-tensor`, `proc.tex:4450`, Proposition; Takesaki I,
Corollary IV.5.10): for von Neumann subalgebras `𝒜₁, 𝒜₂ ⊆ B(ℋ)` and
`ℬ₁, ℬ₂ ⊆ B(𝒦)`,

  `(𝒜₁ ⊗̄ ℬ₁) ∩ (𝒜₂ ⊗̄ ℬ₂) = (𝒜₁ ∩ 𝒜₂) ⊗̄ (ℬ₁ ∩ ℬ₂)`

for the concrete tensor products.

This is *verbatim* the statement of `Theses.A.Proc.intersection_tensor`
(`QuantumLambda.lean:314`), which cannot be proved in place: the commutation
theorem lives above `QuantumLambda.lean` in the import order, since
`A/Proc/Commutation.lean` imports it.

The proof is the one recorded in `docs/COMMUTATION-THEOREM.md` §1: rewrite each
factor as a double commutant using IV.5.9, collapse the intersection of the two
commutants onto the commutant of `W*(𝒜₁□ ∪ 𝒜₂□) ⊗̄ W*(ℬ₁□ ∪ ℬ₂□)`, and apply
IV.5.9 once more, using `(𝒜₁ ∩ 𝒜₂)□ = W*(𝒜₁□ ∪ 𝒜₂□)`. -/
theorem intersection_tensor' (SA₁ SA₂ : StarSubalgebra ℂ (H →L[ℂ] H))
    (SB₁ SB₂ : StarSubalgebra ℂ (K →L[ℂ] K))
    (hA₁ : IsVNSubalgebra (H →L[ℂ] H) SA₁)
    (hA₂ : IsVNSubalgebra (H →L[ℂ] H) SA₂)
    (hB₁ : IsVNSubalgebra (K →L[ℂ] K) SB₁)
    (hB₂ : IsVNSubalgebra (K →L[ℂ] K) SB₂) :
    concreteTensor H K SA₁ SB₁ ⊓ concreteTensor H K SA₂ SB₂ =
      concreteTensor H K (SA₁ ⊓ SA₂) (SB₁ ⊓ SB₂) := by
  -- each factor is the commutant of the tensor product of the commutants
  have hT₁ : concreteTensor H K SA₁ SB₁
      = vnComm (concreteTensor H K (vnComm SA₁) (vnComm SB₁)) := by
    rw [← commutation_theorem _ _ hA₁ hB₁,
      vnComm_vnComm _ (isVNSubalgebra_concreteTensor _ _)]
  have hT₂ : concreteTensor H K SA₂ SB₂
      = vnComm (concreteTensor H K (vnComm SA₂) (vnComm SB₂)) := by
    rw [← commutation_theorem _ _ hA₂ hB₂,
      vnComm_vnComm _ (isVNSubalgebra_concreteTensor _ _)]
  rw [hT₁, hT₂, vnComm_concreteTensor_inf_vnComm_concreteTensor,
    commutation_theorem _ _ (isVNSubalgebra_wstar _).1 (isVNSubalgebra_wstar _).1,
    vnComm_wstar_union SA₁ SA₂ hA₁ hA₂, vnComm_wstar_union SB₁ SB₂ hB₁ hB₂]

/-- 121II, packaged as `QuantumLambda.lean`'s `IntersectionTensorStatement` —
the hypothesis its six downstream consumers were phrased against. -/
theorem intersectionTensorStatement : IntersectionTensorStatement.{u} :=
  fun SA₁ SA₂ SB₁ SB₂ hA₁ hA₂ hB₁ hB₂ =>
    intersection_tensor' SA₁ SA₂ SB₁ SB₂ hA₁ hA₂ hB₁ hB₂

end Intersection

/-- **The abstract form of 121II**, unconditional: for von Neumann subalgebras
`𝒮₁, 𝒮₂ ⊆ 𝒜` and any von Neumann algebra `𝒞`,

  `(𝒮₁ ⊗ 𝒞) ∩ (𝒮₂ ⊗ 𝒞) = (𝒮₁ ∩ 𝒮₂) ⊗ 𝒞`

inside the chosen tensor product `𝒜 ⊗ 𝒞`.  This is
`tensorSub_inf_of_intersectionTensorStatement` with its hypothesis discharged;
it is what 125IV `equaliser_lemma` consumes. -/
theorem tensorSub_inf {𝒜 𝒞 : Type u}
    [CStarAlgebra 𝒜] [PartialOrder 𝒜] [StarOrderedRing 𝒜] [VonNeumannAlgebra 𝒜]
    [CStarAlgebra 𝒞] [PartialOrder 𝒞] [StarOrderedRing 𝒞] [VonNeumannAlgebra 𝒞]
    (S₁ S₂ : StarSubalgebra ℂ 𝒜) (hS₁ : IsVNSubalgebra 𝒜 S₁)
    (hS₂ : IsVNSubalgebra 𝒜 S₂) :
    tensorSub 𝒞 S₁ ⊓ tensorSub 𝒞 S₂ = tensorSub 𝒞 (S₁ ⊓ S₂) :=
  tensorSub_inf_of_intersectionTensorStatement intersectionTensorStatement S₁ S₂ hS₁ hS₂

end Theses.A.Proc
