import Papers.OAP.Basic
import Papers.EJA.Prelim
import Papers.EJA.FilterCorner
import Papers.REC.Effectus
import Papers.REC.Algebras
import Papers.SIG.Prelim
import Papers.SIG.SigmaEffectus
import Papers.SIG.Normalisation
import Papers.SIG.Classification
import Papers.EJA.Appendix
import Papers.SEA.Basic
import Papers.OAP.Yosida
import Papers.EJA.Fundamental
import Papers.OAP.FloorCeiling
import Papers.FDS.DirectSums
import Papers.EJA.Pure
import Papers.EJA.PureRoot
import Papers.SIG.EffectModules
import Papers.OAP.Boolean
import Papers.SEA.Boolean
import Papers.OAP.OUS
import Papers.SIG.WeightModules
import Papers.FDS.WStar
import Papers.OAP.Embedding
import Papers.EJA.Dagger
import Papers.EJA.Final
import Papers.REC.Decompose
import Papers.OAP.Main
import Papers.REC.DecomposeFinite
import Papers.REC.Scalars
import Papers.SIG.Discharge
import Papers.SEA.Discharge
import Papers.SEA.AlmostConvex
import Papers.SIG.Pfn
import Papers.SIG.Finite
import Papers.EJA.Appendix2
import Papers.REC.Tidy
import Papers.REC.Rec92Counter
import Papers.SIG.Convex
import Papers.SEA.PureAConvex
import Papers.EJA.Albert
import Papers.SIG.Examples
import Papers.SEA.Closing
import Papers.SIG.Closing
import Papers.REC.Reconstruction
import Papers.OAP.Closing2
import Papers.SEA.Closing2
import Papers.FDS.Closing2
import Papers.REC.JordanSymmetry
import Papers.REC.SpectralChains
import Papers.REC.JordanFromChains
import Papers.REC.Reconstruction2
import Papers.REC.Monoidal
import Papers.REC.Rec128
import Papers.REC.Resolvent
import Papers.REC.Rec119
import Papers.REC.Rec136Hyps
import Papers.REC.Rec136Hyps2
import Papers.REC.JBPeirce
import Papers.REC.JBCalculus
import Papers.REC.Rec136Native
import Papers.REC.JBMacdonald
import Papers.REC.JBWProj
import Papers.FDS.Linking
import Papers.FDS.Envelope
import Papers.FDS.Bidual
import Papers.FDS.Predual
import Papers.FDS.Predual2
import Papers.FDS.Predual3
import Papers.SEA.JordanSEA
import Papers.SEA.JBSEA
import Papers.SEA.JBWSEA
import Papers.SEA.JBAllSEA
import Papers.SEA.JBCommThm
import Papers.SEA.JBSeqComm

/-
Formalisations of six papers following the theses, by Abraham (Bram)
Westerbaan, Bas Westerbaan, Kenta Cho, Tobias Fritz and John van de Wetering.
Sources and point indexes are in `../papers/`; conventions in `Papers/README.md`.
-/
