/-
Papers/SEA/JBSEA.lean

**SEA 16** (`ex:canonical-sea`, second.tex:475), the Jordan sentence beyond
finite dimension: "any JB-algebra is a convex SEA, while any JBW-algebra is a
convex normal SEA" (`a ∘ b = U_{√a} b`, cited from van de Wetering 2019).

Scope (2026-09-26): the *special* case, proved outright; no named hypotheses.
* `JCAlgebra`: a norm-closed real subspace of `A_sa` (`A` a unital C*-algebra)
  containing `1`, closed under `x ∘ y = ½(xy + yx)` (Hanche-Olsen–Størmer 3.1.2).
  Functional calculus inside `J`: `x ∘ xⁿ = xⁿ⁺¹`, so polynomials in `x` lie in
  `J`, and `√x ∈ J` as it lies in the closed real `*`-algebra generated by `x`
  (`sqrt_mem`).  `U_x y = 2x∘(x∘y) − x²∘y = xyx` (`jU_eq`).  `√x` is the unique
  positive Jordan square root in `J`, and `J`'s positive cone is its cone of
  Jordan squares (`sqrt_spec`, `nonneg_iff_jsq`).
* `jcSEA`, `sea16_jc`, `sea16_jc_intrinsic`: `[0,1]_J` is a convex SEA with
  `a ∘ b = U_{√a} b`; the axioms come from the C*-case (`sqrtConj` lemmas):
  the product commutes iff `ab = ba` in `A`.  `isJB`: `J` is a JB-algebra in
  REC 44's sense (the order-unit norm is the C*-norm, `ousNorm_eq`).
* van de Wetering's commutation theorem, JC case (`opComm_iff`,
  `sea16_jc_commutes_iff`): `a ∘ b = b ∘ a` iff `a`, `b` operator commute in
  `J`.  Operator commutation makes `c = ab − ba` commute with `a`, `b`; then
  `δ = [a,·]` has `δⁿ(bⁿ) = n! cⁿ`, so `n! ‖cⁿ‖ ≤ (2‖a‖‖b‖)ⁿ`; `c` is skew,
  `‖c^{2^k}‖ = ‖c‖^{2^k}`, so `c = 0` (Kleinecke–Shirokov, `der_eq_zero`).
* Normality: `jwNormalSEA`/`sea16_jw` for `J` closed under suprema of directed
  sets in a monotone complete `A`; `sea16_jw_vN` for JW-algebras proper
  (`IsJW`: ultraweakly closed in a von Neumann algebra; suprema are ultraweak
  limits, `supClosed_of_isJW`).  `isJBW`, `isJWAlgebra`: such `J` is a
  JBW-algebra (REC 48) and a JW-algebra (REC 50).
* Abstract special JB(W)-algebras: `SpecialEmbedding` (a unital isometric
  Jordan embedding of a `JBAlgebra` into a C*-algebra) is an order embedding
  (`nonneg_iff`) with closed range (`toJC`); `sea16_special`: `[0,1]_V` is a
  convex SEA with `a ∘ b = 2r(rb) − (rr)b`, `r` the unique positive root of
  `a` in `V`; `sea16_special_normal`: for a JBW-algebra and a normal embedding
  it is a normal SEA (`[0,1]`-suprema are suprema in `V`, `isLUB_of_Icc_sup`).
  Every JC- (JW-) algebra is an instance (`specialEmbedding`, `_normal`).
* Not covered: non-special (exceptional) JB/JBW-algebras of infinite
  dimension; they need Shirshov–Cohn/Macdonald or Hanche-Olsen–Størmer 7.2.7
  with Shultz's `C(X, H₃(𝕆))` (and normality there).  Finite-dimensional
  exceptional ones, the Albert algebra included, are `sea16_eja`.
-/
import Papers.SEA.Closing
import Papers.REC.Reconstruction

set_option linter.unusedSectionVars false
set_option warn.classDefReducibility false

namespace Papers.SEA.JC

open Theses.B.Eff Filter Topology Polynomial

universe u

variable {A : Type u} [CStarAlgebra A]

/-- The special Jordan product `x ∘ y = ½(xy + yx)`. -/
noncomputable def jmul (x y : A) : A := (2⁻¹ : ℝ) • (x * y + y * x)

/-- The quadratic map `U_x y = 2 x∘(x∘y) − x²∘y` of the Jordan product. -/
noncomputable def jU (x y : A) : A := (2 : ℝ) • jmul x (jmul x y) - jmul (jmul x x) y

theorem jmul_comm (x y : A) : jmul x y = jmul y x := by
  unfold jmul; rw [add_comm]

theorem jmul_self (x : A) : jmul x x = x * x := by
  unfold jmul
  rw [← two_smul ℝ (x * x), smul_smul]; norm_num

theorem jmul_of_commute {x y : A} (h : Commute x y) : jmul x y = x * y := by
  unfold jmul
  rw [← h.eq, ← two_smul ℝ (x * y), smul_smul]; norm_num

/-- `U_x y = x y x` for the special Jordan product. -/
theorem jU_eq (x y : A) : jU x y = x * y * x := by
  unfold jU jmul
  simp only [smul_add, mul_add, add_mul, smul_mul_assoc, mul_smul_comm, smul_smul, mul_assoc]
  module

/-- **JC-algebra** (Hanche-Olsen–Størmer, *Jordan operator algebras*, 3.1.2): a
norm-closed real subspace `J` of the self-adjoint part of a unital C*-algebra
`A`, containing `1` and closed under the Jordan product `x ∘ y = ½(xy + yx)`.
(The unit of a unital JC-algebra could be a projection `e ≠ 1`; then `J`
lives in the unital C*-algebra `eAe`, so asking `1 ∈ J` loses nothing, but
that corner reduction is not formalised.) -/
structure JCAlgebra (A : Type u) [CStarAlgebra A] where
  carrier : Submodule ℝ A
  sa : ∀ x ∈ carrier, IsSelfAdjoint x
  one_mem : (1 : A) ∈ carrier
  jmul_mem : ∀ x ∈ carrier, ∀ y ∈ carrier, jmul x y ∈ carrier
  isClosed : IsClosed (carrier : Set A)

namespace JCAlgebra

variable (J : JCAlgebra A)

theorem mul_self_mem {x : A} (hx : x ∈ J.carrier) : x * x ∈ J.carrier := by
  rw [← jmul_self]; exact J.jmul_mem x hx x hx

theorem jU_mem {x y : A} (hx : x ∈ J.carrier) (hy : y ∈ J.carrier) : x * y * x ∈ J.carrier := by
  rw [← jU_eq]
  exact J.carrier.sub_mem (J.carrier.smul_mem _ (J.jmul_mem _ hx _ (J.jmul_mem _ hx _ hy)))
    (J.jmul_mem _ (J.jmul_mem _ hx _ hx) _ hy)

theorem pow_mem {x : A} (hx : x ∈ J.carrier) (n : ℕ) : x ^ n ∈ J.carrier := by
  induction n with
  | zero => rw [pow_zero]; exact J.one_mem
  | succ n ih =>
    have h := J.jmul_mem x hx _ ih
    rwa [jmul_of_commute (Commute.self_pow x n), ← pow_succ'] at h

theorem aeval_mem {x : A} (hx : x ∈ J.carrier) (p : ℝ[X]) : aeval x p ∈ J.carrier := by
  induction p using Polynomial.induction_on' with
  | add p q hp hq => rw [map_add]; exact J.carrier.add_mem hp hq
  | monomial n r =>
    rw [aeval_monomial, ← Algebra.smul_def]
    exact J.carrier.smul_mem r (J.pow_mem hx n)

/-- The closed real `*`-algebra generated by `x ∈ J` lies in `J`. -/
theorem elemental_le {x : A} (hx : x ∈ J.carrier) :
    (StarAlgebra.elemental ℝ x : Set A) ⊆ J.carrier := by
  have hsa : star x = x := J.sa x hx
  have h1 : ((StarAlgebra.adjoin ℝ ({x} : Set A)) : Set A) ⊆ J.carrier := by
    intro y hy
    have hy' : y ∈ (StarAlgebra.adjoin ℝ ({x} : Set A)).toSubalgebra := hy
    rw [StarAlgebra.adjoin_toSubalgebra, Set.star_singleton, hsa, Set.union_self,
      Algebra.adjoin_singleton_eq_range_aeval] at hy'
    obtain ⟨p, rfl⟩ := hy'
    exact J.aeval_mem hx p
  unfold StarAlgebra.elemental
  rw [StarSubalgebra.topologicalClosure_coe]
  exact closure_minimal h1 J.isClosed

variable [PartialOrder A] [StarOrderedRing A]

/-- **Square roots stay in `J`**: `√x ∈ J` for `0 ≤ x ∈ J`. -/
theorem sqrt_mem {x : A} (hx : x ∈ J.carrier) (hx0 : 0 ≤ x) : CFC.sqrt x ∈ J.carrier := by
  rw [CFC.sqrt_eq_real_sqrt x hx0, cfcₙ_eq_cfc (hf0 := by simp)]
  exact J.elemental_le hx (cfc_mem_elemental (𝕜 := ℝ) Real.sqrt x)

end JCAlgebra

/-! ## `[0,1]_J` as a convex SEA -/

section SEA

variable [PartialOrder A] [StarOrderedRing A] (J : JCAlgebra A)

theorem real_smul_eq (r : ℝ) (x : A) : r • x = (r : ℂ) • x :=
  RCLike.real_smul_eq_coe_smul (K := ℂ) r x

namespace JCAlgebra

/-- The unit of `J`. -/
def one : J.carrier := ⟨1, J.one_mem⟩

/-- `J` is an ordered real vector space (the order of `A`). -/
instance : IsOrderedAddMonoid J.carrier where
  add_le_add_left x y h z := by
    show (x : A) + z ≤ y + z
    exact add_le_add (show (x : A) ≤ y from h) le_rfl

instance : PosSMulMono ℝ J.carrier := ⟨fun r hr x y hxy => by
  show r • (x : A) ≤ r • (y : A)
  rw [real_smul_eq, real_smul_eq]
  exact rsmul_mono' hr (show (x : A) ≤ y from hxy)⟩

instance : SMulPosMono ℝ J.carrier := ⟨fun x hx r t hrt => by
  show r • (x : A) ≤ t • (x : A)
  rw [real_smul_eq, real_smul_eq]
  exact rsmul_le_rsmul' hrt (show (0 : A) ≤ x from hx)⟩

theorem zero_le_one' : (0 : J.carrier) ≤ J.one := show (0 : A) ≤ 1 from zero_le_one

/-- `[0,1]_J` with the effect algebra structure of SEA 4 (`u = 1`). -/
@[instance_reducible] noncomputable def jcEA : EffectAlgebra (Set.Icc (0 : J.carrier) J.one) :=
  orderIntervalEffectAlgebra J.carrier J.one J.zero_le_one'

variable {J}

/-- The underlying element of `A` of an element of `[0,1]_J`. -/
abbrev toA (a : Set.Icc (0 : J.carrier) J.one) : A := a.1.1

theorem toA_nonneg (a : Set.Icc (0 : J.carrier) J.one) : 0 ≤ toA a := a.2.1

theorem toA_le_one (a : Set.Icc (0 : J.carrier) J.one) : toA a ≤ 1 := a.2.2

theorem toA_mem (a : Set.Icc (0 : J.carrier) J.one) : toA a ∈ J.carrier := a.1.2

theorem ext_toA {a b : Set.Icc (0 : J.carrier) J.one} (h : toA a = toA b) : a = b :=
  Subtype.ext (Subtype.ext h)

variable (J) in
/-- The sequential product on `[0,1]_J`: `a ∘ b = √a b √a`, which is
`U_{√a} b` for the Jordan product of `J` (`seq_eq_jU`). -/
noncomputable def seq (a b : Set.Icc (0 : J.carrier) J.one) : Set.Icc (0 : J.carrier) J.one :=
  ⟨⟨sqrtConj (toA a) (toA b), J.jU_mem (J.sqrt_mem (toA_mem a) (toA_nonneg a)) (toA_mem b)⟩,
    sqrtConj_nonneg (toA_nonneg b), sqrtConj_le_one (toA_nonneg a) (toA_le_one a) (toA_le_one b)⟩

theorem toA_seq (a b : Set.Icc (0 : J.carrier) J.one) :
    toA (seq J a b) = sqrtConj (toA a) (toA b) := rfl

theorem seq_comm_iff {a b : Set.Icc (0 : J.carrier) J.one} :
    seq J a b = seq J b a ↔ Commute (toA a) (toA b) := by
  constructor
  · intro h
    exact commute_of_sqrtConj_eq (toA_nonneg a) (toA_nonneg b)
      (congrArg (fun x => toA x) h)
  · intro h
    exact ext_toA (sqrtConj_comm_of_commute (toA_nonneg a) (toA_nonneg b) h)

variable (J) in
/-- **SEA 16**, Jordan sentence, JC case: `[0,1]_J` is a SEA with
`a ∘ b = U_{√a} b`. -/
@[instance_reducible] noncomputable def jcSEA : @SEAlgebra (Set.Icc (0 : J.carrier) J.one) J.jcEA := by
  letI := J.jcEA
  exact
  { seq := seq J
    seq_add := fun c {a b} h => by
      have hab : toA a + toA b ≤ 1 := h
      refine ⟨?_, ext_toA ?_⟩
      · show sqrtConj (toA c) (toA a) + sqrtConj (toA c) (toA b) ≤ 1
        rw [sqrtConj_add]; exact sqrtConj_le_one (toA_nonneg c) (toA_le_one c) hab
      · exact sqrtConj_add (toA a) (toA b) (toA c)
    one_seq := fun a => ext_toA (sqrtConj_one_left (toA a))
    seq_zero_comm := fun a b hab =>
      ext_toA (sqrtConj_eq_zero_comm (toA_nonneg a) (toA_nonneg b)
        (congrArg (fun x => toA x) hab))
    seq_comm_orth := fun {a b} h => by
      have hcomm := seq_comm_iff.mp h
      have hb' : (0 : A) ≤ 1 - toA b := sub_nonneg.mpr (toA_le_one b)
      have hc2 : Commute (toA a) (1 - toA b) := (Commute.one_right _).sub_right hcomm
      exact ext_toA (sqrtConj_comm_of_commute (toA_nonneg a) hb' hc2)
    seq_comm_assoc := fun {a b} h c =>
      ext_toA (sqrtConj_assoc_of_commute (toA_nonneg a) (toA_nonneg b)
        (seq_comm_iff.mp h) (toA c))
    seq_comm_compat := fun {a b c} h hca hcb => by
      have h1 := seq_comm_iff.mp hca
      have h2 := seq_comm_iff.mp hcb
      have hsa : Commute (toA c) (CFC.sqrt (toA a)) := (commute_sqrt h1.symm).symm
      have h3 : Commute (toA c) (sqrtConj (toA a) (toA b)) := (hsa.mul_right h2).mul_right hsa
      have h4 : Commute (toA c) (toA a + toA b) := h1.add_right h2
      exact ⟨ext_toA (sqrtConj_comm_of_commute (toA_nonneg c) (sqrtConj_nonneg (toA_nonneg b)) h3),
        ext_toA (sqrtConj_comm_of_commute (toA_nonneg c) (add_nonneg (toA_nonneg a)
          (toA_nonneg b)) h4)⟩
    seq_comm_seq := fun {a b c} hca hcb => by
      have h1 := seq_comm_iff.mp hca
      have h2 := seq_comm_iff.mp hcb
      have hsa : Commute (toA c) (CFC.sqrt (toA a)) := (commute_sqrt h1.symm).symm
      have h3 : Commute (toA c) (sqrtConj (toA a) (toA b)) := (hsa.mul_right h2).mul_right hsa
      exact ext_toA (sqrtConj_comm_of_commute (toA_nonneg c) (sqrtConj_nonneg (toA_nonneg b)) h3) }

/-- The product of `jcSEA` is `U_{√a} b` for the Jordan product of `J`, and
`√a ∈ J`. -/
theorem seq_eq_jU (a b : Set.Icc (0 : J.carrier) J.one) :
    toA (seq J a b) = jU (CFC.sqrt (toA a)) (toA b) ∧ CFC.sqrt (toA a) ∈ J.carrier := by
  refine ⟨?_, J.sqrt_mem (toA_mem a) (toA_nonneg a)⟩
  rw [toA_seq, jU_eq]; rfl

variable (J) in
/-- The le relation of the effect algebra `[0,1]_J` is the order of `A`. -/
theorem le_iff (x y : Set.Icc (0 : J.carrier) J.one) :
    @PCM.le _ J.jcEA.toPCM x y ↔ toA x ≤ toA y :=
  interval_le_iff J.one J.zero_le_one' x y

end JCAlgebra

/-! ### The square root and the positive cone, Jordan-intrinsically -/

namespace JCAlgebra

variable {J}

/-- In `J`, `√x` is the unique positive `y ∈ J` with `y ∘ y = x`. -/
theorem sqrt_spec {x : A} (hx : x ∈ J.carrier) (hx0 : 0 ≤ x) :
    CFC.sqrt x ∈ J.carrier ∧ 0 ≤ CFC.sqrt x ∧ jmul (CFC.sqrt x) (CFC.sqrt x) = x ∧
      ∀ y ∈ J.carrier, 0 ≤ y → jmul y y = x → y = CFC.sqrt x := by
  refine ⟨J.sqrt_mem hx hx0, CFC.sqrt_nonneg x, ?_, fun y _ hy0 hyy => ?_⟩
  · rw [jmul_self]; exact CFC.sqrt_mul_sqrt_self x hx0
  · rw [jmul_self] at hyy
    rw [← hyy]; exact (CFC.sqrt_mul_self y hy0).symm

/-- The positive cone of `J` (the order of `A`) is the cone of Jordan squares
`x ∘ x`, `x ∈ J`, as for a JB-algebra. -/
theorem nonneg_iff_jsq {x : A} (hx : x ∈ J.carrier) :
    0 ≤ x ↔ ∃ y ∈ J.carrier, x = jmul y y := by
  constructor
  · intro hx0
    obtain ⟨h1, -, h2, -⟩ := sqrt_spec hx hx0
    exact ⟨_, h1, h2.symm⟩
  · rintro ⟨y, hy, rfl⟩
    rw [jmul_self]
    have h := star_mul_self_nonneg y
    rwa [show star y = y from J.sa y hy] at h

end JCAlgebra

/-- **SEA 16** (`ex:canonical-sea`, second.tex:475, Example), the sentence
"any JB-algebra is a convex SEA", for **JC-algebras** (norm-closed unital
Jordan subalgebras `J` of a C*-algebra's self-adjoint part): `[0,1]_J` is a
convex effect algebra (SEA 8) and a SEA (`jcSEA`) whose product is the Jordan
`a ∘ b = U_{√a} b = 2 √a∘(√a∘b) − a∘b`, with `√a ∈ J`. -/
theorem sea16_jc :
    @IsConvex _ J.jcEA ∧
    ∀ a b : Set.Icc (0 : J.carrier) J.one,
      JCAlgebra.toA (@SequentialEffectAlgebra.seq _ J.jcEA
        (J.jcSEA).toSequentialEffectAlgebra a b) =
        jU (CFC.sqrt (JCAlgebra.toA a)) (JCAlgebra.toA b) ∧
      CFC.sqrt (JCAlgebra.toA a) ∈ J.carrier :=
  ⟨sea9_interval_convex J.carrier J.one J.zero_le_one', fun a b => JCAlgebra.seq_eq_jU a b⟩

end SEA

/-! ## JW-algebras: `[0,1]_J` is a normal SEA -/

section JW

variable [PartialOrder A] [StarOrderedRing A]

namespace JCAlgebra

variable (J : JCAlgebra A)

/-- `J` is closed under least upper bounds (in `A`) of its non-empty directed
subsets.  With `A` monotone complete (`BoundedDirectedComplete`), this makes
`J` a **JW-algebra** in the monotone sense: an ultraweakly closed Jordan
subalgebra of a von Neumann algebra is closed under these suprema (they are
σ-weak limits, vn.tex 42I), so every JW-algebra of Hanche-Olsen–Størmer 4.1.1
is covered. -/
def SupClosed : Prop :=
  ∀ D : Set A, D ⊆ J.carrier → D.Nonempty → DirectedOn (· ≤ ·) D → ∀ s, IsLUB D s → s ∈ J.carrier

variable {J}

/-- The self-adjoint elements underlying a subset of `[0,1]_J`. -/
def saImg (S : Set (Set.Icc (0 : J.carrier) J.one)) : Set (selfAdjoint A) :=
  (fun x => (⟨toA x, IsSelfAdjoint.of_nonneg (toA_nonneg x)⟩ : selfAdjoint A)) '' S

theorem saImg_props {S : Set (Set.Icc (0 : J.carrier) J.one)} (hS : @EDirected _ J.jcEA S) :
    (saImg S).Nonempty ∧ DirectedOn (· ≤ ·) (saImg S) ∧ BddAbove (saImg S) := by
  let _ := J.jcEA
  obtain ⟨⟨x0, hx0⟩, hdir⟩ := hS
  refine ⟨⟨_, x0, hx0, rfl⟩, ?_, ⟨⟨1, IsSelfAdjoint.one A⟩, by
    rintro _ ⟨a, _, rfl⟩; exact toA_le_one a⟩⟩
  rintro _ ⟨a, ha, rfl⟩ _ ⟨b, hb, rfl⟩
  obtain ⟨c, hc, hac, hbc⟩ := hdir a ha b hb
  exact ⟨_, ⟨c, hc, rfl⟩, (le_iff J a c).mp hac, (le_iff J b c).mp hbc⟩

/-- The supremum of a directed subset of `[0,1]_J`: the least upper bound in
`A` of the underlying set, which lies in `J`. -/
theorem sup_data (hbdc : BoundedDirectedComplete A) (hJ : J.SupClosed)
    {S : Set (Set.Icc (0 : J.carrier) J.one)} (hS : @EDirected _ J.jcEA S) :
    ∃ s : selfAdjoint A, IsLUB (saImg S) s ∧ ∃ x : Set.Icc (0 : J.carrier) J.one,
      toA x = s ∧ @EIsSup _ J.jcEA S x ∧
        ∀ y, @EIsSup _ J.jcEA S y → toA y = s := by
  let _ := J.jcEA
  obtain ⟨hne, hdir, hbdd⟩ := saImg_props hS
  obtain ⟨s, hs⟩ := hbdc _ hne hdir hbdd
  have hsA := Papers.SEA.isLUB_coe_of_isLUB hne hs
  have hsJ : (s : A) ∈ J.carrier := by
    refine hJ _ ?_ (hne.image _) ?_ _ hsA
    · rintro _ ⟨_, ⟨a, _, rfl⟩, rfl⟩; exact toA_mem a
    · rintro _ ⟨d, hd, rfl⟩ _ ⟨e, he, rfl⟩
      obtain ⟨f, hf, h1, h2⟩ := hdir d hd e he
      exact ⟨f, ⟨f, hf, rfl⟩, h1, h2⟩
  obtain ⟨a0, ha0⟩ := hS.1
  have hs0 : (0 : A) ≤ s := le_trans (toA_nonneg a0) (hs.1 ⟨a0, ha0, rfl⟩)
  have hs1 : (s : A) ≤ 1 := hs.2 (show (⟨1, IsSelfAdjoint.one A⟩ : selfAdjoint A) ∈
    upperBounds (saImg S) by rintro _ ⟨a, _, rfl⟩; exact toA_le_one a)
  let x : Set.Icc (0 : J.carrier) J.one := ⟨⟨s, hsJ⟩, hs0, hs1⟩
  have hub : ∀ y : Set.Icc (0 : J.carrier) J.one, (∀ a ∈ S, a ≼ y) → (s : A) ≤ toA y := by
    intro y hy
    exact hs.2 (show (⟨toA y, IsSelfAdjoint.of_nonneg (toA_nonneg y)⟩ : selfAdjoint A) ∈
      upperBounds (saImg S) by
        rintro _ ⟨a, ha, rfl⟩; exact (le_iff J a y).mp (hy a ha))
  have hx : EIsSup S x := ⟨fun a ha => (le_iff J a x).mpr (hs.1 ⟨a, ha, rfl⟩),
    fun y hy => (le_iff J x y).mpr (hub y hy)⟩
  refine ⟨s, hs, x, rfl, hx, fun y hy => ?_⟩
  have := hy.unique hx
  rw [this]

variable (J) in
/-- **SEA 16**, Jordan sentence, JW case: for a monotone complete C*-algebra
`A` (e.g. a von Neumann algebra) and a JC-algebra `J ⊆ A_sa` closed under
suprema of directed subsets, `[0,1]_J` is a *normal* SEA with the product of
`jcSEA`.  Suprema in `[0,1]_J` are those of `A` (`sup_data`); the product half
of S6 is `conj_isLUB_of_nonneg`, the commutation half `commute_of_isLUB`
(Closing.lean). -/
@[instance_reducible] noncomputable def jwNormalSEA (hbdc : BoundedDirectedComplete A)
    (hJ : J.SupClosed) : @NormalSEA (Set.Icc (0 : J.carrier) J.one) J.jcEA := by
  letI := J.jcEA
  letI := J.jcSEA
  have hnorm : ∀ z : Set.Icc (0 : J.carrier) J.one, ‖toA z‖ ≤ ‖(1 : A)‖ := fun z =>
    CStarAlgebra.norm_le_norm_of_nonneg_of_le (toA_nonneg z) (toA_le_one z)
  exact
  { J.jcSEA with
    directedComplete := fun S hS => by
      obtain ⟨_, _, x, _, hx, _⟩ := sup_data hbdc hJ hS
      exact ⟨x, hx⟩
    seq_sup := by
      intro a S x hS hx
      obtain ⟨hne, -, -⟩ := saImg_props hS
      obtain ⟨s, hs, -, -, -, huniq⟩ := sup_data hbdc hJ hS
      have hxs := huniq x hx
      have hL := conj_isLUB_of_nonneg (CFC.sqrt_nonneg (toA a)) hne (M := ‖(1 : A)‖)
        (by rintro _ ⟨z, _, rfl⟩; exact hnorm z) hs (by rw [← hxs]; exact hnorm x)
      rw [← hxs] at hL
      refine ⟨?_, fun y hy => (le_iff J _ _).mpr (hL.2 ?_)⟩
      · rintro _ ⟨s, hs, rfl⟩
        exact (le_iff J _ _).mpr (hL.1 ⟨_, ⟨s, hs, rfl⟩, rfl⟩)
      · rintro _ ⟨d, ⟨s, hs, rfl⟩, rfl⟩
        exact (le_iff J _ _).mp (hy _ ⟨s, hs, rfl⟩)
    comm_sup := by
      intro a S x hS hx hcomm
      obtain ⟨hne, -, -⟩ := saImg_props hS
      obtain ⟨s, hs, -, -, -, huniq⟩ := sup_data hbdc hJ hS
      have hc : ∀ d ∈ saImg S, Commute (toA a) (d : A) := by
        rintro _ ⟨s, hs, rfl⟩
        exact seq_comm_iff.mp (hcomm s hs)
      have := commute_of_isLUB (toA_nonneg a) (toA_le_one a) hne hs hc
      rw [← huniq x hx] at this
      exact seq_comm_iff.mpr this }

end JCAlgebra

/-- **SEA 16** (`ex:canonical-sea`, second.tex:475, Example), the sentence
"any JBW-algebra is a convex normal SEA", for **JW-algebras** (in the monotone
sense of `JCAlgebra.SupClosed`, inside a monotone complete C*-algebra such as
a von Neumann algebra): `[0,1]_J` is convex and a normal SEA with
`a ∘ b = U_{√a} b`. -/
theorem sea16_jw (J : JCAlgebra A) (hbdc : BoundedDirectedComplete A) (hJ : J.SupClosed) :
    @IsConvex _ J.jcEA ∧
    ∀ a b : Set.Icc (0 : J.carrier) J.one,
      JCAlgebra.toA (@SequentialEffectAlgebra.seq _ J.jcEA
        (J.jwNormalSEA hbdc hJ).toSEAlgebra.toSequentialEffectAlgebra a b) =
        jU (CFC.sqrt (JCAlgebra.toA a)) (JCAlgebra.toA b) :=
  ⟨(sea16_jc J).1, fun a b => (JCAlgebra.seq_eq_jU a b).1⟩

/-! ### Ultraweakly closed JC-algebras of von Neumann algebras -/

open scoped ComplexOrder in
/-- Along a non-empty directed set `D` of self-adjoint elements of a von
Neumann algebra with least upper bound `s`, `ω d → ω s` for every
np-functional `ω` (normality, vn.tex 42II). -/
theorem np_tendsto_of_isLUB [Theses.VonNeumannAlgebra A] (ω : Theses.NPFunctional A)
    {D : Set (selfAdjoint A)} (hne : D.Nonempty) (hdir : DirectedOn (· ≤ ·) D)
    {s : selfAdjoint A} (hs : IsLUB D s) [IsDirectedOrder D] :
    Tendsto (fun d : D => ω (d : A)) atTop (𝓝 (ω s)) := by
  have hN := ω.preservesDirSups' D s hne hdir hs
  have hle : ∀ d ∈ D, ω (d : A) ≤ ω s := fun d hd => hN.1 ⟨d, hd, rfl⟩
  have hmono : ∀ d ∈ D, ∀ d' ∈ D, d ≤ d' → ω (d : A) ≤ ω (d' : A) := fun d _ d' _ h =>
    ω.toPositiveLinearMap.mono (show (d : A) ≤ d' from h)
  have key : ∀ d ∈ D, dist (ω (d : A)) (ω s) = (ω s).re - (ω (d : A)).re := by
    intro d hd
    have h4 := hle d hd
    rw [Complex.le_def] at h4
    rw [dist_eq_norm]
    have : ω (d : A) - ω s = (((ω (d : A)).re - (ω s).re : ℝ) : ℂ) := by
      apply Complex.ext <;> simp [h4.2]
    rw [this, Complex.norm_real, Real.norm_eq_abs, abs_of_nonpos (by linarith [h4.1])]
    ring
  rw [Metric.tendsto_nhds]
  intro ε hε
  obtain ⟨d0, hd0, hd0ε⟩ : ∃ d0 ∈ D, (ω s).re - (ω (d0 : A)).re < ε := by
    by_contra hcon
    push Not at hcon
    have hub : (ω s - (ε : ℂ)) ∈ upperBounds ((fun d : selfAdjoint A => ω (d : A)) '' D) := by
      rintro _ ⟨d, hd, rfl⟩
      have h1 := hle d hd
      rw [Complex.le_def] at h1 ⊢
      refine ⟨?_, ?_⟩
      · simp only [Complex.sub_re, Complex.ofReal_re]; linarith [hcon d hd]
      · simp only [Complex.sub_im, Complex.ofReal_im, sub_zero]; exact h1.2
    have := hN.2 hub
    rw [Complex.le_def] at this
    simp only [Complex.sub_re, Complex.ofReal_re] at this
    have h5 : (ω s).re ≤ (ω s).re - ε := this.1
    linarith
  filter_upwards [Filter.eventually_ge_atTop (⟨d0, hd0⟩ : D)] with d hd
  rw [key d d.2]
  have := hmono d0 hd0 d d.2 hd
  rw [Complex.le_def] at this
  linarith [this.1]

omit [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A] in
theorem mem_of_tendsto_top {X ι : Type*} (t : TopologicalSpace X) {s : Set X}
    (hs : IsClosed[t] s) {f : ι → X} {l : Filter ι} [NeBot l] {x : X}
    (hf : Tendsto f l (@nhds X t x)) (h : ∀ i, f i ∈ s) : x ∈ s := by
  let _ := t
  exact hs.mem_of_tendsto hf (Filter.Eventually.of_forall h)

namespace JCAlgebra

/-- A JC-algebra `J` in a von Neumann algebra `A` is a **JW-algebra**
(Hanche-Olsen–Størmer 4.1.1, REC 50) when it is closed for the ultraweak
topology of `A` (thesis A's `ultraweak`, vn.tex 42III). -/
def IsJW [Theses.VonNeumannAlgebra A] (J : JCAlgebra A) : Prop :=
  IsClosed[Theses.A.VN.ultraweak A] (J.carrier : Set A)

/-- An ultraweakly closed JC-algebra is closed under suprema of directed
subsets: the supremum is the ultraweak limit of the directed net. -/
theorem supClosed_of_isJW [Theses.VonNeumannAlgebra A] {J : JCAlgebra A} (hJ : J.IsJW) :
    J.SupClosed := by
  intro D hDJ hne hdir s hs
  have hDsa : ∀ d ∈ D, IsSelfAdjoint d := fun d hd => J.sa d (hDJ hd)
  have hssa : IsSelfAdjoint s := isSelfAdjoint_of_ub hDsa hne hs.1
  let D' : Set (selfAdjoint A) := {d | (d : A) ∈ D}
  have hne' : D'.Nonempty := by
    obtain ⟨d, hd⟩ := hne; exact ⟨⟨d, hDsa d hd⟩, hd⟩
  have hdir' : DirectedOn (· ≤ ·) D' := by
    intro x hx y hy
    obtain ⟨z, hz, h1, h2⟩ := hdir _ hx _ hy
    exact ⟨⟨z, hDsa z hz⟩, hz, h1, h2⟩
  have hs' : IsLUB D' ⟨s, hssa⟩ :=
    ⟨fun d hd => hs.1 hd, fun t ht => hs.2 fun d hd => ht (show (⟨d, hDsa d hd⟩ : selfAdjoint A)
      ∈ D' from hd)⟩
  have : Nonempty D' := hne'.to_subtype
  have : IsDirectedOrder D' := ⟨fun i j => by
    obtain ⟨k, hk, hik, hjk⟩ := hdir' i i.2 j j.2
    exact ⟨⟨k, hk⟩, hik, hjk⟩⟩
  have ht : Tendsto (fun d : D' => ((d : selfAdjoint A) : A)) atTop
      (@nhds A (Theses.A.VN.ultraweak A) s) := by
    unfold Theses.A.VN.ultraweak
    rw [nhds_iInf, tendsto_iInf]
    intro ω
    rw [nhds_induced, tendsto_comap_iff]
    exact np_tendsto_of_isLUB ω hne' hdir' hs'
  exact mem_of_tendsto_top _ hJ ht fun d => hDJ d.2

end JCAlgebra

/-- **SEA 16**, JBW clause, for JW-algebras in the standard sense: if `J` is an
ultraweakly closed JC-algebra in a von Neumann algebra `A`, `[0,1]_J` is a
convex normal SEA with `a ∘ b = U_{√a} b`. -/
theorem sea16_jw_vN [Theses.VonNeumannAlgebra A] (J : JCAlgebra A) (hJ : J.IsJW) :
    ∃ N : @NormalSEA (Set.Icc (0 : J.carrier) J.one) J.jcEA,
      @IsConvex _ J.jcEA ∧
      ∀ a b : Set.Icc (0 : J.carrier) J.one,
        JCAlgebra.toA (@SequentialEffectAlgebra.seq _ J.jcEA
          N.toSEAlgebra.toSequentialEffectAlgebra a b) =
          jU (CFC.sqrt (JCAlgebra.toA a)) (JCAlgebra.toA b) :=
  ⟨J.jwNormalSEA vonNeumann_boundedDirectedComplete (JCAlgebra.supClosed_of_isJW hJ),
    sea16_jw J _ _⟩

end JW

/-! ## The commutation theorem in the JC case

van de Wetering's theorem: `a ∘ b = b ∘ a` iff `a`, `b` operator commute.  In
a JC-algebra operator commutation (`a∘(b∘x) = b∘(a∘x)` for all `x ∈ J`) is
equivalent to `ab = ba` in `A`; the hard direction is the Kleinecke–Shirokov
argument below. -/

section Commutation

/-- The inner derivation `δ_a x = ax − xa`. -/
def der (a x : A) : A := a * x - x * a

theorem der_mul (a x y : A) : der a (x * y) = der a x * y + x * der a y := by
  unfold der; noncomm_ring

theorem der_nsmul (a x : A) (m : ℕ) : der a (m • x) = m • der a x := by
  unfold der; rw [mul_smul_comm, smul_mul_assoc, smul_sub]

theorem norm_der_le (a x : A) : ‖der a x‖ ≤ 2 * ‖a‖ * ‖x‖ := by
  unfold der
  calc ‖a * x - x * a‖ ≤ ‖a * x‖ + ‖x * a‖ := norm_sub_le _ _
    _ ≤ ‖a‖ * ‖x‖ + ‖x‖ * ‖a‖ := add_le_add (norm_mul_le _ _) (norm_mul_le _ _)
    _ = 2 * ‖a‖ * ‖x‖ := by ring

theorem norm_der_iterate_le (a x : A) (k : ℕ) : ‖(der a)^[k] x‖ ≤ (2 * ‖a‖) ^ k * ‖x‖ := by
  induction k with
  | zero => simp
  | succ k ih =>
    rw [Function.iterate_succ_apply']
    calc ‖der a ((der a)^[k] x)‖ ≤ 2 * ‖a‖ * ‖(der a)^[k] x‖ := norm_der_le _ _
      _ ≤ 2 * ‖a‖ * ((2 * ‖a‖) ^ k * ‖x‖) :=
          mul_le_mul_of_nonneg_left ih (by positivity)
      _ = (2 * ‖a‖) ^ (k + 1) * ‖x‖ := by ring

variable {a b : A}

theorem der_pow (hcb : Commute (der a b) b) (m : ℕ) :
    der a (b ^ (m + 1)) = (m + 1) • (der a b * b ^ m) := by
  induction m with
  | zero => simp
  | succ m ih =>
    rw [pow_succ b (m + 1), der_mul, ih, smul_mul_assoc, mul_assoc, ← pow_succ,
      ← ((hcb.pow_right (m + 1)).eq)]
    simp only [succ_nsmul]

theorem der_cpow_mul (hca : Commute (der a b) a) (j : ℕ) (y : A) :
    der a ((der a b) ^ j * y) = (der a b) ^ j * der a y := by
  have h := (hca.pow_left j).eq
  unfold der at h ⊢
  rw [mul_sub, ← mul_assoc, ← h, mul_assoc, mul_assoc]

/-- `δ^k(bⁿ) = n(n−1)⋯(n−k+1) c^k b^{n−k}` for `c = δ b` commuting with `a`
and `b`. -/
theorem der_iterate_pow (hca : Commute (der a b) a) (hcb : Commute (der a b) b) (n : ℕ) :
    ∀ k ≤ n, (der a)^[k] (b ^ n) = n.descFactorial k • ((der a b) ^ k * b ^ (n - k)) := by
  intro k
  induction k with
  | zero => intro _; simp
  | succ k ih =>
    intro hk
    rw [Function.iterate_succ_apply', ih (by omega), der_nsmul, der_cpow_mul hca]
    obtain ⟨m, hm⟩ : ∃ m, n - k = m + 1 := ⟨n - k - 1, by omega⟩
    rw [hm, der_pow hcb, show n - (k + 1) = m by omega, Nat.descFactorial_succ,
      show n - k = m + 1 from hm, mul_smul_comm, smul_smul, ← mul_assoc, ← pow_succ, mul_comm]

/-- **Kleinecke–Shirokov, the case used**: if `a, b` are self-adjoint and
`c = ab − ba` commutes with `a` and `b`, then `c = 0`. -/
theorem der_eq_zero (ha : IsSelfAdjoint a) (hb : IsSelfAdjoint b) (hca : Commute (der a b) a)
    (hcb : Commute (der a b) b) : der a b = 0 := by
  set c := der a b with hc
  -- `n! ‖cⁿ‖ ≤ (2‖a‖‖b‖)ⁿ`
  have hbound : ∀ n, 0 < n → (n.factorial : ℝ) * ‖c ^ n‖ ≤ (2 * ‖a‖ * ‖b‖) ^ n := by
    intro n hn
    have h1 := norm_der_iterate_le a (b ^ n) n
    rw [der_iterate_pow hca hcb n n le_rfl, Nat.descFactorial_self, Nat.sub_self, pow_zero,
      mul_one, ← Nat.cast_smul_eq_nsmul ℝ, norm_smul, Real.norm_natCast] at h1
    calc (n.factorial : ℝ) * ‖c ^ n‖ ≤ (2 * ‖a‖) ^ n * ‖b ^ n‖ := h1
      _ ≤ (2 * ‖a‖) ^ n * ‖b‖ ^ n :=
          mul_le_mul_of_nonneg_left (norm_pow_le' b hn) (by positivity)
      _ = (2 * ‖a‖ * ‖b‖) ^ n := by rw [mul_pow (2 * ‖a‖)]
  -- `c` is skew, so `c²` is self-adjoint and `‖c^{2^{k+1}}‖ = ‖c‖^{2^{k+1}}`
  have hstar : star c = -c := by
    rw [hc]; unfold der
    rw [star_sub, star_mul, star_mul, ha.star_eq, hb.star_eq, neg_sub]
  have hs : IsSelfAdjoint (c * c) := by
    show star (c * c) = c * c
    rw [star_mul, hstar, neg_mul_neg]
  have hcc : ‖c * c‖ = ‖c‖ ^ 2 := by
    rw [sq, ← CStarRing.norm_star_mul_self, hstar, neg_mul, norm_neg]
  have hpow : ∀ k : ℕ, ‖c ^ 2 ^ (k + 1)‖ = ‖c‖ ^ 2 ^ (k + 1) := by
    intro k
    rw [pow_succ, pow_mul', sq c, hs.norm_pow_two_pow, hcc, ← pow_mul, mul_comm]
  by_contra hne
  have ht : 0 < ‖c‖ := norm_pos_iff.mpr hne
  set K : ℝ := 2 * ‖a‖ * ‖b‖ / ‖c‖
  have hlim := FloorSemiring.tendsto_pow_div_factorial_atTop K
  obtain ⟨N, hN⟩ := Filter.eventually_atTop.mp
    ((hlim.eventually (gt_mem_nhds (show (0 : ℝ) < 1 by norm_num))))
  set n := 2 ^ (N + 1)
  have hnN : N ≤ n := (Nat.lt_two_pow_self).le.trans (Nat.pow_le_pow_right (by norm_num) (by omega))
  have h1 := hN n hnN
  have hn0 : 0 < n := by positivity
  have h2 := hbound n hn0
  rw [hpow N] at h2
  have hf : (0 : ℝ) < n.factorial := by exact_mod_cast Nat.factorial_pos n
  have hK : K ^ n = (2 * ‖a‖ * ‖b‖) ^ n / ‖c‖ ^ n := by rw [div_pow]
  rw [hK, div_div, div_lt_one (by positivity)] at h1
  nlinarith [h1, h2]

theorem jmul_opcomm_expand (a b x : A) :
    jmul a (jmul b x) - jmul b (jmul a x) = (4⁻¹ : ℝ) • ((a * b - b * a) * x - x * (a * b - b * a))
    := by
  unfold jmul
  simp only [smul_add, mul_add, add_mul, smul_mul_assoc, mul_smul_comm, smul_smul, mul_assoc,
    mul_sub, sub_mul, smul_sub]
  module

/-- **The commutation theorem, JC case** (van de Wetering 2019 for
JB-algebras): for `a, b` in a JC-algebra `J`, `a` and `b` *operator commute*
(`a∘(b∘x) = b∘(a∘x)` for all `x ∈ J`) iff `ab = ba` in `A`. -/
theorem opComm_iff (J : JCAlgebra A) {a b : A} (ha : a ∈ J.carrier) (hb : b ∈ J.carrier) :
    (∀ x ∈ J.carrier, jmul a (jmul b x) = jmul b (jmul a x)) ↔ Commute a b := by
  constructor
  · intro h
    have hc : ∀ x ∈ J.carrier, Commute (der a b) x := by
      intro x hx
      have e := jmul_opcomm_expand a b x
      rw [h x hx, sub_self] at e
      have e2 : (a * b - b * a) * x - x * (a * b - b * a) = 0 := by
        have := congrArg (fun y => (4 : ℝ) • y) e
        simp only [smul_zero, smul_smul] at this
        norm_num at this
        exact this.symm
      exact sub_eq_zero.mp e2
    have := der_eq_zero (J.sa a ha) (J.sa b hb) (hc a ha) (hc b hb)
    exact sub_eq_zero.mp this
  · intro h x _
    have e := jmul_opcomm_expand a b x
    rw [h.eq, sub_self, zero_mul, mul_zero, sub_self, smul_zero] at e
    exact sub_eq_zero.mp e

/-- **The commutation theorem on `[0,1]_J`**: `a ∘ b = b ∘ a` (sequential
product `U_{√a} b`) iff `a` and `b` operator commute in `J`. -/
theorem sea16_jc_commutes_iff [PartialOrder A] [StarOrderedRing A] (J : JCAlgebra A)
    (a b : Set.Icc (0 : J.carrier) J.one) :
    @Commutes _ J.jcEA J.jcSEA a b ↔
      ∀ x ∈ J.carrier, jmul (JCAlgebra.toA a) (jmul (JCAlgebra.toA b) x) =
        jmul (JCAlgebra.toA b) (jmul (JCAlgebra.toA a) x) := by
  rw [opComm_iff J (JCAlgebra.toA_mem a) (JCAlgebra.toA_mem b)]
  exact JCAlgebra.seq_comm_iff

end Commutation

/-! ## A JC-algebra is a JB-algebra (REC 44) -/

section JB

open Papers.REC

variable [PartialOrder A] [StarOrderedRing A]

/-- For self-adjoint `x`: `−l ≤ x ≤ l` iff `‖x‖ ≤ l` (in a non-trivial `A`). -/
theorem bounds_iff [Nontrivial A] {x : A} (hx : IsSelfAdjoint x) (l : ℝ) :
    (-(algebraMap ℝ A l) ≤ x ∧ x ≤ algebraMap ℝ A l) ↔ ‖x‖ ≤ l := by
  constructor
  · rintro ⟨h1, h2⟩
    have h1' : algebraMap ℝ A (-l) ≤ x := by rw [map_neg]; exact h1
    have s1 := (algebraMap_le_iff_le_spectrum (R := ℝ) (a := x) hx).mp h1'
    have s2 := (le_algebraMap_iff_spectrum_le (R := ℝ) (a := x) hx).mp h2
    rcases CStarAlgebra.norm_or_neg_norm_mem_spectrum hx with h | h
    · exact s2 _ h
    · have := s1 _ h; linarith
  · intro h
    have hm : algebraMap ℝ A ‖x‖ ≤ algebraMap ℝ A l := algebraMap_mono' h
    exact ⟨le_trans (neg_le_neg hm) hx.neg_algebraMap_norm_le_self,
      le_trans hx.le_algebraMap_norm_self hm⟩

namespace JCAlgebra

variable (J : JCAlgebra A)

/-- The order-unit-space structure of `J` (thesis B's `OrderUnitSpace`), with
unit `1`. -/
@[instance_reducible] noncomputable def ous : OrderUnitSpace J.carrier where
  add_le_add_left x y h z := add_le_add h le_rfl
  smul_nonneg {r x} hr hx := by
    show (0 : A) ≤ r • (x : A)
    rw [real_smul_eq]; exact rsmul_nonneg' (show (0 : A) ≤ x from hx) hr
  unit := J.one
  exists_le_smul_unit x := by
    refine ⟨⌈‖(x : A)‖⌉₊, ?_⟩
    show (x : A) ≤ (⌈‖(x : A)‖⌉₊ : ℝ) • (1 : A)
    rw [← Algebra.algebraMap_eq_smul_one]
    exact le_trans (J.sa x x.2).le_algebraMap_norm_self (algebraMap_mono' (Nat.le_ceil _))

/-- The Jordan product of `J` as a multiplication on `J`. -/
@[instance_reducible] noncomputable def jmulInst : Mul J.carrier :=
  ⟨fun x y => ⟨jmul x y, J.jmul_mem x x.2 y y.2⟩⟩

attribute [local instance] ous jmulInst

theorem ouUnit_eq : ((ouUnit J.carrier : J.carrier) : A) = 1 := rfl

theorem smul_unit_val (l : ℝ) : ((l • ouUnit J.carrier : J.carrier) : A) = algebraMap ℝ A l := by
  rw [Algebra.algebraMap_eq_smul_one]; rfl

/-- The order-unit norm of `J` is the C*-norm. -/
theorem ousNorm_eq (x : J.carrier) : ousNorm J.carrier x = ‖(x : A)‖ := by
  rcases subsingleton_or_nontrivial A with hA | hA
  · have hx : (x : A) = 0 := Subsingleton.elim _ _
    rw [hx, norm_zero]
    unfold ousNorm
    refine Real.sInf_of_not_bddBelow ?_
    rintro ⟨m, hm⟩
    have : m - 1 ∈ {l : ℝ | -(l • ouUnit J.carrier) ≤ x ∧ x ≤ l • ouUnit J.carrier} :=
      ⟨show _ ≤ (x : A) from le_of_eq (Subsingleton.elim _ _),
        show (x : A) ≤ _ from le_of_eq (Subsingleton.elim _ _)⟩
    have := hm this; linarith
  · have hset : {l : ℝ | -(l • ouUnit J.carrier) ≤ x ∧ x ≤ l • ouUnit J.carrier} =
        Set.Ici ‖(x : A)‖ := by
      ext l
      rw [Set.mem_ofPred_eq, Set.mem_Ici, ← bounds_iff (J.sa x x.2) l]
      show (-((l • ouUnit J.carrier : J.carrier) : A) ≤ x ∧ (x : A) ≤ (l • ouUnit J.carrier :
        J.carrier)) ↔ _
      rw [smul_unit_val]
    unfold ousNorm
    rw [hset, csInf_Ici]

theorem ousNorm_sub (x y : J.carrier) : ousNorm J.carrier (x - y) = dist (x : A) y := by
  rw [ousNorm_eq, dist_eq_norm]; rfl

/-- **A JC-algebra is a JB-algebra** in REC 44's sense (`JBAlgebra`: a Banach
order unit space with a commutative bilinear unital product satisfying the
Jordan identity and `−1 ≤ a ≤ 1 ⇒ 0 ≤ a² ≤ 1`). -/
theorem isJB : JBAlgebra J.carrier where
  norm_eq_zero v h := by
    rw [ousNorm_eq, norm_eq_zero] at h
    exact Subtype.ext h
  cone_closed v h := by
    show (0 : A) ≤ v
    have hcl : (v : A) ∈ closure (Set.Ici (0 : A)) := by
      rw [Metric.mem_closure_iff]
      intro ε hε
      obtain ⟨w, hw, hvw⟩ := h ε hε
      exact ⟨w, show (0 : A) ≤ w from hw, by rw [← ousNorm_sub]; exact hvw⟩
    rw [isClosed_Ici.closure_eq] at hcl
    exact hcl
  banach s hs := by
    have hc : CauchySeq (fun n => (s n : A)) := by
      rw [Metric.cauchySeq_iff]
      intro ε hε
      obtain ⟨N, hN⟩ := hs ε hε
      exact ⟨N, fun m hm n hn => by rw [← ousNorm_sub]; exact hN m hm n hn⟩
    obtain ⟨L, hL⟩ := cauchySeq_tendsto_of_complete hc
    have hLJ : L ∈ J.carrier :=
      J.isClosed.mem_of_tendsto hL (Filter.Eventually.of_forall fun n => (s n).2)
    refine ⟨⟨L, hLJ⟩, fun ε hε => ?_⟩
    obtain ⟨N, hN⟩ := Metric.tendsto_atTop.mp hL ε hε
    exact ⟨N, fun n hn => by rw [ousNorm_sub]; exact hN n hn⟩
  mul_comm a b := Subtype.ext (jmul_comm (a : A) b)
  mul_one a := Subtype.ext (by
    show jmul (a : A) 1 = a
    rw [jmul_of_commute (Commute.one_right _), mul_one])
  one_mul a := Subtype.ext (by
    show jmul (1 : A) a = a
    rw [jmul_of_commute (Commute.one_left _), one_mul])
  jordan a b := Subtype.ext (by
    show jmul (jmul (a : A) b) (jmul (a : A) a) = jmul (a : A) (jmul (b : A) (jmul (a : A) a))
    unfold jmul
    simp only [smul_add, mul_add, add_mul, smul_mul_assoc, mul_smul_comm, smul_smul, mul_assoc]
    module)
  sq_mem a h1 h2 := by
    have hsa := J.sa a a.2
    have hsq : (0 : A) ≤ (a : A) * a := by
      have h := star_mul_self_nonneg (a : A)
      rwa [hsa.star_eq] at h
    refine ⟨show (0 : A) ≤ jmul (a : A) a by rw [jmul_self]; exact hsq, ?_⟩
    show jmul (a : A) a ≤ 1
    rw [jmul_self]
    rcases subsingleton_or_nontrivial A with hA | hA
    · exact le_of_eq (Subsingleton.elim _ _)
    have hn : ‖(a : A)‖ ≤ 1 := by
      rw [← bounds_iff hsa, map_one]
      exact ⟨h1, h2⟩
    refine (CStarAlgebra.norm_le_one_iff_of_nonneg _ hsq).mp ?_
    calc ‖(a : A) * a‖ ≤ ‖(a : A)‖ * ‖(a : A)‖ := norm_mul_le _ _
      _ ≤ 1 * 1 := mul_le_mul hn hn (norm_nonneg _) zero_le_one
      _ = 1 := one_mul 1
  add_mul a b c := Subtype.ext (by
    show jmul ((a : A) + b) c = jmul (a : A) c + jmul (b : A) c
    unfold jmul; rw [add_mul, mul_add, ← smul_add, add_add_add_comm])
  smul_mul r a b := Subtype.ext (by
    show jmul (r • (a : A)) b = r • jmul (a : A) b
    unfold jmul; rw [smul_mul_assoc, mul_smul_comm, ← smul_add, smul_comm])

end JCAlgebra

/-! ### An ultraweakly closed JC-algebra is a JBW- and a JW-algebra (REC 48, 50) -/

section JBW

variable [Theses.VonNeumannAlgebra A]

namespace JCAlgebra

attribute [local instance] ous jmulInst

variable {J : JCAlgebra A}

/-- A least upper bound in `J` of a non-empty directed subset of an
ultraweakly closed `J` is its least upper bound among the self-adjoint
elements of `A`. -/
theorem isLUB_sa_of_isLUB (hJ : J.IsJW) {S : Set J.carrier} (hne : S.Nonempty)
    (hdir : DirectedOn (· ≤ ·) S) {s : J.carrier} (hs : IsLUB S s) :
    IsLUB ((fun x : J.carrier => (⟨(x : A), J.sa x x.2⟩ : selfAdjoint A)) '' S)
      ⟨(s : A), J.sa s s.2⟩ := by
  set D := (fun x : J.carrier => (⟨(x : A), J.sa x x.2⟩ : selfAdjoint A)) '' S
  have hneD : D.Nonempty := hne.image _
  have hdirD : DirectedOn (· ≤ ·) D := by
    rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩
    obtain ⟨z, hz, h1, h2⟩ := hdir x hx y hy
    exact ⟨_, ⟨z, hz, rfl⟩, h1, h2⟩
  have hbdd : BddAbove D := ⟨⟨s, J.sa s s.2⟩, by
    rintro _ ⟨x, hx, rfl⟩; exact (show (x : A) ≤ s from hs.1 hx)⟩
  obtain ⟨t, ht⟩ := Theses.VonNeumannAlgebra.isLUB_of_bddAbove_directed D hneD hdirD hbdd
  have htJ : (t : A) ∈ J.carrier := by
    refine supClosed_of_isJW hJ ((↑) '' D) ?_ (hneD.image _) ?_ _
      (Papers.SEA.isLUB_coe_of_isLUB hneD ht)
    · rintro _ ⟨_, ⟨x, _, rfl⟩, rfl⟩; exact x.2
    · rintro _ ⟨d, hd, rfl⟩ _ ⟨e, he, rfl⟩
      obtain ⟨f, hf, h1, h2⟩ := hdirD d hd e he
      exact ⟨f, ⟨f, hf, rfl⟩, h1, h2⟩
  have hts : t ≤ (⟨s, J.sa s s.2⟩ : selfAdjoint A) :=
    ht.2 (by rintro _ ⟨x, hx, rfl⟩; exact (show (x : A) ≤ s from hs.1 hx))
  have hst : (s : A) ≤ t := by
    have : s ≤ (⟨t, htJ⟩ : J.carrier) := hs.2 fun x hx => (show (x : A) ≤ t from
      ht.1 ⟨x, hx, rfl⟩)
    exact this
  have : (⟨(s : A), J.sa s s.2⟩ : selfAdjoint A) = t := Subtype.ext (le_antisymm hst (show (t : A) ≤ s from hts))
  rw [this]; exact ht

/-- An ultraweakly closed JC-algebra is directed complete (REC 41). -/
theorem directedComplete_of_isJW (hJ : J.IsJW) :
    IsDirectedCompleteOUS J.carrier := by
  let _ := J.ous
  intro D hD hdir
  rcases D.eq_empty_or_nonempty with hDe | hne
  · refine ⟨0, ⟨le_rfl, J.zero_le_one'⟩, by simp [hDe], fun t ht _ => ht.1⟩
  obtain ⟨t, ht⟩ := Theses.VonNeumannAlgebra.isLUB_of_bddAbove_directed
    ((fun x : J.carrier => (⟨(x : A), J.sa x x.2⟩ : selfAdjoint A)) '' D) (hne.image _)
    (by
      rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩
      obtain ⟨z, hz, h1, h2⟩ := hdir x hx y hy
      exact ⟨_, ⟨z, hz, rfl⟩, h1, h2⟩)
    ⟨⟨1, IsSelfAdjoint.one A⟩, by rintro _ ⟨x, hx, rfl⟩; exact (hD hx).2⟩
  have hDA : ((↑) '' ((fun x : J.carrier => (⟨(x : A), J.sa x x.2⟩ : selfAdjoint A)) '' D) :
      Set A) ⊆ J.carrier := by rintro _ ⟨_, ⟨x, _, rfl⟩, rfl⟩; exact x.2
  have htJ : (t : A) ∈ J.carrier := by
    refine supClosed_of_isJW hJ _ hDA ((hne.image _).image _) ?_ _
      (Papers.SEA.isLUB_coe_of_isLUB (hne.image _) ht)
    rintro _ ⟨_, ⟨x, hx, rfl⟩, rfl⟩ _ ⟨_, ⟨y, hy, rfl⟩, rfl⟩
    obtain ⟨z, hz, h1, h2⟩ := hdir x hx y hy
    exact ⟨_, ⟨_, ⟨z, hz, rfl⟩, rfl⟩, h1, h2⟩
  obtain ⟨x0, hx0⟩ := hne
  refine ⟨⟨t, htJ⟩, ⟨le_trans (hD hx0).1 (show (x0 : A) ≤ t from ht.1 ⟨x0, hx0, rfl⟩),
    show (t : A) ≤ 1 from ht.2 (show (⟨1, IsSelfAdjoint.one A⟩ : selfAdjoint A) ∈ upperBounds _
      by rintro _ ⟨x, hx, rfl⟩; exact (hD hx).2)⟩,
    fun d hd => (show (d : A) ≤ t from ht.1 ⟨d, hd, rfl⟩), fun u _ hu => ?_⟩
  exact (show (t : A) ≤ u from ht.2 (show (⟨u, J.sa u u.2⟩ : selfAdjoint A) ∈ upperBounds _ by
    rintro _ ⟨x, hx, rfl⟩; exact (show (x : A) ≤ u from hu x hx)))

open scoped ComplexOrder in
/-- An np-functional of `A`, normalised, restricts to a normal state of `J`. -/
theorem exists_normal_state (hJ : J.IsJW) (φ : Theses.NPFunctional A)
    (hφ : (φ (1 : A)).re ≠ 0) :
    ∃ ω : OUSState J.carrier, IsNormalMap ω.toLin ∧
      ∀ x : J.carrier, ω.toLin x = (φ (x : A)).re / (φ (1 : A)).re := by
  let _ := J.ous
  set c := (φ (1 : A)).re with hc
  have hc0 : 0 < c := lt_of_le_of_ne (Complex.le_def.mp
    (Theses.A.VN.npFunctional_nonneg φ zero_le_one)).1 (Ne.symm hφ)
  let L : J.carrier →ₗ[ℝ] ℝ :=
    { toFun := fun x => (φ (x : A)).re / c
      map_add' := fun x y => by
        show (φ ((x : A) + y)).re / c = _
        rw [Theses.A.VN.npFunctional_add, Complex.add_re, add_div]
      map_smul' := fun r x => by
        show (φ.toPositiveLinearMap (r • (x : A))).re / c = r • ((φ (x : A)).re / c)
        rw [real_smul_eq, map_smul φ.toPositiveLinearMap, smul_eq_mul, Complex.re_ofReal_mul,
          smul_eq_mul, mul_div_assoc]
        rfl }
  have hreal : ∀ x : J.carrier, (φ (x : A)).im = 0 := fun x =>
    Theses.A.VN.npFunctional_im_eq_zero φ (J.sa x x.2)
  refine ⟨⟨L, fun a ha => div_nonneg (Complex.le_def.mp
      (Theses.A.VN.npFunctional_nonneg φ (show (0 : A) ≤ a from ha))).1 hc0.le,
    div_self hc0.ne'⟩, ?_, fun x => rfl⟩
  intro S s hne hdir hs
  have hsa := isLUB_sa_of_isLUB hJ hne hdir hs
  have hN := φ.preservesDirSups' _ _ (hne.image _) (by
    rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩
    obtain ⟨z, hz, h1, h2⟩ := hdir x hx y hy
    exact ⟨_, ⟨z, hz, rfl⟩, h1, h2⟩) hsa
  have hre := Theses.A.VN.isLUB_re_of_isLUB (by
    rintro _ ⟨_, ⟨x, _, rfl⟩, rfl⟩; exact hreal x) hN
  have himg : Complex.re '' ((fun d : selfAdjoint A => φ.toPositiveLinearMap (d : A)) ''
      ((fun x : J.carrier => (⟨(x : A), J.sa x x.2⟩ : selfAdjoint A)) '' S)) =
      (fun x : J.carrier => (φ (x : A)).re) '' S := by
    rw [Set.image_image, Set.image_image]; rfl
  rw [himg] at hre
  have hmul : (fun x : J.carrier => L x) '' S = (fun r => r / c) '' ((fun x : J.carrier =>
      (φ (x : A)).re) '' S) := by rw [Set.image_image]; rfl
  show IsLUB ((fun x : J.carrier => L x) '' S) (L s)
  rw [hmul]
  exact (OrderIso.divRight₀ c hc0 : ℝ ≃o ℝ).isLUB_image'.mpr hre

/-- **An ultraweakly closed JC-algebra is a JBW-algebra** (REC 48): directed
complete, and separated by normal states (restrictions of normalised
np-functionals of the von Neumann algebra `A`, which separate its points,
vn.tex 44XI). -/
theorem isJBW (hJ : J.IsJW) :
    JBWAlgebra J.carrier := by
  let _ := J.ous
  let _ := J.jmulInst
  refine { J.isJB with directedComplete := directedComplete_of_isJW hJ, separating := ?_ }
  intro a b hab
  have hab' : (a : A) ≠ b := fun h => hab (Subtype.ext h)
  obtain ⟨φ, hφ⟩ : ∃ φ : Theses.NPFunctional A, φ (a : A) ≠ φ b := by
    by_contra h
    push Not at h
    exact hab' (Theses.A.VN.eq_of_forall_npFunctional h)
  have hφ1 : (φ (1 : A)).re ≠ 0 := by
    intro h0
    have hz : ∀ x : A, φ x = 0 := fun x => by
      have := Theses.A.VN.norm_apply_le_omegaNorm φ x
      rw [h0, Real.sqrt_zero, mul_zero] at this
      exact norm_le_zero_iff.mp this
    exact hφ (by rw [hz, hz])
  obtain ⟨ω, hωn, hω⟩ := exists_normal_state hJ φ hφ1
  refine ⟨ω, hωn, ?_⟩
  rw [hω, hω]
  intro h
  have hre : (φ (a : A)).re = (φ (b : A)).re := by
    have hc : (φ (1 : A)).re ≠ 0 := hφ1
    field_simp at h
    exact h
  apply hφ
  apply Complex.ext hre
  rw [Theses.A.VN.npFunctional_im_eq_zero φ (J.sa a a.2),
    Theses.A.VN.npFunctional_im_eq_zero φ (J.sa b b.2)]

/-- **An ultraweakly closed JC-algebra is a JW-algebra in REC 50's sense**: the
inclusion `J → A` is an injective normal Jordan homomorphism into a von
Neumann algebra. -/
theorem isJWAlgebra (hJ : J.IsJW) :
    IsJWAlgebra J.carrier := by
  let _ := J.ous
  let _ := J.jmulInst
  refine ⟨A, inferInstance, inferInstance, inferInstance, inferInstance, J.carrier.subtype,
    ⟨fun x => J.sa x x.2, fun x y => rfl⟩, Subtype.coe_injective, ?_⟩
  intro S s hne hdir hs
  have hsa := isLUB_sa_of_isLUB hJ hne hdir hs
  have := Papers.SEA.isLUB_coe_of_isLUB (hne.image _) hsa
  rw [Set.image_image] at this
  exact this

end JCAlgebra

end JBW

/-! ### The headline statements in `J`'s own terms -/

namespace JCAlgebra

attribute [local instance] ous jmulInst

variable (J : JCAlgebra A)

/-- **SEA 16** (`ex:canonical-sea`, second.tex:475), "any JB-algebra is a
convex SEA", for JC-algebras, stated inside `J`: `J`, with its own Jordan
product `x * y = ½(xy + yx)`, is a JB-algebra (REC 44); `[0, 1]_J` is a convex
effect algebra and a SEA (`jcSEA`) whose product is
`a ∘ b = U_r b = 2 r(r b) − (r r) b` (REC's `jQ`) for the unique `r ∈ J` with
`0 ≤ r` and `r r = a`. -/
theorem sea16_jc_intrinsic :
    JBAlgebra J.carrier ∧ @IsConvex _ J.jcEA ∧
    ∀ a b : Set.Icc (0 : J.carrier) (ouUnit J.carrier),
      ∃! r : J.carrier, 0 ≤ r ∧ r * r = a.1 ∧
        (@SequentialEffectAlgebra.seq _ J.jcEA J.jcSEA.toSequentialEffectAlgebra a b).1 =
          (2 : ℝ) • (r * (r * b.1)) - (r * r) * b.1 := by
  refine ⟨J.isJB, (sea16_jc J).1, fun a b => ?_⟩
  obtain ⟨hmem, hnn, hsq, huniq⟩ := sqrt_spec (toA_mem a) (toA_nonneg a)
  refine ⟨⟨_, hmem⟩, ⟨show (0 : A) ≤ CFC.sqrt (toA a) from hnn, Subtype.ext hsq, ?_⟩, ?_⟩
  · apply Subtype.ext
    exact (seq_eq_jU a b).1
  · rintro r ⟨hr0, hrr, -⟩
    apply Subtype.ext
    exact huniq r r.2 hr0 (congrArg Subtype.val hrr)

/-- The self-adjoint part of `A` is a JC-algebra; for it `jcSEA` is the
C*-algebra SEA of SEA 16 (`cstarSEA`, product `√a b √a`). -/
noncomputable def selfAdjointJC (A : Type u) [CStarAlgebra A] : JCAlgebra A where
  carrier := selfAdjoint.submodule ℝ A
  sa _ h := h
  one_mem := IsSelfAdjoint.one A
  jmul_mem x hx y hy := by
    have hx' : IsSelfAdjoint x := hx
    have hy' : IsSelfAdjoint y := hy
    show IsSelfAdjoint (jmul x y)
    unfold jmul
    refine IsSelfAdjoint.smul (IsSelfAdjoint.all _) ?_
    show star (x * y + y * x) = x * y + y * x
    rw [star_add, star_mul, star_mul, hx'.star_eq, hy'.star_eq, add_comm]
  isClosed := isClosed_eq continuous_star continuous_id

/-- The self-adjoint part is closed under suprema. -/
theorem selfAdjointJC_supClosed : (selfAdjointJC A).SupClosed := by
  intro D hDJ hne _ s hs
  exact isSelfAdjoint_of_ub (fun d hd => hDJ hd) hne hs.1

end JCAlgebra

end JB

/-! ## Abstract special JB-algebras

A JB-algebra `V` in REC 44's sense (`JBAlgebra`) that is *special*: it has a
unital isometric Jordan embedding into a C*-algebra (so it is isometrically
Jordan isomorphic to a JC-algebra, Hanche-Olsen–Størmer 3.1.2, 3.3).  Then
`[0,1]_V` is a convex SEA with `a ∘ b = U_{√a} b` computed in `V`. -/

section Special

open Papers.REC

variable {V : Type u} [AddCommGroup V] [Module ℝ V] [PartialOrder V] [OrderUnitSpace V] [Mul V]
  [hV : JBAlgebra V]

/-- A **special embedding** of the JB-algebra `V`: a real-linear unital map
into a C*-algebra, a Jordan homomorphism into its self-adjoint part (REC 50/51's
`IsJordanHomInto`), and isometric for the order-unit norm. -/
structure SpecialEmbedding (V : Type u) [AddCommGroup V] [Module ℝ V] [PartialOrder V]
    [OrderUnitSpace V] [Mul V] (B : Type u) [CStarAlgebra B] where
  φ : V →ₗ[ℝ] B
  jordan : IsJordanHomInto V B φ
  unital : φ (ouUnit V) = 1
  isometric : ∀ x : V, ‖φ x‖ = ousNorm V x

namespace SpecialEmbedding

variable {B : Type u} [CStarAlgebra B] (E : SpecialEmbedding V B)

theorem sa (x : V) : IsSelfAdjoint (E.φ x) := E.jordan.1 x

theorem map_mul (x y : V) : E.φ (x * y) = jmul (E.φ x) (E.φ y) := E.jordan.2 x y

theorem injective : Function.Injective E.φ := by
  intro x y h
  have : ousNorm V (x - y) = 0 := by rw [← E.isometric, map_sub, h, sub_self, norm_zero]
  exact sub_eq_zero.mp (IsOUS.norm_eq_zero _ this)

theorem map_smul_unit (r : ℝ) : E.φ (r • ouUnit V) = algebraMap ℝ B r := by
  rw [map_smul, E.unital, Algebra.algebraMap_eq_smul_one]

variable [PartialOrder B] [StarOrderedRing B]

/-- In `V`: `0 ≤ x` iff `‖r·1 − x‖ ≤ r` for `r = ‖x‖`. -/
theorem nonneg_iff_V (x : V) :
    0 ≤ x ↔ ousNorm V (ousNorm V x • ouUnit V - x) ≤ ousNorm V x := by
  have hr := ousNorm_nonneg_rc x
  obtain ⟨b1, b2⟩ := ousNorm_bounds_le x
  constructor
  · intro hx
    refine ousNorm_le_rc hr ?_ ?_
    · exact le_trans (neg_nonpos.mpr (ou_smul_unit_nonneg hr)) (sub_nonneg.mpr b2)
    · exact sub_le_self _ hx
  · intro h
    obtain ⟨-, c2⟩ := ousNorm_bounds_le (ousNorm V x • ouUnit V - x)
    have := le_trans c2 (ou_smul_unit_mono h)
    exact (sub_le_self_iff _).mp this

omit [OrderUnitSpace V] [Mul V] hV in
/-- In `B`: a self-adjoint `y` is positive iff `‖r − y‖ ≤ r` for `r = ‖y‖`. -/
theorem nonneg_iff_B {y : B} (hy : IsSelfAdjoint y) :
    0 ≤ y ↔ ‖algebraMap ℝ B ‖y‖ - y‖ ≤ ‖y‖ := by
  rcases subsingleton_or_nontrivial B with hB | hB
  · refine ⟨fun _ => ?_, fun _ => le_of_eq (Subsingleton.elim _ _)⟩
    rw [Subsingleton.elim (algebraMap ℝ B ‖y‖ - y) 0, norm_zero]
    exact norm_nonneg _
  have hsa : IsSelfAdjoint (algebraMap ℝ B ‖y‖ - y) :=
    (IsSelfAdjoint.algebraMap B (IsSelfAdjoint.all ‖y‖)).sub hy
  rw [← bounds_iff hsa]
  constructor
  · intro h0
    refine ⟨?_, sub_le_self _ h0⟩
    have h1 : y ≤ algebraMap ℝ B ‖y‖ := hy.le_algebraMap_norm_self
    have h2 : (0 : B) ≤ algebraMap ℝ B ‖y‖ := by
      rw [Algebra.algebraMap_eq_smul_one, real_smul_eq]
      exact rsmul_nonneg' zero_le_one (norm_nonneg _)
    rw [neg_le_sub_iff_le_add]
    exact le_trans h1 (le_add_of_nonneg_left h2)
  · rintro ⟨-, h2⟩
    exact (sub_le_self_iff _).mp h2

/-- **A special embedding is an order embedding.** -/
theorem nonneg_iff (x : V) : 0 ≤ x ↔ 0 ≤ E.φ x := by
  rw [nonneg_iff_V, nonneg_iff_B (E.sa x), E.isometric x, ← E.map_smul_unit, ← map_sub,
    E.isometric]

theorem le_iff (x y : V) : x ≤ y ↔ E.φ x ≤ E.φ y := by
  rw [← sub_nonneg, E.nonneg_iff, map_sub, sub_nonneg]

/-- The image of a special embedding is a JC-algebra. -/
noncomputable def toJC : JCAlgebra B where
  carrier := LinearMap.range E.φ
  sa := by rintro _ ⟨x, rfl⟩; exact E.sa x
  one_mem := ⟨ouUnit V, E.unital⟩
  jmul_mem := by
    rintro _ ⟨x, rfl⟩ _ ⟨y, rfl⟩
    exact ⟨x * y, E.map_mul x y⟩
  isClosed := by
    refine IsSeqClosed.isClosed fun f a hf hlim => ?_
    choose x hx using hf
    have hc : ∀ ε : ℝ, 0 < ε → ∃ N, ∀ m ≥ N, ∀ n ≥ N, ousNorm V (x m - x n) < ε := by
      intro ε hε
      obtain ⟨N, hN⟩ := Metric.cauchySeq_iff.mp hlim.cauchySeq ε hε
      refine ⟨N, fun m hm n hn => ?_⟩
      have := hN m hm n hn
      rwa [dist_eq_norm, ← hx m, ← hx n, ← map_sub, E.isometric] at this
    obtain ⟨v, hv⟩ := hV.banach x hc
    have hlim' : Tendsto f atTop (𝓝 (E.φ v)) := by
      rw [Metric.tendsto_atTop]
      intro ε hε
      obtain ⟨N, hN⟩ := hv ε hε
      refine ⟨N, fun n hn => ?_⟩
      rw [dist_eq_norm, ← hx n, ← map_sub, E.isometric]
      exact hN n hn
    rw [tendsto_nhds_unique hlim hlim']
    exact ⟨v, rfl⟩

variable (V) in
/-- `[0,1]_V` with the effect algebra structure of SEA 4. -/
@[instance_reducible] noncomputable def jbEA : EffectAlgebra (Set.Icc (0 : V) (ouUnit V)) :=
  orderIntervalEffectAlgebra V (ouUnit V) ou_unit_nonneg

theorem vnonneg (a : Set.Icc (0 : V) (ouUnit V)) : 0 ≤ E.φ a.1 := (E.nonneg_iff _).mp a.2.1

theorem vle_one (a : Set.Icc (0 : V) (ouUnit V)) : E.φ a.1 ≤ 1 := by
  rw [← E.unital]; exact (E.le_iff _ _).mp a.2.2

theorem vext {a b : Set.Icc (0 : V) (ouUnit V)} (h : E.φ a.1 = E.φ b.1) : a = b :=
  Subtype.ext (E.injective h)

theorem sqrtConj_mem (a b : Set.Icc (0 : V) (ouUnit V)) :
    sqrtConj (E.φ a.1) (E.φ b.1) ∈ LinearMap.range E.φ :=
  E.toJC.jU_mem (E.toJC.sqrt_mem (LinearMap.mem_range_self E.φ a.1) (E.vnonneg a))
    (LinearMap.mem_range_self E.φ b.1)

/-- The sequential product on `[0,1]_V`: the element whose image is
`√a b √a` (it is `U_{√a} b` computed in `V`, `sea16_special`). -/
noncomputable def vseq (a b : Set.Icc (0 : V) (ouUnit V)) : Set.Icc (0 : V) (ouUnit V) :=
  ⟨(E.sqrtConj_mem a b).choose,
    (E.nonneg_iff _).mpr (by
      rw [(E.sqrtConj_mem a b).choose_spec]
      exact sqrtConj_nonneg (E.vnonneg b)),
    (E.le_iff _ _).mpr (by
      rw [(E.sqrtConj_mem a b).choose_spec, E.unital]
      exact sqrtConj_le_one (E.vnonneg a) (E.vle_one a) (E.vle_one b))⟩

theorem φ_vseq (a b : Set.Icc (0 : V) (ouUnit V)) :
    E.φ (E.vseq a b).1 = sqrtConj (E.φ a.1) (E.φ b.1) := (E.sqrtConj_mem a b).choose_spec

theorem vseq_comm_iff {a b : Set.Icc (0 : V) (ouUnit V)} :
    E.vseq a b = E.vseq b a ↔ Commute (E.φ a.1) (E.φ b.1) := by
  constructor
  · intro h
    refine commute_of_sqrtConj_eq (E.vnonneg a) (E.vnonneg b) ?_
    rw [← E.φ_vseq, ← E.φ_vseq, h]
  · intro h
    exact E.vext (by rw [E.φ_vseq, E.φ_vseq,
      sqrtConj_comm_of_commute (E.vnonneg a) (E.vnonneg b) h])

/-- `[0,1]_V` is a SEA with the transported product. -/
@[instance_reducible] noncomputable def vSEA : @SEAlgebra (Set.Icc (0 : V) (ouUnit V)) (jbEA V) := by
  letI := jbEA V
  have hperp : ∀ {a b : Set.Icc (0 : V) (ouUnit V)}, Perp a b → E.φ a.1 + E.φ b.1 ≤ 1 := by
    intro a b h
    rw [← map_add, ← E.unital]; exact (E.le_iff _ _).mp h
  have hovee : ∀ {a b : Set.Icc (0 : V) (ouUnit V)} (h : Perp a b),
      E.φ (ovee a b h).1 = E.φ a.1 + E.φ b.1 := fun _ => map_add _ _ _
  have horth : ∀ b : Set.Icc (0 : V) (ouUnit V), E.φ (orth b).1 = 1 - E.φ b.1 := by
    intro b; show E.φ (ouUnit V - b.1) = _; rw [map_sub, E.unital]
  exact
  { seq := E.vseq
    seq_add := fun c {a b} h => by
      have hab := hperp h
      have hp : Perp (E.vseq c a) (E.vseq c b) := by
        show ((E.vseq c a).1 + (E.vseq c b).1 ≤ ouUnit V)
        rw [E.le_iff, map_add, E.φ_vseq, E.φ_vseq, E.unital, sqrtConj_add]
        exact sqrtConj_le_one (E.vnonneg c) (E.vle_one c) hab
      refine ⟨hp, E.vext ?_⟩
      rw [hovee, E.φ_vseq, E.φ_vseq, E.φ_vseq, hovee]
      exact sqrtConj_add _ _ _
    one_seq := fun a => E.vext (by
      rw [E.φ_vseq]; show sqrtConj (E.φ (ouUnit V)) _ = _
      rw [E.unital]; exact sqrtConj_one_left _)
    seq_zero_comm := fun a b hab => E.vext (by
      have h0 : E.φ (E.vseq a b).1 = 0 := by rw [hab]; exact map_zero _
      rw [E.φ_vseq] at h0
      rw [E.φ_vseq, sqrtConj_eq_zero_comm (E.vnonneg a) (E.vnonneg b) h0]
      exact (map_zero _).symm)
    seq_comm_orth := fun {a b} h => by
      have hcomm := E.vseq_comm_iff.mp h
      have hc2 : Commute (E.φ a.1) (E.φ (orth b).1) := by
        rw [horth]; exact (Commute.one_right _).sub_right hcomm
      exact E.vseq_comm_iff.mpr hc2
    seq_comm_assoc := fun {a b} h c => E.vext (by
      rw [E.φ_vseq, E.φ_vseq, E.φ_vseq, E.φ_vseq]
      exact sqrtConj_assoc_of_commute (E.vnonneg a) (E.vnonneg b) (E.vseq_comm_iff.mp h) _)
    seq_comm_compat := fun {a b c} h hca hcb => by
      have h1 := E.vseq_comm_iff.mp hca
      have h2 := E.vseq_comm_iff.mp hcb
      have hsa : Commute (E.φ c.1) (CFC.sqrt (E.φ a.1)) := (commute_sqrt h1.symm).symm
      have h3 : Commute (E.φ c.1) (E.φ (E.vseq a b).1) := by
        rw [E.φ_vseq]; exact (hsa.mul_right h2).mul_right hsa
      have h4 : Commute (E.φ c.1) (E.φ (ovee a b h).1) := by
        rw [hovee]; exact h1.add_right h2
      exact ⟨E.vseq_comm_iff.mpr h3, E.vseq_comm_iff.mpr h4⟩
    seq_comm_seq := fun {a b c} hca hcb => by
      have h1 := E.vseq_comm_iff.mp hca
      have h2 := E.vseq_comm_iff.mp hcb
      have hsa : Commute (E.φ c.1) (CFC.sqrt (E.φ a.1)) := (commute_sqrt h1.symm).symm
      have h3 : Commute (E.φ c.1) (E.φ (E.vseq a b).1) := by
        rw [E.φ_vseq]; exact (hsa.mul_right h2).mul_right hsa
      exact E.vseq_comm_iff.mpr h3 }

end SpecialEmbedding

/-- **SEA 16** (`ex:canonical-sea`, second.tex:475, Example), "any JB-algebra
is a convex SEA", for **special** JB-algebras: if the JB-algebra `V` (REC 44)
has a unital isometric Jordan embedding `E` into a C*-algebra, then `[0,1]_V`
is a convex effect algebra and a SEA (`E.vSEA`) whose product is, computed
in `V`, `a ∘ b = U_r b = 2 r(r b) − (r r) b` for the unique `r ≥ 0` in `V`
with `r r = a` (`r = √a`). -/
theorem sea16_special {B : Type u} [CStarAlgebra B] [PartialOrder B] [StarOrderedRing B]
    (E : SpecialEmbedding V B) :
    @IsConvex _ (SpecialEmbedding.jbEA V) ∧
    ∀ a b : Set.Icc (0 : V) (ouUnit V),
      ∃! r : V, 0 ≤ r ∧ r * r = a.1 ∧
        (@SequentialEffectAlgebra.seq _ (SpecialEmbedding.jbEA V)
          E.vSEA.toSequentialEffectAlgebra a b).1 = (2 : ℝ) • (r * (r * b.1)) - (r * r) * b.1 := by
  have := Papers.OAP.ous_posSMulMono V
  have := Papers.OAP.ous_smulPosMono V
  refine ⟨sea9_interval_convex V (ouUnit V) ou_unit_nonneg, fun a b => ?_⟩
  have hm : CFC.sqrt (E.φ a.1) ∈ LinearMap.range E.φ :=
    E.toJC.sqrt_mem (LinearMap.mem_range_self E.φ a.1) (E.vnonneg a)
  obtain ⟨r, hr⟩ := hm
  have hr0 : 0 ≤ r := (E.nonneg_iff r).mpr (by rw [hr]; exact CFC.sqrt_nonneg _)
  have hrr : r * r = a.1 := E.injective (by
    rw [E.map_mul, hr, jmul_self]; exact CFC.sqrt_mul_sqrt_self _ (E.vnonneg a))
  refine ⟨r, ⟨hr0, hrr, E.injective ?_⟩, ?_⟩
  · show E.φ (E.vseq a b).1 = _
    rw [E.φ_vseq, map_sub, map_smul, E.map_mul, E.map_mul, E.map_mul, E.map_mul, hr]
    rw [← jU, jU_eq]; rfl
  · rintro r' ⟨hr0', hrr', -⟩
    apply E.injective
    rw [hr]
    have h1 : E.φ r' * E.φ r' = E.φ a.1 := by rw [← jmul_self, ← E.map_mul, hrr']
    rw [← h1]
    exact (CFC.sqrt_mul_self _ ((E.nonneg_iff r').mp hr0')).symm

/-! ### The normal case: JBW-algebras with a normal special embedding -/

/-- In a directed complete order unit space, the supremum of a non-empty
directed `D ⊆ [0,1]_V` inside `[0,1]_V` is its least upper bound in `V`: for an
upper bound `u ≤ λ·1` (`λ ≥ 1`), compare with the supremum of `λ⁻¹ D`. -/
theorem isLUB_of_Icc_sup (hdc : IsDirectedCompleteOUS V) {D : Set V}
    (hD : D ⊆ Set.Icc 0 (ouUnit V)) (hne : D.Nonempty) (hdir : DirectedOn (· ≤ ·) D) {s : V}
    (hub : ∀ d ∈ D, d ≤ s)
    (hleast : ∀ t ∈ Set.Icc 0 (ouUnit V), (∀ d ∈ D, d ≤ t) → s ≤ t) : IsLUB D s := by
  refine ⟨hub, fun u hu => ?_⟩
  obtain ⟨d0, hd0⟩ := hne
  have hu0 : 0 ≤ u := le_trans (hD hd0).1 (hu hd0)
  set l : ℝ := max 1 (ousNorm V u) with hl
  have hl1 : 1 ≤ l := le_max_left _ _
  have hl0 : 0 < l := lt_of_lt_of_le one_pos hl1
  have hul : u ≤ l • ouUnit V :=
    le_trans (ousNorm_bounds_le u).2 (ou_smul_unit_mono (le_max_right _ _))
  -- the supremum `t` of `l⁻¹ D` in `[0,1]`
  have hD' : (fun d => l⁻¹ • d) '' D ⊆ Set.Icc 0 (ouUnit V) := by
    rintro _ ⟨d, hd, rfl⟩
    refine ⟨ou_smul_nonneg (inv_nonneg.mpr hl0.le) (hD hd).1, ?_⟩
    calc l⁻¹ • d ≤ l⁻¹ • ouUnit V := ou_smul_le_smul (inv_nonneg.mpr hl0.le) (hD hd).2
      _ ≤ (1 : ℝ) • ouUnit V := ou_smul_unit_mono (inv_le_one_of_one_le₀ hl1)
      _ = ouUnit V := one_smul _ _
  obtain ⟨t, ht, htub, htleast⟩ := hdc _ hD' (by
    rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩
    obtain ⟨z, hz, h1, h2⟩ := hdir x hx y hy
    exact ⟨_, ⟨z, hz, rfl⟩, ou_smul_le_smul (inv_nonneg.mpr hl0.le) h1,
      ou_smul_le_smul (inv_nonneg.mpr hl0.le) h2⟩)
  have hscale : ∀ {x y : V}, l⁻¹ • x ≤ y ↔ x ≤ l • y := by
    intro x y
    constructor
    · intro h
      have := ou_smul_le_smul hl0.le h
      rwa [smul_smul, mul_inv_cancel₀ hl0.ne', one_smul] at this
    · intro h
      have := ou_smul_le_smul (inv_nonneg.mpr hl0.le) h
      rwa [smul_smul, inv_mul_cancel₀ hl0.ne', one_smul] at this
  -- `l t` is an upper bound of `D` below `1`, so `s ≤ l t`
  have hlt1 : l • t ≤ ouUnit V := by
    have := htleast (l⁻¹ • ouUnit V)
      ⟨ou_smul_nonneg (inv_nonneg.mpr hl0.le) ou_unit_nonneg,
        le_trans (ou_smul_unit_mono (inv_le_one_of_one_le₀ hl1)) (le_of_eq (one_smul _ _))⟩
      (by rintro _ ⟨d, hd, rfl⟩; exact ou_smul_le_smul (inv_nonneg.mpr hl0.le) (hD hd).2)
    have := ou_smul_le_smul hl0.le this
    rwa [smul_smul, mul_inv_cancel₀ hl0.ne', one_smul] at this
  have hslt : s ≤ l • t := hleast _ ⟨ou_smul_nonneg hl0.le ht.1, hlt1⟩
    (fun d hd => hscale.mp (htub _ ⟨d, hd, rfl⟩))
  -- `l⁻¹ u ∈ [0,1]` bounds `l⁻¹ D`, so `t ≤ l⁻¹ u`
  have htu : t ≤ l⁻¹ • u := htleast _
    ⟨ou_smul_nonneg (inv_nonneg.mpr hl0.le) hu0, hscale.mpr hul⟩
    (by rintro _ ⟨d, hd, rfl⟩; exact ou_smul_le_smul (inv_nonneg.mpr hl0.le) (hu hd))
  calc s ≤ l • t := hslt
    _ ≤ l • (l⁻¹ • u) := ou_smul_le_smul hl0.le htu
    _ = u := by rw [smul_smul, mul_inv_cancel₀ hl0.ne', one_smul]

end Special

section SpecialW

open Papers.REC

variable {V : Type u} [AddCommGroup V] [Module ℝ V] [PartialOrder V] [OrderUnitSpace V] [Mul V]
  [hW : JBWAlgebra V]

namespace SpecialEmbedding

variable {B : Type u} [CStarAlgebra B] [PartialOrder B] [StarOrderedRing B]
  (E : SpecialEmbedding V B)

/-- In `[0,1]_V` (`V` a JBW-algebra), a supremum of a directed set is its
least upper bound in `V`, and `E` maps it to the least upper bound among the
self-adjoint elements of `B` when `E` is normal. -/
theorem sup_facts (hn : IsNormalMap E.φ) {S : Set (Set.Icc (0 : V) (ouUnit V))}
    (hS : @EDirected _ (jbEA V) S) {x : Set.Icc (0 : V) (ouUnit V)}
    (hx : @EIsSup _ (jbEA V) S x) :
    IsLUB ((fun v : Set.Icc (0 : V) (ouUnit V) => (⟨E.φ v.1, E.sa v.1⟩ : selfAdjoint B)) '' S)
      ⟨E.φ x.1, E.sa x.1⟩ := by
  let _ := jbEA V
  have hle := interval_le_iff (ouUnit V) (ou_unit_nonneg (X := V))
  obtain ⟨hne, hdir⟩ := hS
  have hDV : IsLUB (Subtype.val '' S) x.1 := by
    refine isLUB_of_Icc_sup hW.directedComplete (by rintro _ ⟨v, _, rfl⟩; exact v.2)
      (hne.image _) ?_ (by rintro _ ⟨v, hv, rfl⟩; exact (hle v x).mp (hx.1 v hv)) ?_
    · rintro _ ⟨v, hv, rfl⟩ _ ⟨w, hw, rfl⟩
      obtain ⟨z, hz, h1, h2⟩ := hdir v hv w hw
      exact ⟨z.1, ⟨z, hz, rfl⟩, (hle v z).mp h1, (hle w z).mp h2⟩
    · intro t ht htub
      exact (hle x ⟨t, ht⟩).mp (hx.2 ⟨t, ht⟩ fun v hv => (hle v ⟨t, ht⟩).mpr (htub _ ⟨v, hv, rfl⟩))
  have hB := hn _ _ (hne.image _) (by
    rintro _ ⟨v, hv, rfl⟩ _ ⟨w, hw, rfl⟩
    obtain ⟨z, hz, h1, h2⟩ := hdir v hv w hw
    exact ⟨z.1, ⟨z, hz, rfl⟩, (hle v z).mp h1, (hle w z).mp h2⟩) hDV
  refine ⟨?_, fun t ht => ?_⟩
  · rintro _ ⟨v, hv, rfl⟩; exact hB.1 ⟨v.1, ⟨v, hv, rfl⟩, rfl⟩
  · exact hB.2 (by rintro _ ⟨_, ⟨v, hv, rfl⟩, rfl⟩; exact ht ⟨v, hv, rfl⟩)

/-- **SEA 16**, JBW clause, for special JBW-algebras: `[0,1]_V` is a normal SEA
with the product of `vSEA` when `V` is a JBW-algebra (REC 48) with a normal
special embedding. -/
@[instance_reducible] noncomputable def vNormalSEA (hn : IsNormalMap E.φ) :
    @NormalSEA (Set.Icc (0 : V) (ouUnit V)) (jbEA V) := by
  letI := jbEA V
  letI := E.vSEA
  have hle := interval_le_iff (ouUnit V) (ou_unit_nonneg (X := V))
  have hnorm : ∀ z : Set.Icc (0 : V) (ouUnit V), ‖E.φ z.1‖ ≤ ‖(1 : B)‖ := fun z =>
    CStarAlgebra.norm_le_norm_of_nonneg_of_le (E.vnonneg z) (E.vle_one z)
  exact
  { E.vSEA with
    directedComplete := fun S hS => by
      obtain ⟨hne, hdir⟩ := hS
      obtain ⟨t, ht, htub, htleast⟩ := hW.directedComplete (Subtype.val '' S)
        (by rintro _ ⟨v, _, rfl⟩; exact v.2) (by
          rintro _ ⟨v, hv, rfl⟩ _ ⟨w, hw, rfl⟩
          obtain ⟨z, hz, h1, h2⟩ := hdir v hv w hw
          exact ⟨z.1, ⟨z, hz, rfl⟩, (hle v z).mp h1, (hle w z).mp h2⟩)
      exact ⟨⟨t, ht⟩, fun v hv => (hle v ⟨t, ht⟩).mpr (htub _ ⟨v, hv, rfl⟩),
        fun y hy => (hle ⟨t, ht⟩ y).mpr (htleast y.1 y.2 fun _ ⟨v, hv, e⟩ => by
          rw [← e]; exact (hle v y).mp (hy v hv))⟩
    seq_sup := by
      intro a S x hS hx
      have hsa := E.sup_facts hn hS hx
      have hL := conj_isLUB_of_nonneg (CFC.sqrt_nonneg (E.φ a.1)) (hS.1.image _)
        (M := ‖(1 : B)‖) (by rintro _ ⟨z, _, rfl⟩; exact hnorm z) hsa (hnorm x)
      refine ⟨?_, fun y hy => (hle _ _).mpr ((E.le_iff _ _).mpr ?_)⟩
      · rintro _ ⟨s, hs, rfl⟩
        refine (hle _ _).mpr ((E.le_iff _ _).mpr ?_)
        show E.φ (E.vseq a s).1 ≤ E.φ (E.vseq a x).1
        rw [E.φ_vseq, E.φ_vseq]
        exact hL.1 ⟨_, ⟨s, hs, rfl⟩, rfl⟩
      · show E.φ (E.vseq a x).1 ≤ E.φ y.1
        rw [E.φ_vseq]
        refine hL.2 ?_
        rintro _ ⟨_, ⟨s, hs, rfl⟩, rfl⟩
        have := (E.le_iff _ _).mp ((hle _ _).mp (hy _ ⟨s, hs, rfl⟩))
        show sqrtConj (E.φ a.1) (E.φ s.1) ≤ E.φ y.1
        rw [← E.φ_vseq]; exact this
    comm_sup := by
      intro a S x hS hx hcomm
      have hsa := E.sup_facts hn hS hx
      have hc : ∀ d ∈ (fun v : Set.Icc (0 : V) (ouUnit V) =>
          (⟨E.φ v.1, E.sa v.1⟩ : selfAdjoint B)) '' S, Commute (E.φ a.1) (d : B) := by
        rintro _ ⟨s, hs, rfl⟩
        exact E.vseq_comm_iff.mp (hcomm s hs)
      exact E.vseq_comm_iff.mpr (commute_of_isLUB (E.vnonneg a) (E.vle_one a) (hS.1.image _) hsa hc) }

end SpecialEmbedding

/-- **SEA 16** (`ex:canonical-sea`, second.tex:475, Example), "any JBW-algebra
is a convex normal SEA", for **special** JBW-algebras: if `V` is a JBW-algebra
(REC 48) with a *normal* unital isometric Jordan embedding `E` into a
C*-algebra, then `[0,1]_V` is convex and a normal SEA (`E.vNormalSEA`) whose
product is `U_{√a} b` computed in `V` (as in `sea16_special`). -/
theorem sea16_special_normal {B : Type u} [CStarAlgebra B] [PartialOrder B]
    [StarOrderedRing B] (E : SpecialEmbedding V B) (hn : IsNormalMap E.φ) :
    @IsConvex _ (SpecialEmbedding.jbEA V) ∧
    ∀ a b : Set.Icc (0 : V) (ouUnit V),
      ∃! r : V, 0 ≤ r ∧ r * r = a.1 ∧
        (@SequentialEffectAlgebra.seq _ (SpecialEmbedding.jbEA V)
          (E.vNormalSEA hn).toSequentialEffectAlgebra a b).1 =
          (2 : ℝ) • (r * (r * b.1)) - (r * r) * b.1 :=
  sea16_special E

end SpecialW

/-! ### Every JC-algebra is special in the abstract sense -/

section Examples

variable [PartialOrder A] [StarOrderedRing A]

namespace JCAlgebra

attribute [local instance] ous jmulInst

variable (J : JCAlgebra A)

/-- The inclusion of a JC-algebra is a special embedding of the JB-algebra
`J` (`isJB`), so `sea16_special` covers every JC-algebra. -/
noncomputable def specialEmbedding : SpecialEmbedding J.carrier A where
  φ := J.carrier.subtype
  jordan := ⟨fun x => J.sa x x.2, fun _ _ => rfl⟩
  unital := rfl
  isometric x := (J.ousNorm_eq x).symm

/-- For an ultraweakly closed `J` in a von Neumann algebra, the inclusion is
normal, so `sea16_special_normal` covers every JW-algebra (with `isJBW`). -/
theorem specialEmbedding_normal [Theses.VonNeumannAlgebra A] (hJ : J.IsJW) :
    Papers.REC.IsNormalMap J.specialEmbedding.φ := by
  intro S s hne hdir hs
  have hsa := isLUB_sa_of_isLUB hJ hne hdir hs
  have := Papers.SEA.isLUB_coe_of_isLUB (hne.image _) hsa
  rw [Set.image_image] at this
  exact this

end JCAlgebra

end Examples

end Papers.SEA.JC
