#!/usr/bin/env python3
"""Flag doc comments that claim a von Neumann setting the Lean type does not have.

A doc comment saying "an mi-bilinear map between von Neumann algebras is
completely positive" over a signature whose binders are `CStarAlgebra` is
stating the *thesis's* theorem and proving a stronger one.  That is not a
harmless wording slip: the audit row above it is then graded against a
statement the tree does not make, which is how `113II` and all four renderings
of `113IV` sat at `stmt=ok` while a fifth rendering of the same generalisation,
in `A/CStar`, was graded `stronger`.

The binders cannot be read off the source -- `variable`, `omit ... in`, section
structure and superclass instances all intervene -- so they are taken from
`docs/binders.txt`, which `scripts/BinderDump.lean` writes by walking the
elaborated environment.  Regenerate it after changing any signature:

    scripts/lean1.sh scripts/BinderDump.lean

and NOT with `lake env lean`: that runs outside the compile lock, and one
`lean` on this tree peaks at 7.2 GB on a 14 GB swapless box (see
`scripts/lean1.sh`).  `BinderDump` imports everything, so it is one of the
heaviest runs there is.

A doc comment is flagged when its **first sentence** says "von Neumann" and the
declaration's type carries `CStarAlgebra` without `Theses.VonNeumannAlgebra`.

Two phrases are not claims about the setting and are excluded: a *von Neumann
subalgebra* and a *von Neumann tensor product* are objects named in the
statement, carried by predicates like `IsVNSubalgebra` and by `vnTensor`, and a
declaration about them needs no von Neumann binder on the ambient type.

A **contrastive** mention is excluded too, and for the same reason: it is the
opposite of a claim.  `procIsCornerOf_of_isCornerFor` says its universal property
"is being asked of *fewer* test objects there (von Neumann rather than all
C\*-algebras)" -- describing the SOURCE's setting precisely in order to say the
tree's is wider.  Flagging that would be exactly backwards, and would push the
next author to reword a doc comment that is right.  The marker has to follow the
mention closely (40 characters), so that a doc which claims the setting in one
clause and says "not" in some unrelated later one is still reported.
"""

import pathlib
import re
import sys

LEAN = pathlib.Path(__file__).resolve().parents[1] / "Theses"
BINDERS = pathlib.Path(__file__).resolve().parents[1] / "docs" / "binders.txt"

DECL = re.compile(r'^(?:private |protected |noncomputable |@\[[^\]]*\]\s*)*'
                  r'(?:theorem|lemma) (\S+)')
TAG = re.compile(r'\*\*(\d{1,3}[a-z]?[IVXL]+(?:\.[0-9a-z]+)?)\*\*')
# an object, not a hypothesis about the ambient algebra
OBJECTS = ("von Neumann subalgebra", "von Neumann subalgebras",
           "von Neumann tensor product")

# "von Neumann rather than all C*-algebras" -- the source's setting, named to
# contrast with ours.  Kept tight to the mention on purpose; see the module doc.
CONTRAST = re.compile(r'on Neumann[^.]{0,40}?'
                      r'(?:rather than|instead of|as opposed to|whereas|not all)',
                      re.I)


def binder_table():
    out = {}
    if not BINDERS.exists():
        sys.exit(f"{BINDERS} is missing; run `scripts/lean1.sh scripts/BinderDump.lean`")
    for line in BINDERS.read_text().splitlines():
        parts = line.split("|")
        if len(parts) == 3:
            out[parts[1]] = (parts[0], [c for c in parts[2].split(",") if c])
    return out


def stale(binders):
    """Declarations `docs/binders.txt` names that the tree no longer has.

    The file is generated by `scripts/BinderDump.lean` and regenerated by hand,
    so a rename or a deletion leaves it describing declarations that are gone —
    and this check then reads a *stale* type for a name that still exists
    elsewhere.  `audit_check.py` guards `docs/status.txt` the same way and for
    the same reason.  Only that direction is tested: the file holds theorems
    only, so a `def` missing from it is not an error, and Lean synthesises
    `instFooBar` and `toParentClass` names that appear in no source.
    """
    # `LEAN` is already `lean/Theses` here, not `lean/` -- rglobbing
    # `Theses/**/*.lean` under it matched nothing, so every name read as stale.
    # And 6432 regex searches over 7.7 MB is fifty gigabytes of scanning: the
    # sources are tokenised once instead, and membership tested against the set.
    tokens = set()
    for path in sorted(LEAN.rglob("*.lean")):
        if ".lake" in path.parts:
            continue
        # Lean names carry primes, Greek, and sub/superscripts -- `tpair_tp₁`,
        # `𝒜`, `bax'`.  `\w` alone drops the subscripts, and 79 live
        # declarations then read as stale.
        tokens.update(re.findall(r"[\w'\u2070-\u209f]+",
                                 path.read_text(errors="replace"), re.UNICODE))
    out = []
    for full in binders:
        short = full.rsplit(".", 1)[-1]
        if short.startswith("inst") or re.match(r'to[A-Z]', short):
            continue
        if short not in tokens:
            out.append(full)
    return sorted(out)


def doc_of(lines, i):
    """The doc comment immediately above line `i`, or None."""
    j = i - 1
    while j >= 0 and not lines[j].lstrip().startswith("/--"):
        if lines[j].strip() == "" or lines[j].lstrip().startswith("--"):
            return None
        j -= 1
    return " ".join(lines[j:i]) if j >= 0 else None


def main():
    binders = binder_table()
    for name in stale(binders):
        print(f"STALE   docs/binders.txt names {name}, which the tree no longer has; "
              f"regenerate with `scripts/lean1.sh scripts/BinderDump.lean`")
    hits = []
    for src in sorted(LEAN.rglob("*.lean")):
        lines = src.read_text().splitlines()
        for i, line in enumerate(lines):
            m = DECL.match(line)
            if not m:
                continue
            doc = doc_of(lines, i)
            if not doc:
                continue
            first = doc.split(". ")[0]
            if "on Neumann" not in first or any(o in first for o in OBJECTS):
                continue
            if CONTRAST.search(first):
                continue
            cand = [k for k in binders if k == m.group(1) or k.endswith("." + m.group(1))]
            if not cand:
                continue
            classes = binders[cand[0]][1]
            has = lambda k: any(k in c for c in classes)
            if has("CStarAlgebra") and not has("VonNeumannAlgebra"):
                tag = TAG.search(doc)
                hits.append((src, i + 1, m.group(1), tag.group(1) if tag else "-",
                             " ".join(first.split())[:140]))

    for src, ln, name, tag, txt in hits:
        print(f"VNCLAIM {src}:{ln}  {name}  [{tag}]\n        {txt}")
    gone = stale(binders)
    print(f"\n{len(hits)} doc comments claim a von Neumann setting their type does not "
          f"have; {len(gone)} names in docs/binders.txt are no longer in the tree")
    return 1 if (hits or gone) else 0


if __name__ == "__main__":
    sys.exit(main())
