/-
Thesis A (Abraham Westerbaan, *The Category of Von Neumann Algebras*,
arXiv:1804.02203), chapter 2: Von Neumann Algebras — vn.tex, lines 1–2182.

  §The Basics
    Definition and Counterexamples  (parsec 420: Kadison's definition — in
                                     `Theses.Common` — and the ultraweak and
                                     ultrastrong topologies; parsec 430:
                                     counterexamples in B(ℓ²))
    Elementary Theory               (parsecs 440–460: suprema vs.
                                     multiplication, normality of positive
                                     maps, ultraweak/ultrastrong continuity)
    parsec 470: the categories W*_miu and W*_cpsu, products, equalisers
    parsec 480: the normal Gelfand–Naimark theorem
  §Examples
    parsec 490: matrices over a von Neumann algebra
    parsecs 500–540: commutative von Neumann algebras, L^∞(X), meagre sets,
                     extremal disconnectedness, the classification of
                     commutative von Neumann algebras with a faithful
                     np-functional

Statements only; every proof is `sorry`.  See CONVENTIONS.md for the
numbering (**42I** = parsec 420, point 10) and naming conventions.

Encoding of the ultraweak/ultrastrong topologies: they are *defs* (not
instances), so they never clash with the norm topology; statements mention
them explicitly, via `@`-application (e.g. `@IsClosed A (ultraweak A) C`) or
via the convergence predicates `UWTendsto`/`USTendsto`.
-/
import Theses.Common
import Theses.A.CStar.Basic
import Theses.A.CStar.TowardsVN

open scoped ComplexOrder ComplexInnerProductSpace CStarAlgebra ENNReal symmDiff
open Filter Topology MeasureTheory Theses Theses.A.CStar

-- The topologies `ultraweak`/`ultrastrong` (and the σ-algebra
-- `almostClopenMS`) are *intentionally* plain defs, not instances:
set_option warn.classDefReducibility false

universe u

namespace Theses.A.VN

/-! ## Parsec 420 (`vna`): Kadison's definition; the two topologies

**42I** (`vna`, vn.tex:166, Definition (Kadison)): the definition of a von
Neumann algebra is formalized in `Theses.Common` as the class
`Theses.VonNeumannAlgebra`.

**42II** (`def-np-functional`, vn.tex:196): normal positive functionals are
`Theses.NPFunctional` (with `Theses.PreservesDirSups` for normality).

**42IIa** (vn.tex:203): "n" abbreviates "normal" — nothing to formalize.

**42IV** (vn.tex:246, Remark): on the interplay of the two topologies —
nothing to formalize. -/

section Topologies

variable {A B : Type*} [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
  [CStarAlgebra B] [PartialOrder B] [StarOrderedRing B]

variable (A) in
/-- **42III** (vn.tex:208): the seminorm `‖a‖_ω = ω(a*a)^½` associated to an
np-functional `ω` (cf. `omega-norm-basic`, cstar.tex 30IV). -/
noncomputable def omegaNorm (ω : NPFunctional A) (a : A) : ℝ :=
  Real.sqrt (ω (star a * a)).re

variable (A) in
/-- **42III** (vn.tex:208): the **ultraweak topology** on a von Neumann
algebra `A`: the least topology making every np-functional `ω : A → ℂ`
continuous.  Deliberately a `def`, not an instance. -/
noncomputable def ultraweak : TopologicalSpace A :=
  ⨅ ω : NPFunctional A, TopologicalSpace.induced (fun a => ω a) inferInstance

variable (A) in
/-- **42III** (vn.tex:208): the **ultrastrong topology** on a von Neumann
algebra `A`: the topology generated by the "balls"
`{a | ‖a - b‖_ω < ε}` of the seminorms `‖·‖_ω` associated to the
np-functionals.  Deliberately a `def`, not an instance. -/
noncomputable def ultrastrong : TopologicalSpace A :=
  TopologicalSpace.generateFrom
    {U : Set A | ∃ (ω : NPFunctional A) (b : A) (ε : ℝ), 0 < ε ∧
      U = {a : A | omegaNorm A ω (a - b) < ε}}

/-- Convergence with respect to the ultraweak topology (encoding used
throughout these files). -/
def UWTendsto {ι : Type*} (x : ι → A) (l : Filter ι) (a : A) : Prop :=
  Tendsto x l (@nhds A (ultraweak A) a)

/-- Convergence with respect to the ultrastrong topology (encoding used
throughout these files). -/
def USTendsto {ι : Type*} (x : ι → A) (l : Filter ι) (a : A) : Prop :=
  Tendsto x l (@nhds A (ultrastrong A) a)

/-- **42III** (vn.tex:208), embedded claim ("one can verify"): a net
`(b_α)_α` converges ultraweakly to `b` iff `ω(b_α) → ω(b)` for every
np-functional `ω`. -/
theorem uwTendsto_iff {ι : Type*} (x : ι → A) (l : Filter ι) (b : A) :
    UWTendsto x l b ↔
      ∀ ω : NPFunctional A, Tendsto (fun i => ω (x i)) l (𝓝 (ω b)) :=
  sorry

/-- **42III** (vn.tex:208), embedded claim ("one can prove"): a net `(b_α)_α`
converges ultrastrongly to `b` iff `‖b_α - b‖_ω → 0` for every np-functional
`ω`. -/
theorem usTendsto_iff {ι : Type*} (x : ι → A) (l : Filter ι) (b : A) :
    USTendsto x l b ↔
      ∀ ω : NPFunctional A,
        Tendsto (fun i => omegaNorm A ω (x i - b)) l (𝓝 0) :=
  sorry

/-! ## 42V: Examples of von Neumann algebras -/

/-- **42V** (`von-neumann-examples`, vn.tex:262, Examples), part 1: `ℂ` is a
von Neumann algebra.  (`{0}` — any subsingleton C*-algebra — is one too,
trivially.) -/
noncomputable instance : VonNeumannAlgebra ℂ := sorry

/-- **42V** (`von-neumann-examples`, vn.tex:262, Examples), part 2: the
C*-algebra `B(H)` of bounded operators on a Hilbert space `H` is a von
Neumann algebra: it has bounded directed suprema of self-adjoint elements by
cstar.tex 37IX, and the vector states are order separating by cstar.tex
25III. -/
instance {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] : VonNeumannAlgebra (H →L[ℂ] H) := sorry

section DirectSum

variable {I : Type*} (𝒜 : I → Type u) [∀ i, CStarAlgebra (𝒜 i)]
  [∀ i, Nontrivial (𝒜 i)]

/-- The direct sum `⊕ᵢ 𝒜ᵢ = lp 𝒜 ∞` of unital C*-algebras is a unital
C*-algebra (Mathlib provides all the pieces but only registers the
commutative unital instance; this mirrors `lp.inftyCommCStarAlgebra`). -/
noncomputable instance : CStarAlgebra (lp 𝒜 ∞) where

/-- The canonical (spectral) order on the direct sum `lp 𝒜 ∞`, mirroring
`CStarMatrix.instPartialOrder`. -/
noncomputable instance : PartialOrder (lp 𝒜 ∞) := CStarAlgebra.spectralOrder _

instance : StarOrderedRing (lp 𝒜 ∞) := CStarAlgebra.spectralOrderedRing _

variable [∀ i, PartialOrder (𝒜 i)] [∀ i, StarOrderedRing (𝒜 i)]

/-- **42V** (`von-neumann-examples`, vn.tex:262, Examples), part 3 (also
**47IV**, `vn-products`, part 1): the direct sum `⊕ᵢ 𝒜ᵢ` (Mathlib:
`lp 𝒜 ∞`) of a family of von Neumann algebras is a von Neumann algebra. -/
instance vonNeumannAlgebra_lp_infty [∀ i, VonNeumannAlgebra (𝒜 i)] :
    VonNeumannAlgebra (lp 𝒜 ∞) := sorry

end DirectSum

variable (A) in
/-- **42V** (`von-neumann-examples`, vn.tex:262, Examples), part 4: a
C*-subalgebra `S` of a von Neumann algebra `A` is a **von Neumann
subalgebra** when the supremum (taken in `A`) of every nonempty bounded
directed set of self-adjoint elements of `S` again belongs to `S`.  (Such an
`S` is itself a von Neumann algebra.) -/
structure IsVNSubalgebra (S : StarSubalgebra ℂ A) : Prop where
  isClosed : IsClosed (S : Set A)
  dirSup_mem : ∀ (D : Set (selfAdjoint A)) (s : selfAdjoint A),
    (∀ d ∈ D, (d : A) ∈ S) → D.Nonempty → DirectedOn (· ≤ ·) D →
      IsLUB D s → (s : A) ∈ S

variable (A) in
/-- **42V** (`von-neumann-examples`, vn.tex:262, Examples), part 4a: the
least von Neumann subalgebra `W*(S)` of `A` containing a subset `S` — the
intersection of all von Neumann subalgebras containing `S`. -/
def wstar (S : Set A) : StarSubalgebra ℂ A :=
  sInf {T : StarSubalgebra ℂ A | IsVNSubalgebra A T ∧ S ⊆ T}

/-- **42V** (`von-neumann-examples`, vn.tex:262, Examples), part 4a,
well-definedness: `W*(S)` is indeed a von Neumann subalgebra containing `S`
(the intersection of von Neumann subalgebras is one). -/
theorem isVNSubalgebra_wstar [VonNeumannAlgebra A] (S : Set A) :
    IsVNSubalgebra A (wstar A S) ∧ S ⊆ wstar A S :=
  sorry

/-! **42V**, parts 5–7 (commutants, matrices, `L^∞(X)`) are stated at their
proper places: 65III (`Theses/A/VN/Projections.lean`), 49IV (`mn_vna` below)
and 51IX (`Linfty_vn` below). -/

/-! ## Parsec 430: counterexamples -/

/-- **43I** (`uwweaker`, vn.tex:341, Exercise), part 1:
`|ω(a)| ≤ ‖a‖_ω · ‖ω‖^½` for every np-functional `ω` and `a ∈ A` (for a
positive functional `‖ω‖ = ω(1)`, which is how the norm is rendered
here). -/
theorem uwweaker_1 [VonNeumannAlgebra A] (ω : NPFunctional A) (a : A) :
    ‖ω a‖ ≤ omegaNorm A ω a * Real.sqrt (ω 1).re :=
  sorry

/-- **43I** (`uwweaker`, vn.tex:341, Exercise), part 2: ultrastrong
convergence implies ultraweak convergence. -/
theorem uwweaker_2 [VonNeumannAlgebra A] {ι : Type*} (x : ι → A)
    (l : Filter ι) (a : A) (h : USTendsto x l a) : UWTendsto x l a :=
  sorry

/-- **43I** (`uwweaker`, vn.tex:341, Exercise), part 3: an ultraweakly closed
subset of `A` is ultrastrongly closed. -/
theorem uwweaker_3 [VonNeumannAlgebra A] (C : Set A)
    (h : @IsClosed A (ultraweak A) C) : @IsClosed A (ultrastrong A) C :=
  sorry

/-- **43Ia** (`infima-in-vna`, vn.tex:359, Exercise): every nonempty bounded
filtered (downwards directed) set `F` of self-adjoint elements of a von
Neumann algebra has an infimum, namely `⋀ F = -⋁{-d : d ∈ F}`. -/
theorem infima_in_vna [VonNeumannAlgebra A] (F : Set (selfAdjoint A))
    (hne : F.Nonempty) (hdir : DirectedOn (· ≥ ·) F) (hbdd : BddBelow F) :
    ∃ i : selfAdjoint A, IsGLB F i :=
  sorry

section Counterexamples

local notation "ℓ²" => lp (fun _ : ℕ => ℂ) 2

/-- The operator `|n⟩⟨m|` on `ℓ²` (**43II**, vn.tex:374, part 1). -/
noncomputable def ketbraNat (n m : ℕ) : ℓ² →L[ℂ] ℓ² :=
  ketbra (lp.single 2 n 1) (lp.single 2 m 1)

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 1:
computation rules `(|n⟩⟨m|)* = |m⟩⟨n|` and
`|n⟩⟨m| |l⟩⟨k| = δ_{m,l} |n⟩⟨k|`. -/
theorem vn_counterexamples_1 (k l m n : ℕ) :
    star (ketbraNat n m) = ketbraNat m n ∧
      ketbraNat n m * ketbraNat l k =
        (if m = l then ketbraNat n k else 0) :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 2 (first
half): `⋁_N ∑_{n≤N} |n⟩⟨n| = 1` in `B(ℓ²)`. -/
theorem vn_counterexamples_2_sup :
    IsLUB {T : ℓ² →L[ℂ] ℓ² |
        ∃ N : ℕ, T = ∑ n ∈ Finset.range N, ketbraNat n n}
      1 :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 2 (second
half): `(|n⟩⟨n|)_n` converges ultrastrongly (hence ultraweakly) to `0`; so
ultrastrong convergence does not imply norm convergence, and `‖·‖` is not
ultraweakly continuous. -/
theorem vn_counterexamples_2_tendsto :
    USTendsto (fun n : ℕ => ketbraNat n n) atTop 0 :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 3: already in
`ℂ`, the sequence `(e^{in})_n` does not converge ultraweakly, although the
products `e^{-in}·e^{in} = 1` are norm-bounded and converge; so ultraweak
convergence of `(b_α* b_α)_α` and norm-boundedness do not imply ultrastrong
convergence of `(b_α)_α`. -/
theorem vn_counterexamples_3 :
    ¬∃ z : ℂ, UWTendsto (fun n : ℕ => Complex.exp (Complex.I * n)) atTop z :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 4 (first
half): `(|0⟩⟨n|)_n` converges ultrastrongly to `0`. -/
theorem vn_counterexamples_4_ket :
    USTendsto (fun n : ℕ => ketbraNat 0 n) atTop 0 :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 4 (second
half): `(|n⟩⟨0|)_n` converges ultraweakly to `0` but does not converge
ultrastrongly at all. -/
theorem vn_counterexamples_4_bra :
    UWTendsto (fun n : ℕ => ketbraNat n 0) atTop 0 ∧
      ¬∃ T : ℓ² →L[ℂ] ℓ², USTendsto (fun n : ℕ => ketbraNat n 0) atTop T :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 4
(conclusion): `a ↦ a*` is not ultrastrongly continuous on `B(ℓ²)`. -/
theorem vn_counterexamples_4_star :
    ¬@Continuous (ℓ² →L[ℂ] ℓ²) (ℓ² →L[ℂ] ℓ²)
        (ultrastrong _) (ultrastrong _) star :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 5: the unit
ball of `B(ℓ²)` is not ultrastrongly compact (the sequence `(|0⟩⟨n|)_n` has
no ultrastrongly convergent subnet). -/
theorem vn_counterexamples_5 :
    ¬@IsCompact (ℓ² →L[ℂ] ℓ²) (ultrastrong _)
        (Metric.closedBall (0 : ℓ² →L[ℂ] ℓ²) 1) :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 6:
`|n⟩⟨0| + |0⟩⟨n| → 0` ultraweakly while its squares converge ultraweakly to
`|0⟩⟨0| ≠ 0`. -/
theorem vn_counterexamples_6 :
    UWTendsto (fun n : ℕ => ketbraNat n 0 + ketbraNat 0 n) atTop 0 ∧
      UWTendsto (fun n : ℕ => (ketbraNat n 0 + ketbraNat 0 n) ^ 2) atTop
        (ketbraNat 0 0) :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 6
(conclusion): squaring — hence also multiplication jointly, `|·|`, and
`√·` (part 8) — is not ultraweakly continuous on `B(ℓ²)`. -/
theorem vn_counterexamples_6_sq :
    ¬@Continuous (ℓ² →L[ℂ] ℓ²) (ℓ² →L[ℂ] ℓ²) (ultraweak _) (ultraweak _)
        (fun a => a * a) :=
  sorry

/-- **43II** (`vn-counterexamples`, vn.tex:374, Exercise), part 11: `B(ℓ²)`
is not ultraweakly complete: there is an ultraweakly Cauchy net (built from
an unbounded functional on `ℓ²` via Riesz representation on finite
dimensional subspaces) with no ultraweak limit. -/
theorem vn_counterexamples_11 :
    ∃ (ι : Type) (l : Filter ι), l.NeBot ∧ ∃ x : ι → (ℓ² →L[ℂ] ℓ²),
      (∀ ω : NPFunctional (ℓ² →L[ℂ] ℓ²), Cauchy (l.map fun i => ω (x i))) ∧
      ¬∃ T, UWTendsto x l T :=
  sorry

/-! **43II**, parts 7–10 (the maps `|·|_s`, `|·|_r` and squaring are not
ultrastrongly continuous, and multiplication is not jointly ultrastrongly
continuous even with the second argument bounded — via the "growing moving
bump" net) are skipped: they require ad-hoc directed index sets whose
formalization adds bulk without adding a reusable statement; their positive
counterparts are 74I (`proto_kaplansky`) and 45VI (`mult_jus_cont`). -/

end Counterexamples

/-! ## Parsec 440: elementary theory

**44I** (vn.tex:624): introduction — nothing to formalize. -/

/-- **44II** (`mult-polarization`, vn.tex:643, Exercise): the polarisation
identity `a* c b = ¼ ∑_{k<4} iᵏ (iᵏa + b)* c (iᵏa + b)` in a C*-algebra. -/
theorem mult_polarization (a b c : A) :
    star a * c * b =
      (4 : ℂ)⁻¹ • ∑ k ∈ Finset.range 4, Complex.I ^ k •
        (star ((Complex.I ^ k : ℂ) • a + b) * c *
          ((Complex.I ^ k : ℂ) • a + b)) :=
  sorry

/-- **44III** (`vanishing-effects`, vn.tex:654, Lemma): if a net `(x_α)_α` of
effects converges ultraweakly to `0` and `(b_α)_α` is a net with
`‖b_α‖ ≤ 1`, then `(x_α b_α)_α` converges ultraweakly to `0`. -/
theorem vanishing_effects [VonNeumannAlgebra A] {ι : Type*} {l : Filter ι}
    (x b : ι → A) (hx : ∀ i, x i ∈ effects A) (hb : ∀ i, ‖b i‖ ≤ 1)
    (h : UWTendsto x l 0) : UWTendsto (fun i => x i * b i) l 0 :=
  sorry

/-- **44VI** (`vna-supremum-uwlimit`, vn.tex:692): for a bounded directed set
`D` of self-adjoint elements, the net `(d)_{d∈D}` converges ultraweakly to
`⋁D`. -/
theorem vna_supremum_uwlimit [VonNeumannAlgebra A] (D : Set (selfAdjoint A))
    (h : D.Nonempty ∧ DirectedOn (· ≤ ·) D ∧ BddAbove D) :
    UWTendsto (fun d : D => (d : A)) atTop ((dirSup D h : selfAdjoint A) : A) :=
  sorry

/-- **44VII** (`vna-supremum-mult`, vn.tex:695): for a bounded directed `D`
and `a ∈ A`, `(d·a)_d` converges ultraweakly to `(⋁D)·a` and `(a*·d)_d` to
`a*·(⋁D)`. -/
theorem vna_supremum_mult [VonNeumannAlgebra A] (D : Set (selfAdjoint A))
    (h : D.Nonempty ∧ DirectedOn (· ≤ ·) D ∧ BddAbove D) (a : A) :
    UWTendsto (fun d : D => (d : A) * a) atTop
        (((dirSup D h : selfAdjoint A) : A) * a) ∧
      UWTendsto (fun d : D => star a * (d : A)) atTop
        (star a * ((dirSup D h : selfAdjoint A) : A)) :=
  sorry

/-- **44VIII** (`ad-normal`, vn.tex:704, Proposition):
`⋁_{d∈D} a* d a = a* (⋁D) a` for every bounded directed set `D` of
self-adjoint elements and every `a ∈ A` (stated as an `IsLUB` in `A`; upper
bounds of sets of self-adjoint elements are automatically self-adjoint). -/
theorem ad_normal [VonNeumannAlgebra A] (a : A) (D : Set (selfAdjoint A))
    (h : D.Nonempty ∧ DirectedOn (· ≤ ·) D ∧ BddAbove D) :
    IsLUB ((fun d : selfAdjoint A => star a * (d : A) * a) '' D)
      (star a * ((dirSup D h : selfAdjoint A) : A) * a) :=
  sorry

/-- **44XI** (`vn-positive-basic`, vn.tex:756, Exercise), preliminary claim:
the np-functionals on a von Neumann algebra are not only faithful but order
separating. -/
theorem np_orderSeparating [VonNeumannAlgebra A] (a b : A)
    (ha : IsSelfAdjoint a) (hb : IsSelfAdjoint b)
    (h : ∀ ω : NPFunctional A, ω a ≤ ω b) : a ≤ b :=
  sorry

/-- **44XI** (`vn-positive-basic`, vn.tex:756, Exercise), part 1: the
ultraweak and ultrastrong topologies are Hausdorff. -/
theorem vn_positive_basic_1 [VonNeumannAlgebra A] :
    @T2Space A (ultraweak A) ∧ @T2Space A (ultrastrong A) :=
  sorry

/-- **44XI** (`vn-positive-basic`, vn.tex:756, Exercise), part 2: the
positive cone, the self-adjoint part, and the set of effects are ultraweakly
(hence, by **43I**, ultrastrongly) closed. -/
theorem vn_positive_basic_2 [VonNeumannAlgebra A] :
    @IsClosed A (ultraweak A) {a : A | 0 ≤ a} ∧
      @IsClosed A (ultraweak A) {a : A | IsSelfAdjoint a} ∧
      @IsClosed A (ultraweak A) (effects A) :=
  sorry

/-- **44XI** (`vn-positive-basic`, vn.tex:756, Exercise), part 3: the unit
ball is ultrastrongly closed.  (It is ultraweakly closed too, but that is
seen only in 73VIII, `ultraclosed`.) -/
theorem vn_positive_basic_3 [VonNeumannAlgebra A] :
    @IsClosed A (ultrastrong A) (Metric.closedBall (0 : A) 1) :=
  sorry

/-- **44XIII** (`vna-supremum-commutes`, vn.tex:787): if `a` commutes with
every member of a bounded directed set `D` of self-adjoint elements, then
`a` commutes with `⋁D`. -/
theorem vna_supremum_commutes [VonNeumannAlgebra A]
    (D : Set (selfAdjoint A))
    (h : D.Nonempty ∧ DirectedOn (· ≤ ·) D ∧ BddAbove D) (a : A)
    (hc : ∀ d ∈ D, a * (d : A) = (d : A) * a) :
    a * ((dirSup D h : selfAdjoint A) : A) =
      ((dirSup D h : selfAdjoint A) : A) * a :=
  sorry

/-- **44XIV** (`vna-supremum-uslimit`, vn.tex:791): for a bounded directed
set `D` of self-adjoint elements, `(⋁D − d)² → 0` ultraweakly, i.e. the net
`(d)_{d∈D}` converges *ultrastrongly* to `⋁D`. -/
theorem vna_supremum_uslimit [VonNeumannAlgebra A] (D : Set (selfAdjoint A))
    (h : D.Nonempty ∧ DirectedOn (· ≤ ·) D ∧ BddAbove D) :
    USTendsto (fun d : D => (d : A)) atTop ((dirSup D h : selfAdjoint A) : A) :=
  sorry

/-- **44XV** (`p-uwcont`, vn.tex:799, Exercise): for a positive linear map
`f : A → B` between von Neumann algebras the following are equivalent:
(1) `f` is ultraweakly continuous; (2) `f` is ultraweakly continuous on
`[0,1]_A`; (3) `f` preserves suprema of bounded directed sets of
self-adjoint elements; (4) `ω ∘ f` is normal for every np-functional `ω` on
`B`.  In that case `f` is called **normal** (extending 42II). -/
theorem p_uwcont [VonNeumannAlgebra A] [VonNeumannAlgebra B]
    (f : A →ₚ[ℂ] B) :
    List.TFAE
      [@Continuous A B (ultraweak A) (ultraweak B) f,
       @ContinuousOn A B (ultraweak A) (ultraweak B) f (effects A),
       PreservesDirSups ⇑f,
       ∀ ω : NPFunctional B, PreservesDirSups fun a => ω (f a)] :=
  sorry

/-- **44XV** (`p-uwcont`, vn.tex:799, Exercise), conclusion: `b ↦ a* b a` is
ultraweakly continuous for every `a` in a von Neumann algebra (it is normal
by **44VIII**). -/
theorem p_uwcont_ad [VonNeumannAlgebra A] (a : A) :
    @Continuous A A (ultraweak A) (ultraweak A) fun b => star a * b * a :=
  sorry

/-! ## Parsec 450 -/

/-- **45I** (vn.tex:829, Exercise), part 1: a positive linear map between
von Neumann algebras which is ultrastrongly continuous on `[0,1]_A` is
normal. -/
theorem us_cont_normal [VonNeumannAlgebra A] [VonNeumannAlgebra B]
    (f : A →ₚ[ℂ] B)
    (h : @ContinuousOn A B (ultrastrong A) (ultrastrong B) f (effects A)) :
    PreservesDirSups ⇑f :=
  sorry

/-- **45I** (vn.tex:829, Exercise), part 2: the converse fails — there is a
normal positive map (e.g. the transpose on `B(ℓ²)`) that is not
ultrastrongly continuous. -/
theorem normal_not_us_cont :
    ∃ f : (lp (fun _ : ℕ => ℂ) 2 →L[ℂ] lp (fun _ : ℕ => ℂ) 2) →ₚ[ℂ]
        (lp (fun _ : ℕ => ℂ) 2 →L[ℂ] lp (fun _ : ℕ => ℂ) 2),
      PreservesDirSups ⇑f ∧
        ¬@Continuous _ _ (ultrastrong _) (ultrastrong _) ⇑f :=
  sorry

/-- **45II** (`cp-uscont`, vn.tex:841, Proposition): an ncp-map between von
Neumann algebras is ultrastrongly continuous. -/
theorem cp_uscont [VonNeumannAlgebra A] [VonNeumannAlgebra B]
    (f : NCPMap A B) :
    @Continuous A B (ultrastrong A) (ultrastrong B) ⇑f :=
  sorry

/-- **45IV** (`mult-uws-cont`, vn.tex:868, Exercise), part 1: `a ↦ b* a b`
is ultrastrongly continuous for every `b` in a von Neumann algebra. -/
theorem mult_uws_cont_ad [VonNeumannAlgebra A] (b : A) :
    @Continuous A A (ultrastrong A) (ultrastrong A) fun a => star b * a * b :=
  sorry

/-- **45IV** (`mult-uws-cont`, vn.tex:868, Exercise), part 2: multiplication
by a fixed element, `b ↦ ab` and `b ↦ ba`, is ultraweakly and ultrastrongly
continuous. -/
theorem mult_uws_cont [VonNeumannAlgebra A] (a : A) :
    (@Continuous A A (ultraweak A) (ultraweak A) fun b => a * b) ∧
      (@Continuous A A (ultraweak A) (ultraweak A) fun b => b * a) ∧
      (@Continuous A A (ultrastrong A) (ultrastrong A) fun b => a * b) ∧
      (@Continuous A A (ultrastrong A) (ultrastrong A) fun b => b * a) :=
  sorry

/-- **45VI** (`mult-jus-cont`, vn.tex:892, Proposition): if nets `(a_α)_α`,
`(b_α)_α` converge ultrastrongly to `a`, `b` respectively and `(a_α)_α` is
norm-bounded, then `(a_α b_α)_α` converges ultrastrongly to `ab`. -/
theorem mult_jus_cont [VonNeumannAlgebra A] {ι : Type*} {l : Filter ι}
    (x y : ι → A) (a b : A) (hx : USTendsto x l a) (hy : USTendsto y l b)
    (hbdd : ∃ C : ℝ, ∀ i, ‖x i‖ ≤ C) :
    USTendsto (fun i => x i * y i) l (a * b) :=
  sorry

/-! ## Parsec 460 -/

/-- **46II** (`usconv`, vn.tex:930, Exercise): a net `(b_α)_α` converges
ultrastrongly to `b` iff both `b_α* b_α → b* b` and `b_α → b`
ultraweakly. -/
theorem usconv [VonNeumannAlgebra A] {ι : Type*} (x : ι → A) (l : Filter ι)
    (b : A) :
    USTendsto x l b ↔
      UWTendsto (fun i => star (x i) * x i) l (star b * b) ∧
        UWTendsto x l b :=
  sorry

/-- **46III** (`npuws`, vn.tex:940, Exercise): for a positive functional `ω`
on a von Neumann algebra, the following are equivalent: (1) `ω` is normal;
(2) `ω` is ultraweakly continuous; (3) `ω` is ultrastrongly continuous. -/
theorem npuws [VonNeumannAlgebra A] (ω : A →ₚ[ℂ] ℂ) :
    List.TFAE
      [PreservesDirSups ⇑ω,
       @Continuous A ℂ (ultraweak A) _ ⇑ω,
       @Continuous A ℂ (ultrastrong A) _ ⇑ω] :=
  sorry

/-! ## Parsec 470: the categor(ies) of von Neumann algebras

**47II** (vn.tex:960, Definition): the categories `W*_cpsu` (von Neumann
algebras with normal cpsu-maps) and `W*_miu` (with nmiu-maps).  The
morphisms are formalized as `Theses.NCPSUMap` and `Theses.NMIUMap`; the
categorical structure itself is not bundled here — the product (47IV) and
equaliser (47V) below are stated through their universal properties, which
is what the thesis uses.

**47VI** (`vn-effectus`, vn.tex:1017): the sketch that `(W*_cpsu)^op` is an
effectus refers forward to the precise treatment in thesis B (eff.tex);
nothing is formalized here. -/

section Products

variable {I : Type*} (𝒜 : I → Type u) [∀ i, CStarAlgebra (𝒜 i)]
  [∀ i, Nontrivial (𝒜 i)] [∀ i, PartialOrder (𝒜 i)]
  [∀ i, StarOrderedRing (𝒜 i)] [∀ i, VonNeumannAlgebra (𝒜 i)]

/-- **47IV** (`vn-products`, vn.tex:988, Exercise), part 2: the coordinate
projections `π_j : ⊕ᵢ𝒜ᵢ → 𝒜ⱼ` are normal (they are miu-maps by cstar.tex
20aI). -/
theorem vn_products_proj_normal (j : I) :
    PreservesDirSups fun a : lp 𝒜 ∞ => (a : ∀ i, 𝒜 i) j :=
  sorry

/-- **47IV** (`vn-products`, vn.tex:988, Exercise), part 3 (`W*_miu`):
`⊕ᵢ𝒜ᵢ` with the projections `π_j` is the product of the `𝒜ᵢ` in `W*_miu`:
every family of nmiu-maps `f_i : B → 𝒜ᵢ` factors through a unique nmiu-map
`g : B → ⊕ᵢ𝒜ᵢ`. -/
theorem vn_products_nmiu {B : Type*} [CStarAlgebra B] [PartialOrder B]
    [StarOrderedRing B] [VonNeumannAlgebra B] (f : ∀ i, NMIUMap B (𝒜 i)) :
    ∃! g : NMIUMap B (lp 𝒜 ∞), ∀ (j : I) (b : B),
      ((g b : lp 𝒜 ∞) : ∀ i, 𝒜 i) j = f j b :=
  sorry

/-- **47IV** (`vn-products`, vn.tex:988, Exercise), part 3 (`W*_cpsu`):
`⊕ᵢ𝒜ᵢ` is also the product in `W*_cpsu`: every family of ncpsu-maps
`f_i : B → 𝒜ᵢ` factors through a unique ncpsu-map `g : B → ⊕ᵢ𝒜ᵢ`. -/
theorem vn_products_ncpsu {B : Type*} [CStarAlgebra B] [PartialOrder B]
    [StarOrderedRing B] [VonNeumannAlgebra B] (f : ∀ i, NCPSUMap B (𝒜 i)) :
    ∃! g : NCPSUMap B (lp 𝒜 ∞), ∀ (j : I) (b : B),
      ((g.toNCPMap b : lp 𝒜 ∞) : ∀ i, 𝒜 i) j = (f j).toNCPMap b :=
  sorry

end Products

section Elementary

variable {A B : Type u} [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
  [CStarAlgebra B] [PartialOrder B] [StarOrderedRing B]

/-- **47V** (`vn-equalisers`, vn.tex:1006, Exercise): for nmiu-maps
`f, g : A → B` between von Neumann algebras, the set
`E = {a ∈ A | f(a) = g(a)}` is (the carrier of) a von Neumann subalgebra of
`A`; its inclusion is then automatically the equaliser of `f` and `g` in
`W*_miu` and `W*_cpsu`. -/
theorem vn_equalisers [VonNeumannAlgebra A] [VonNeumannAlgebra B]
    (f g : NMIUMap A B) :
    ∃ S : StarSubalgebra ℂ A, IsVNSubalgebra A S ∧
      (S : Set A) = {a : A | f a = g a} :=
  sorry

/-! ## Parsec 480: the normal Gelfand–Naimark theorem -/

/-- A collection `Ω` of np-functionals is **faithful** (`separating`,
cstar.tex 21II): `a = 0` whenever `a ≥ 0` and `ω(a) = 0` for all
`ω ∈ Ω`. -/
def FaithfulCollection (Ω : Set (NPFunctional A)) : Prop :=
  ∀ a : A, 0 ≤ a → (∀ ω ∈ Ω, ω a = 0) → a = 0

/-- **48II** (`normal-faithful`, vn.tex:1082, Exercise): if `Ω` is a
faithful collection of np-functionals on `B`, then a positive linear map
`f : A → B` between von Neumann algebras is normal iff `ω ∘ f` is normal for
all `ω ∈ Ω`. -/
theorem normal_faithful [VonNeumannAlgebra A] [VonNeumannAlgebra B]
    (Ω : Set (NPFunctional B)) (hΩ : FaithfulCollection Ω) (f : A →ₚ[ℂ] B) :
    PreservesDirSups ⇑f ↔
      ∀ ω ∈ Ω, PreservesDirSups fun a => ω (f a) :=
  sorry

/-- **48III** (vn.tex:1091, Proposition): the GNS representation
`ρ_ω : A → B(H_ω)` of an np-functional `ω` on a von Neumann algebra is
normal.  (The GNS construction, cstar.tex 30VI, is not formalized, so this
is rendered as: `ω` admits a *normal* cyclic representation.) -/
theorem gns_normal [VonNeumannAlgebra A] (ω : NPFunctional A) :
    ∃ (ι : Type u) (ρ : MIUMap A
        (lp (fun _ : ι => ℂ) 2 →L[ℂ] lp (fun _ : ι => ℂ) 2))
      (ξ : lp (fun _ : ι => ℂ) 2),
      (∀ a : A, ω a = ⟪ξ, ρ a ξ⟫) ∧
        Dense (Set.range fun a : A => ρ a ξ) ∧
        PreservesDirSups ⇑ρ :=
  sorry

/-- **48V** (`varrho-Omega-normal`, vn.tex:1113, Exercise): the direct-sum
GNS representation `ρ_Ω` of any collection `Ω` of np-functionals on a von
Neumann algebra is normal (rendered, as in **48III**, as the existence of a
normal representation in which every `ω ∈ Ω` is a vector functional). -/
theorem varrho_Omega_normal [VonNeumannAlgebra A]
    (Ω : Set (NPFunctional A)) :
    ∃ (ι : Type u) (ρ : MIUMap A
        (lp (fun _ : ι => ℂ) 2 →L[ℂ] lp (fun _ : ι => ℂ) 2)),
      PreservesDirSups ⇑ρ ∧
        ∀ ω ∈ Ω, ∃ ξ : lp (fun _ : ι => ℂ) 2,
          ∀ a : A, ω a = ⟪ξ, ρ a ξ⟫ :=
  sorry

/-- **48VI** (`injective-nmiu-iso-on-image`, vn.tex:1120, Lemma), part 1:
the image of an injective nmiu-map `f : A → B` between von Neumann algebras
is a von Neumann subalgebra of `B`. -/
theorem injective_nmiu_iso_on_image_1 [VonNeumannAlgebra A]
    [VonNeumannAlgebra B] (f : NMIUMap A B) (hf : Function.Injective f) :
    IsVNSubalgebra B f.toStarAlgHom.range :=
  sorry

/-- **48VI** (`injective-nmiu-iso-on-image`, vn.tex:1120, Lemma), part 2: an
injective nmiu-map `f` restricts to an nmiu-isomorphism onto its image; in
particular it is an order embedding (whence its inverse on the image is
normal). -/
theorem injective_nmiu_iso_on_image_2 [VonNeumannAlgebra A]
    [VonNeumannAlgebra B] (f : NMIUMap A B) (hf : Function.Injective f)
    (a b : A) : f a ≤ f b ↔ a ≤ b :=
  sorry

/-- **48VIII** (`ngns`, vn.tex:1144, Theorem (normal Gelfand–Naimark)):
every von Neumann algebra is nmiu-isomorphic to a von Neumann algebra of
operators on a Hilbert space: there is an injective nmiu-map into some
`B(ℓ²(ι))` whose range is a von Neumann subalgebra. -/
theorem ngns (A : Type u) [CStarAlgebra A] [PartialOrder A]
    [StarOrderedRing A] [VonNeumannAlgebra A] :
    ∃ (ι : Type u) (f : NMIUMap A
        (lp (fun _ : ι => ℂ) 2 →L[ℂ] lp (fun _ : ι => ℂ) 2)),
      Function.Injective f ∧ IsVNSubalgebra _ f.toStarAlgHom.range :=
  sorry

/-! ## Parsec 490: matrices over a von Neumann algebra

**49II** (`bah-vn`, vn.tex:1177, Theorem): for a von Neumann algebra `𝒜`,
the C*-algebra `B^a(X)` of bounded adjointable module maps on a self-dual
Hilbert `𝒜`-module `X` is a von Neumann algebra, and `⟨x,(·)x⟩` is normal
for every `x ∈ X`.
-- FIXME(typecheck): not converted — the C*-algebra `B^a(X)` (cstar.tex
32XIII, `bax-cstar`) has no Mathlib counterpart and is not formalized in
`Theses/A/CStar`; its rôle here (producing `M_N(𝒜)`) is covered by the
direct statement 49IV below. -/

/-- **49IV** (`mn-vna`, vn.tex:1272, Exercise), part 1: the C*-algebra
`M_N(𝒜)` of `N×N`-matrices over a von Neumann algebra `𝒜` (Mathlib:
`CStarMatrix (Fin N) (Fin N) 𝒜`) is a von Neumann algebra. -/
instance mn_vna_1 [VonNeumannAlgebra A] (N : ℕ) :
    VonNeumannAlgebra (CStarMatrix (Fin N) (Fin N) A) := sorry

/-- **49IV** (`mn-vna`, vn.tex:1272, Exercise), part 2 (first half): for
`a₁,…,a_N, b₁,…,b_N ∈ 𝒜`, the map `M ↦ ∑ᵢⱼ aᵢ* Mᵢⱼ bⱼ : M_N(𝒜) → 𝒜` is
ultraweakly and ultrastrongly continuous; for `a = b` it is moreover normal
(and completely positive). -/
theorem mn_vna_2 [VonNeumannAlgebra A] (N : ℕ) (a b : Fin N → A) :
    @Continuous _ _ (ultraweak (CStarMatrix (Fin N) (Fin N) A)) (ultraweak A)
        (fun M : CStarMatrix (Fin N) (Fin N) A =>
          ∑ i, ∑ j, star (a i) * CStarMatrix.ofMatrix.symm M i j * b j) ∧
      @Continuous _ _ (ultrastrong (CStarMatrix (Fin N) (Fin N) A))
        (ultrastrong A)
        (fun M : CStarMatrix (Fin N) (Fin N) A =>
          ∑ i, ∑ j, star (a i) * CStarMatrix.ofMatrix.symm M i j * b j) ∧
      PreservesDirSups (fun M : CStarMatrix (Fin N) (Fin N) A =>
        ∑ i, ∑ j, star (a i) * CStarMatrix.ofMatrix.symm M i j * a j) :=
  sorry

/-- **49IV** (`mn-vna`, vn.tex:1272, Exercise), part 2 (second half): a net
in `M_N(𝒜)` converges ultraweakly (resp. ultrastrongly) iff it does so
entrywise. -/
theorem mn_vna_2' [VonNeumannAlgebra A] (N : ℕ) {ι : Type*} (l : Filter ι)
    (M : ι → CStarMatrix (Fin N) (Fin N) A)
    (M₀ : CStarMatrix (Fin N) (Fin N) A) :
    (UWTendsto M l M₀ ↔ ∀ i j,
        UWTendsto (fun α => CStarMatrix.ofMatrix.symm (M α) i j) l
          (CStarMatrix.ofMatrix.symm M₀ i j)) ∧
      (USTendsto M l M₀ ↔ ∀ i j,
        USTendsto (fun α => CStarMatrix.ofMatrix.symm (M α) i j) l
          (CStarMatrix.ofMatrix.symm M₀ i j)) :=
  sorry

/-- **49IV** (`mn-vna`, vn.tex:1272, Exercise), part 3: for an ncp-map
`f : 𝒜 → ℬ` between von Neumann algebras, the entrywise map
`M_N f : M_N(𝒜) → M_N(ℬ)` (cstar.tex 33III, `mnf`) is normal. -/
theorem mn_vna_3 [VonNeumannAlgebra A] [VonNeumannAlgebra B] (N : ℕ)
    (f : NCPMap A B) :
    PreservesDirSups fun M : CStarMatrix (Fin N) (Fin N) A =>
      CStarMatrix.ofMatrix ((CStarMatrix.ofMatrix.symm M).map f) :=
  sorry

end Elementary

/-! ## Parsecs 500–510: `L^∞(X)` of a finite complete measure space

**50I** (`linfty-example`, vn.tex:1313) and **51I–51VI**
(`measure-theory-recap`, vn.tex:1369): recapitulation of measure theory and
the construction of `𝓛^∞(X)` and `L^∞(X)`, including the counterexample
that `𝓛^∞([0,1])` is *not* a von Neumann algebra (51III) — narrative;
nothing converted separately.  The quotient C*-algebra `L^∞(X)` has no
Mathlib counterpart (Mathlib's `Lp E ∞ μ` carries no multiplicative
structure), so 51IX below is stated existentially. -/

section Measure

variable {A : Type u} [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A]

/-- **51VII** (vn.tex:1581, Proposition), part 1: a C*-algebra `A` with a
faithful positive functional `τ` such that every bounded ascending sequence
of self-adjoint elements has a supremum preserved by `τ` is a von Neumann
algebra. -/
theorem vna_of_faithful_countably_normal_1 (τ : A →ₚ[ℂ] ℂ)
    (hfaith : ∀ a : A, 0 ≤ a → τ a = 0 → a = 0)
    (hsup : ∀ a : ℕ → selfAdjoint A, Monotone a → BddAbove (Set.range a) →
      ∃ s : selfAdjoint A, IsLUB (Set.range a) s ∧
        IsLUB (Set.range fun n => τ (a n : A)) (τ (s : A))) :
    VonNeumannAlgebra A :=
  sorry

/-- **51VII** (vn.tex:1581, Proposition), part 2: such a `τ` is moreover
normal. -/
theorem vna_of_faithful_countably_normal_2 (τ : A →ₚ[ℂ] ℂ)
    (hfaith : ∀ a : A, 0 ≤ a → τ a = 0 → a = 0)
    (hsup : ∀ a : ℕ → selfAdjoint A, Monotone a → BddAbove (Set.range a) →
      ∃ s : selfAdjoint A, IsLUB (Set.range a) s ∧
        IsLUB (Set.range fun n => τ (a n : A)) (τ (s : A))) :
    PreservesDirSups ⇑τ :=
  sorry

variable (X : Type u) [MeasurableSpace X] in
/-- A function `X → ℂ` on a measure(able) space that is measurable and
bounded — a member of the thesis's `𝓛^∞(X)` (vn.tex 51II). -/
def IsBoundedMeasurable (f : X → ℂ) : Prop :=
  Measurable f ∧ ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C

/-- **51IX** (`Linfty-vn`, vn.tex:1638, Corollary): for a finite complete
measure space `X`, the C*-algebra `L^∞(X)` — bounded measurable functions
modulo equality almost everywhere — is a commutative von Neumann algebra on
which integration is a faithful normal positive functional.  (Since Mathlib
has no C*-algebra of classes of bounded measurable functions, `L^∞(X)` is
rendered as an existentially quantified commutative von Neumann algebra `𝒜`
with a quotient map `q` from `𝓛^∞(X)`.) -/
theorem Linfty_vn (X : Type u) [MeasurableSpace X] (μ : Measure X)
    [IsFiniteMeasure μ] (hμ : μ.IsComplete) :
    ∃ (𝒜 : Type u) (_ : CommCStarAlgebra 𝒜) (_ : PartialOrder 𝒜)
      (_ : StarOrderedRing 𝒜) (q : (X → ℂ) → 𝒜) (τ : 𝒜 → ℂ),
      VonNeumannAlgebra 𝒜 ∧
      -- `q` is a surjective miu-map on `𝓛^∞(X)` with kernel the a.e.-null
      -- functions:
      (∀ y : 𝒜, ∃ f, IsBoundedMeasurable X f ∧ q f = y) ∧
      (∀ f g, IsBoundedMeasurable X f → IsBoundedMeasurable X g →
        q (f + g) = q f + q g ∧ q (f * g) = q f * q g ∧
          q (star f) = star (q f)) ∧
      q 1 = 1 ∧
      (∀ f, IsBoundedMeasurable X f → (q f = 0 ↔ f =ᵐ[μ] 0)) ∧
      -- integration descends to a faithful normal positive functional:
      (∃ τ' : NPFunctional 𝒜, ⇑τ' = τ) ∧
      (∀ y : 𝒜, 0 ≤ y → τ y = 0 → y = 0) ∧
      (∀ f, IsBoundedMeasurable X f → τ (q f) = ∫ x, f x ∂μ) :=
  sorry

end Measure

/-! ## Parsec 520 (`classification-cvn`): meagre subsets

**52I** (vn.tex:1648): plan of the classification — nothing to formalize.

**52II** (`meagre`, vn.tex:1711, Definition): *meagre* subsets — a subset
contained in a countable increasing union of closed sets with empty
interior — coincide with Mathlib's `IsMeagre` (complement in the `residual`
filter); we use Mathlib's notion.  The derived notions `≈` and *almost
clopen* are defined here.

**52IIIa** (vn.tex:1767): meagreness vs. negligibility — narrative. -/

section Meagre

variable {X : Type*} [TopologicalSpace X]

/-- **52II** (`meagre`, vn.tex:1711, Definition), part 2: `A ≈ B` iff the
symmetric difference `A ∪ B \ A ∩ B` is meagre. -/
def MeagreEquiv (s t : Set X) : Prop := IsMeagre (s ∆ t)

/-- **52II** (`meagre`, vn.tex:1711, Definition), part 3: a subset is
**almost clopen** when it is `≈` to a clopen subset. -/
def AlmostClopen (s : Set X) : Prop := ∃ C : Set X, IsClopen C ∧ MeagreEquiv s C

/-- **52III** (`meagre-basic`, vn.tex:1737, Exercise), part 1: a countable
union of meagre sets is meagre.  (Mathlib: `IsMeagre` is closed under
countable unions.) -/
theorem meagre_basic_1 (s : ℕ → Set X) (h : ∀ n, IsMeagre (s n)) :
    IsMeagre (⋃ n, s n) :=
  sorry

/-- **52III** (`meagre-basic`, vn.tex:1737, Exercise), part 2: a subset of a
meagre set is meagre. -/
theorem meagre_basic_2 (s t : Set X) (hst : s ⊆ t) (h : IsMeagre t) :
    IsMeagre s :=
  sorry

/-- **52III** (`meagre-basic`, vn.tex:1737, Exercise), part 3:
`closure U ≈ U` for every open `U`. -/
theorem meagre_basic_3 (U : Set X) (hU : IsOpen U) :
    MeagreEquiv (closure U) U :=
  sorry

/-- **52III** (`meagre-basic`, vn.tex:1737, Exercise), part 4:
`⋃ₙ Aₙ ≈ ⋃ₙ Bₙ` when `Aₙ ≈ Bₙ` for all `n`. -/
theorem meagre_basic_4 (s t : ℕ → Set X) (h : ∀ n, MeagreEquiv (s n) (t n)) :
    MeagreEquiv (⋃ n, s n) (⋃ n, t n) :=
  sorry

/-- **52III** (`meagre-basic`, vn.tex:1737, Exercise), part 5:
`A \ B ≈ A' \ B'` when `A ≈ A'` and `B ≈ B'`. -/
theorem meagre_basic_5 (s s' t t' : Set X) (hs : MeagreEquiv s s')
    (ht : MeagreEquiv t t') : MeagreEquiv (s \ t) (s' \ t') :=
  sorry

/-- **52III** (`meagre-basic`, vn.tex:1737, Exercise), part 6: unions and
differences of almost clopen sets are almost clopen. -/
theorem meagre_basic_6 (s t : Set X) (hs : AlmostClopen s)
    (ht : AlmostClopen t) : AlmostClopen (s ∪ t) ∧ AlmostClopen (s \ t) :=
  sorry

end Meagre

/-- **52IIIb** (vn.tex:1776, Example): there is a meagre subset of `[0,1]`
of Lebesgue measure `1`. -/
theorem meagre_full_measure :
    ∃ s : Set ℝ, s ⊆ Set.Icc 0 1 ∧ IsMeagre s ∧ volume s = 1 :=
  sorry

/-! ## Parsec 530: extremal disconnectedness of the spectrum -/

section Gelfand

variable (A : Type*) [CommCStarAlgebra A] [PartialOrder A] [StarOrderedRing A]

open WeakDual

/-- **53II** (`ngelfand`, vn.tex:1807, Exercise), part 1: for a commutative
von Neumann algebra `A`, the C*-algebra `C(spec A)` of continuous functions
on its spectrum is a (commutative) von Neumann algebra. -/
theorem ngelfand_vna [VonNeumannAlgebra A] :
    VonNeumannAlgebra C(characterSpace ℂ A, ℂ) :=
  sorry

/-- **53II** (`ngelfand`, vn.tex:1807, Exercise), part 2: the Gelfand
representation `γ_A : A → C(spec A)` (Mathlib: `gelfandStarTransform`), an
miu-isomorphism by cstar.tex 27XXVII, is normal, hence an
nmiu-isomorphism. -/
theorem ngelfand_normal [VonNeumannAlgebra A] :
    PreservesDirSups ⇑(gelfandStarTransform A) :=
  sorry

/-- **53III** (`vn-spectrum-extremally-disconnected`, vn.tex:1821,
Proposition): the spectrum of a commutative von Neumann algebra is
extremally disconnected: the closure of every open set is open. -/
theorem vn_spectrum_extremally_disconnected [VonNeumannAlgebra A] :
    ExtremallyDisconnected (characterSpace ℂ A) :=
  sorry

end Gelfand

section AlmostClopenSigma

variable (X : Type*) [TopologicalSpace X]

/-- The σ-algebra generated by the almost clopen subsets of a topological
space (auxiliary for **53V** and **54XI**). -/
def almostClopenMS : MeasurableSpace X :=
  MeasurableSpace.generateFrom {s : Set X | AlmostClopen s}

/-- **53V** (vn.tex:1876, Corollary): in an extremally disconnected
topological space the almost clopen subsets form a σ-algebra, i.e. every
member of the σ-algebra they generate is itself almost clopen. -/
theorem almostClopen_sigmaAlgebra [ExtremallyDisconnected X] (s : Set X) :
    MeasurableSet[almostClopenMS X] s ↔ AlmostClopen s :=
  sorry

end AlmostClopenSigma

/-! ## Parsec 540: Baire category and the classification -/

section Baire

variable {X : Type*} [TopologicalSpace X] [CompactSpace X] [T2Space X]

/-- **54II** (`baire-category-theorem`, vn.tex:1909, Baire category
theorem): a meagre subset of a compact Hausdorff space has empty
interior. -/
theorem baire_category_theorem (s : Set X) (h : IsMeagre s) :
    interior s = ∅ :=
  sorry

/-- **54IV** (`approx-closure`, vn.tex:1949, Lemma): for open subsets `U`,
`V` of a compact Hausdorff space:
`U ≈ V ↔ closure U ≈ closure V ↔ closure U = closure V`. -/
theorem approx_closure (U V : Set X) (hU : IsOpen U) (hV : IsOpen V) :
    (MeagreEquiv U V ↔ MeagreEquiv (closure U) (closure V)) ∧
      (MeagreEquiv (closure U) (closure V) ↔ closure U = closure V) :=
  sorry

/-- **54VI** (vn.tex:1975, Corollary; proof label
`almost-meagre-fundamental`): an almost clopen subset of a compact Hausdorff
space is `≈` to exactly one clopen set. -/
theorem almost_meagre_fundamental (s : Set X) (hs : AlmostClopen s) :
    ∃! C : Set X, IsClopen C ∧ MeagreEquiv s C :=
  sorry

/-- **54IX** (`open-almost-clopen`, vn.tex:1991, Proposition): a compact
Hausdorff space is extremally disconnected iff every open subset is almost
clopen. -/
theorem open_almost_clopen :
    ExtremallyDisconnected X ↔ ∀ U : Set X, IsOpen U → AlmostClopen U :=
  sorry

end Baire

section CVNFaithful

variable {A : Type*} [CommCStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
  [VonNeumannAlgebra A]

open WeakDual

/-- **54XI** (`cvn-faithful`, vn.tex:2014, Theorem), part 1: for a
commutative von Neumann algebra `A` with a faithful np-functional `ω` there
is a unique measure `μ` on the σ-algebra of almost clopen subsets of
`spec A` such that `μ(s) = 0` iff `s` is meagre, and
`μ(C) = ω(γ_A⁻¹(𝟙_C))` for clopen `C`; and `μ` is finite and complete. -/
theorem cvn_faithful_1 (ω : NPFunctional A)
    (hω : ∀ a : A, 0 ≤ a → ω a = 0 → a = 0) :
    ∃! μ : @Measure (characterSpace ℂ A) (almostClopenMS _),
      (∀ s : Set (characterSpace ℂ A), AlmostClopen s →
        (μ s = 0 ↔ IsMeagre s)) ∧
      (∀ (C : Set (characterSpace ℂ A)), IsClopen C →
        ∀ f : C(characterSpace ℂ A, ℂ),
          (∀ x, f x = C.indicator (fun _ => 1) x) →
          μ C = ENNReal.ofReal (ω ((gelfandStarTransform A).symm f)).re) ∧
      @IsFiniteMeasure _ (almostClopenMS _) μ ∧
      @Measure.IsComplete _ (almostClopenMS _) μ :=
  sorry

/-- **54XI** (`cvn-faithful`, vn.tex:2014, Theorem), part 2: with respect to
this measure(-space) structure, a bounded function `f : spec A → ℂ` is
measurable iff it is continuous almost everywhere. -/
theorem cvn_faithful_2 (ω : NPFunctional A)
    (hω : ∀ a : A, 0 ≤ a → ω a = 0 → a = 0)
    (μ : @Measure (characterSpace ℂ A) (almostClopenMS _))
    (hμ : ∀ s : Set (characterSpace ℂ A), AlmostClopen s →
      (μ s = 0 ↔ IsMeagre s))
    (f : characterSpace ℂ A → ℂ) (hf : ∃ C : ℝ, ∀ x, ‖f x‖ ≤ C) :
    @Measurable _ _ (almostClopenMS _) _ f ↔
      ∃ E : Set (characterSpace ℂ A), μ E = 0 ∧ ∀ x ∈ Eᶜ, ContinuousAt f x :=
  sorry

/-- **54XI** (`cvn-faithful`, vn.tex:2014, Theorem), part 3: the diagram
commutes: `∫ f dμ = ω(γ_A⁻¹(f))` for every continuous `f` on `spec A`.
(The full statement — that `f ↦ f°` is an nmiu-isomorphism
`C(spec A) → L^∞(spec A)` — is not rendered since `L^∞` has no Mathlib
carrier; cf. 51IX.) -/
theorem cvn_faithful_3 (ω : NPFunctional A)
    (hω : ∀ a : A, 0 ≤ a → ω a = 0 → a = 0)
    (μ : @Measure (characterSpace ℂ A) (almostClopenMS _))
    (hμ : ∀ s : Set (characterSpace ℂ A), AlmostClopen s →
      (μ s = 0 ↔ IsMeagre s))
    (hμC : ∀ (C : Set (characterSpace ℂ A)), IsClopen C →
      ∀ f : C(characterSpace ℂ A, ℂ),
        (∀ x, f x = C.indicator (fun _ => 1) x) →
        μ C = ENNReal.ofReal (ω ((gelfandStarTransform A).symm f)).re)
    (f : C(characterSpace ℂ A, ℂ)) :
    ∫ x, f x ∂μ = ω ((gelfandStarTransform A).symm f) :=
  sorry

/-! **54XIII** (vn.tex:2172): transition to the projections needed for the
full classification (70III, `Theses/A/VN/Projections.lean`) — nothing to
formalize. -/

end CVNFaithful

end Topologies

end Theses.A.VN
